//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/spec/AlgorithmParameterSpec.java
//

#ifndef _JavaSecuritySpecAlgorithmParameterSpec_H_
#define _JavaSecuritySpecAlgorithmParameterSpec_H_

#import "JreEmulation.h"

@protocol JavaSecuritySpecAlgorithmParameterSpec < NSObject, JavaObject >

@end

__attribute__((always_inline)) inline void JavaSecuritySpecAlgorithmParameterSpec_init() {}

#endif // _JavaSecuritySpecAlgorithmParameterSpec_H_
