//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/spec/DSAPublicKeySpec.java
//

#ifndef _JavaSecuritySpecDSAPublicKeySpec_H_
#define _JavaSecuritySpecDSAPublicKeySpec_H_

@class JavaMathBigInteger;

#import "JreEmulation.h"
#include "java/security/spec/KeySpec.h"

@interface JavaSecuritySpecDSAPublicKeySpec : NSObject < JavaSecuritySpecKeySpec > {
 @public
  JavaMathBigInteger *y_;
  JavaMathBigInteger *p_;
  JavaMathBigInteger *q_;
  JavaMathBigInteger *g_;
}

- (instancetype)initWithJavaMathBigInteger:(JavaMathBigInteger *)y
                    withJavaMathBigInteger:(JavaMathBigInteger *)p
                    withJavaMathBigInteger:(JavaMathBigInteger *)q
                    withJavaMathBigInteger:(JavaMathBigInteger *)g;

- (JavaMathBigInteger *)getG;

- (JavaMathBigInteger *)getP;

- (JavaMathBigInteger *)getQ;

- (JavaMathBigInteger *)getY;

- (void)copyAllFieldsTo:(JavaSecuritySpecDSAPublicKeySpec *)other;

@end

__attribute__((always_inline)) inline void JavaSecuritySpecDSAPublicKeySpec_init() {}

J2OBJC_FIELD_SETTER(JavaSecuritySpecDSAPublicKeySpec, y_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(JavaSecuritySpecDSAPublicKeySpec, p_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(JavaSecuritySpecDSAPublicKeySpec, q_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(JavaSecuritySpecDSAPublicKeySpec, g_, JavaMathBigInteger *)

#endif // _JavaSecuritySpecDSAPublicKeySpec_H_
