//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/spec/DSAParameterSpec.java
//

#ifndef _JavaSecuritySpecDSAParameterSpec_H_
#define _JavaSecuritySpecDSAParameterSpec_H_

#include "J2ObjC_header.h"
#include "java/security/interfaces/DSAParams.h"
#include "java/security/spec/AlgorithmParameterSpec.h"

@class JavaMathBigInteger;

@interface JavaSecuritySpecDSAParameterSpec : NSObject < JavaSecuritySpecAlgorithmParameterSpec, JavaSecurityInterfacesDSAParams >

#pragma mark Public

- (instancetype)initWithJavaMathBigInteger:(JavaMathBigInteger *)p
                    withJavaMathBigInteger:(JavaMathBigInteger *)q
                    withJavaMathBigInteger:(JavaMathBigInteger *)g;

- (JavaMathBigInteger *)getG;

- (JavaMathBigInteger *)getP;

- (JavaMathBigInteger *)getQ;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaSecuritySpecDSAParameterSpec)

FOUNDATION_EXPORT void JavaSecuritySpecDSAParameterSpec_initWithJavaMathBigInteger_withJavaMathBigInteger_withJavaMathBigInteger_(JavaSecuritySpecDSAParameterSpec *self, JavaMathBigInteger *p, JavaMathBigInteger *q, JavaMathBigInteger *g);

FOUNDATION_EXPORT JavaSecuritySpecDSAParameterSpec *new_JavaSecuritySpecDSAParameterSpec_initWithJavaMathBigInteger_withJavaMathBigInteger_withJavaMathBigInteger_(JavaMathBigInteger *p, JavaMathBigInteger *q, JavaMathBigInteger *g) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaSecuritySpecDSAParameterSpec)

#endif // _JavaSecuritySpecDSAParameterSpec_H_
