//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/spec/DSAPrivateKeySpec.java
//

#ifndef _JavaSecuritySpecDSAPrivateKeySpec_H_
#define _JavaSecuritySpecDSAPrivateKeySpec_H_

@class JavaMathBigInteger;

#import "JreEmulation.h"
#include "java/security/spec/KeySpec.h"

@interface JavaSecuritySpecDSAPrivateKeySpec : NSObject < JavaSecuritySpecKeySpec > {
 @public
  JavaMathBigInteger *x_;
  JavaMathBigInteger *p_;
  JavaMathBigInteger *q_;
  JavaMathBigInteger *g_;
}

- (instancetype)initWithJavaMathBigInteger:(JavaMathBigInteger *)x
                    withJavaMathBigInteger:(JavaMathBigInteger *)p
                    withJavaMathBigInteger:(JavaMathBigInteger *)q
                    withJavaMathBigInteger:(JavaMathBigInteger *)g;

- (JavaMathBigInteger *)getG;

- (JavaMathBigInteger *)getP;

- (JavaMathBigInteger *)getQ;

- (JavaMathBigInteger *)getX;

- (void)copyAllFieldsTo:(JavaSecuritySpecDSAPrivateKeySpec *)other;

@end

__attribute__((always_inline)) inline void JavaSecuritySpecDSAPrivateKeySpec_init() {}

J2OBJC_FIELD_SETTER(JavaSecuritySpecDSAPrivateKeySpec, x_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(JavaSecuritySpecDSAPrivateKeySpec, p_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(JavaSecuritySpecDSAPrivateKeySpec, q_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(JavaSecuritySpecDSAPrivateKeySpec, g_, JavaMathBigInteger *)

#endif // _JavaSecuritySpecDSAPrivateKeySpec_H_
