//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/spec/ECFieldF2m.java
//

#ifndef _JavaSecuritySpecECFieldF2m_H_
#define _JavaSecuritySpecECFieldF2m_H_

@class IOSIntArray;
@class JavaMathBigInteger;

#import "JreEmulation.h"
#include "java/security/spec/ECField.h"

#define JavaSecuritySpecECFieldF2m_PPB_LEN 5
#define JavaSecuritySpecECFieldF2m_PPB_MID_LEN 3
#define JavaSecuritySpecECFieldF2m_TPB_LEN 3
#define JavaSecuritySpecECFieldF2m_TPB_MID_LEN 1

@interface JavaSecuritySpecECFieldF2m : NSObject < JavaSecuritySpecECField > {
 @public
  jint m_;
  JavaMathBigInteger *rp_;
  IOSIntArray *ks_;
}

- (instancetype)initWithInt:(jint)m;

- (instancetype)initWithInt:(jint)m
     withJavaMathBigInteger:(JavaMathBigInteger *)rp;

- (instancetype)initWithInt:(jint)m
               withIntArray:(IOSIntArray *)ks;

- (jboolean)isEqual:(id)obj;

- (jint)getFieldSize;

- (jint)getM;

- (IOSIntArray *)getMidTermsOfReductionPolynomial;

- (JavaMathBigInteger *)getReductionPolynomial;

- (NSUInteger)hash;

- (void)copyAllFieldsTo:(JavaSecuritySpecECFieldF2m *)other;

@end

__attribute__((always_inline)) inline void JavaSecuritySpecECFieldF2m_init() {}

J2OBJC_FIELD_SETTER(JavaSecuritySpecECFieldF2m, rp_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(JavaSecuritySpecECFieldF2m, ks_, IOSIntArray *)

J2OBJC_STATIC_FIELD_GETTER(JavaSecuritySpecECFieldF2m, TPB_MID_LEN, jint)

J2OBJC_STATIC_FIELD_GETTER(JavaSecuritySpecECFieldF2m, PPB_MID_LEN, jint)

J2OBJC_STATIC_FIELD_GETTER(JavaSecuritySpecECFieldF2m, TPB_LEN, jint)

J2OBJC_STATIC_FIELD_GETTER(JavaSecuritySpecECFieldF2m, PPB_LEN, jint)

#endif // _JavaSecuritySpecECFieldF2m_H_
