//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/spec/ECField.java
//

#ifndef _JavaSecuritySpecECField_H_
#define _JavaSecuritySpecECField_H_

#import "JreEmulation.h"

@protocol JavaSecuritySpecECField < NSObject, JavaObject >

- (jint)getFieldSize;

@end

__attribute__((always_inline)) inline void JavaSecuritySpecECField_init() {}

#endif // _JavaSecuritySpecECField_H_
