//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/spec/ECGenParameterSpec.java
//

#ifndef _JavaSecuritySpecECGenParameterSpec_H_
#define _JavaSecuritySpecECGenParameterSpec_H_

#import "JreEmulation.h"
#include "java/security/spec/AlgorithmParameterSpec.h"

@interface JavaSecuritySpecECGenParameterSpec : NSObject < JavaSecuritySpecAlgorithmParameterSpec > {
 @public
  NSString *name_;
}

- (instancetype)initWithNSString:(NSString *)name;

- (NSString *)getName;

- (void)copyAllFieldsTo:(JavaSecuritySpecECGenParameterSpec *)other;

@end

__attribute__((always_inline)) inline void JavaSecuritySpecECGenParameterSpec_init() {}

J2OBJC_FIELD_SETTER(JavaSecuritySpecECGenParameterSpec, name_, NSString *)

#endif // _JavaSecuritySpecECGenParameterSpec_H_
