//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/spec/ECParameterSpec.java
//

#ifndef _JavaSecuritySpecECParameterSpec_H_
#define _JavaSecuritySpecECParameterSpec_H_

@class JavaMathBigInteger;
@class JavaSecuritySpecECPoint;
@class JavaSecuritySpecEllipticCurve;

#import "JreEmulation.h"
#include "java/security/spec/AlgorithmParameterSpec.h"

@interface JavaSecuritySpecECParameterSpec : NSObject < JavaSecuritySpecAlgorithmParameterSpec > {
 @public
  JavaSecuritySpecEllipticCurve *curve_;
  JavaSecuritySpecECPoint *generator_;
  JavaMathBigInteger *order_;
  jint cofactor_;
  NSString *curveName_;
}

- (instancetype)initWithJavaSecuritySpecEllipticCurve:(JavaSecuritySpecEllipticCurve *)curve
                          withJavaSecuritySpecECPoint:(JavaSecuritySpecECPoint *)generator
                               withJavaMathBigInteger:(JavaMathBigInteger *)order
                                              withInt:(jint)cofactor;

- (instancetype)initWithJavaSecuritySpecEllipticCurve:(JavaSecuritySpecEllipticCurve *)curve
                          withJavaSecuritySpecECPoint:(JavaSecuritySpecECPoint *)generator
                               withJavaMathBigInteger:(JavaMathBigInteger *)order
                                              withInt:(jint)cofactor
                                         withNSString:(NSString *)curveName;

- (jint)getCofactor;

- (JavaSecuritySpecEllipticCurve *)getCurve;

- (JavaSecuritySpecECPoint *)getGenerator;

- (JavaMathBigInteger *)getOrder;

- (NSString *)getCurveName;

- (void)copyAllFieldsTo:(JavaSecuritySpecECParameterSpec *)other;

@end

__attribute__((always_inline)) inline void JavaSecuritySpecECParameterSpec_init() {}

J2OBJC_FIELD_SETTER(JavaSecuritySpecECParameterSpec, curve_, JavaSecuritySpecEllipticCurve *)
J2OBJC_FIELD_SETTER(JavaSecuritySpecECParameterSpec, generator_, JavaSecuritySpecECPoint *)
J2OBJC_FIELD_SETTER(JavaSecuritySpecECParameterSpec, order_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(JavaSecuritySpecECParameterSpec, curveName_, NSString *)

#endif // _JavaSecuritySpecECParameterSpec_H_
