//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/spec/ECPoint.java
//

#ifndef _JavaSecuritySpecECPoint_H_
#define _JavaSecuritySpecECPoint_H_

@class JavaMathBigInteger;

#import "JreEmulation.h"

@interface JavaSecuritySpecECPoint : NSObject {
 @public
  JavaMathBigInteger *affineX_;
  JavaMathBigInteger *affineY_;
}

- (instancetype)init;

- (instancetype)initWithJavaMathBigInteger:(JavaMathBigInteger *)affineX
                    withJavaMathBigInteger:(JavaMathBigInteger *)affineY;

- (JavaMathBigInteger *)getAffineX;

- (JavaMathBigInteger *)getAffineY;

- (jboolean)isEqual:(id)other;

- (NSUInteger)hash;

- (void)copyAllFieldsTo:(JavaSecuritySpecECPoint *)other;

@end

FOUNDATION_EXPORT BOOL JavaSecuritySpecECPoint_initialized;
J2OBJC_STATIC_INIT(JavaSecuritySpecECPoint)

J2OBJC_FIELD_SETTER(JavaSecuritySpecECPoint, affineX_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(JavaSecuritySpecECPoint, affineY_, JavaMathBigInteger *)

FOUNDATION_EXPORT JavaSecuritySpecECPoint *JavaSecuritySpecECPoint_POINT_INFINITY_;
J2OBJC_STATIC_FIELD_GETTER(JavaSecuritySpecECPoint, POINT_INFINITY_, JavaSecuritySpecECPoint *)

#endif // _JavaSecuritySpecECPoint_H_
