//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/spec/ECPrivateKeySpec.java
//

#ifndef _JavaSecuritySpecECPrivateKeySpec_H_
#define _JavaSecuritySpecECPrivateKeySpec_H_

@class JavaMathBigInteger;
@class JavaSecuritySpecECParameterSpec;

#import "JreEmulation.h"
#include "java/security/spec/KeySpec.h"

@interface JavaSecuritySpecECPrivateKeySpec : NSObject < JavaSecuritySpecKeySpec > {
 @public
  JavaMathBigInteger *s_;
  JavaSecuritySpecECParameterSpec *params_;
}

- (instancetype)initWithJavaMathBigInteger:(JavaMathBigInteger *)s
       withJavaSecuritySpecECParameterSpec:(JavaSecuritySpecECParameterSpec *)params;

- (JavaSecuritySpecECParameterSpec *)getParams;

- (JavaMathBigInteger *)getS;

- (void)copyAllFieldsTo:(JavaSecuritySpecECPrivateKeySpec *)other;

@end

__attribute__((always_inline)) inline void JavaSecuritySpecECPrivateKeySpec_init() {}

J2OBJC_FIELD_SETTER(JavaSecuritySpecECPrivateKeySpec, s_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(JavaSecuritySpecECPrivateKeySpec, params_, JavaSecuritySpecECParameterSpec *)

#endif // _JavaSecuritySpecECPrivateKeySpec_H_
