//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/spec/ECPublicKeySpec.java
//

#ifndef _JavaSecuritySpecECPublicKeySpec_H_
#define _JavaSecuritySpecECPublicKeySpec_H_

@class JavaSecuritySpecECParameterSpec;
@class JavaSecuritySpecECPoint;

#import "JreEmulation.h"
#include "java/security/spec/KeySpec.h"

@interface JavaSecuritySpecECPublicKeySpec : NSObject < JavaSecuritySpecKeySpec > {
 @public
  JavaSecuritySpecECPoint *w_;
  JavaSecuritySpecECParameterSpec *params_;
}

- (instancetype)initWithJavaSecuritySpecECPoint:(JavaSecuritySpecECPoint *)w
            withJavaSecuritySpecECParameterSpec:(JavaSecuritySpecECParameterSpec *)params;

- (JavaSecuritySpecECParameterSpec *)getParams;

- (JavaSecuritySpecECPoint *)getW;

- (void)copyAllFieldsTo:(JavaSecuritySpecECPublicKeySpec *)other;

@end

__attribute__((always_inline)) inline void JavaSecuritySpecECPublicKeySpec_init() {}

J2OBJC_FIELD_SETTER(JavaSecuritySpecECPublicKeySpec, w_, JavaSecuritySpecECPoint *)
J2OBJC_FIELD_SETTER(JavaSecuritySpecECPublicKeySpec, params_, JavaSecuritySpecECParameterSpec *)

#endif // _JavaSecuritySpecECPublicKeySpec_H_
