//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/spec/EllipticCurve.java
//

#ifndef _JavaSecuritySpecEllipticCurve_H_
#define _JavaSecuritySpecEllipticCurve_H_

@class IOSByteArray;
@class JavaMathBigInteger;
@protocol JavaSecuritySpecECField;

#import "JreEmulation.h"

@interface JavaSecuritySpecEllipticCurve : NSObject {
 @public
  id<JavaSecuritySpecECField> field_;
  JavaMathBigInteger *a_;
  JavaMathBigInteger *b_;
  IOSByteArray *seed_;
  jint hash__;
}

- (instancetype)initWithJavaSecuritySpecECField:(id<JavaSecuritySpecECField>)field
                         withJavaMathBigInteger:(JavaMathBigInteger *)a
                         withJavaMathBigInteger:(JavaMathBigInteger *)b
                                  withByteArray:(IOSByteArray *)seed;

- (instancetype)initWithJavaSecuritySpecECField:(id<JavaSecuritySpecECField>)field
                         withJavaMathBigInteger:(JavaMathBigInteger *)a
                         withJavaMathBigInteger:(JavaMathBigInteger *)b;

- (JavaMathBigInteger *)getA;

- (JavaMathBigInteger *)getB;

- (id<JavaSecuritySpecECField>)getField;

- (IOSByteArray *)getSeed;

- (jboolean)isEqual:(id)other;

- (NSUInteger)hash;

- (void)copyAllFieldsTo:(JavaSecuritySpecEllipticCurve *)other;

@end

__attribute__((always_inline)) inline void JavaSecuritySpecEllipticCurve_init() {}

J2OBJC_FIELD_SETTER(JavaSecuritySpecEllipticCurve, field_, id<JavaSecuritySpecECField>)
J2OBJC_FIELD_SETTER(JavaSecuritySpecEllipticCurve, a_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(JavaSecuritySpecEllipticCurve, b_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(JavaSecuritySpecEllipticCurve, seed_, IOSByteArray *)

#endif // _JavaSecuritySpecEllipticCurve_H_
