//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/spec/EncodedKeySpec.java
//

#ifndef _JavaSecuritySpecEncodedKeySpec_H_
#define _JavaSecuritySpecEncodedKeySpec_H_

@class IOSByteArray;

#import "JreEmulation.h"
#include "java/security/spec/KeySpec.h"

@interface JavaSecuritySpecEncodedKeySpec : NSObject < JavaSecuritySpecKeySpec > {
 @public
  IOSByteArray *encodedKey_;
}

- (instancetype)initWithByteArray:(IOSByteArray *)encodedKey;

- (IOSByteArray *)getEncoded;

- (NSString *)getFormat;

- (void)copyAllFieldsTo:(JavaSecuritySpecEncodedKeySpec *)other;

@end

__attribute__((always_inline)) inline void JavaSecuritySpecEncodedKeySpec_init() {}

J2OBJC_FIELD_SETTER(JavaSecuritySpecEncodedKeySpec, encodedKey_, IOSByteArray *)

#endif // _JavaSecuritySpecEncodedKeySpec_H_
