//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/spec/KeySpec.java
//

#ifndef _JavaSecuritySpecKeySpec_H_
#define _JavaSecuritySpecKeySpec_H_

#import "JreEmulation.h"

@protocol JavaSecuritySpecKeySpec < NSObject, JavaObject >

@end

__attribute__((always_inline)) inline void JavaSecuritySpecKeySpec_init() {}

#endif // _JavaSecuritySpecKeySpec_H_
