//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/spec/PKCS8EncodedKeySpec.java
//

#ifndef _JavaSecuritySpecPKCS8EncodedKeySpec_H_
#define _JavaSecuritySpecPKCS8EncodedKeySpec_H_

@class IOSByteArray;

#import "JreEmulation.h"
#include "java/security/spec/EncodedKeySpec.h"

@interface JavaSecuritySpecPKCS8EncodedKeySpec : JavaSecuritySpecEncodedKeySpec {
}

- (instancetype)initWithByteArray:(IOSByteArray *)encodedKey;

- (IOSByteArray *)getEncoded;

- (NSString *)getFormat;

@end

__attribute__((always_inline)) inline void JavaSecuritySpecPKCS8EncodedKeySpec_init() {}

#endif // _JavaSecuritySpecPKCS8EncodedKeySpec_H_
