//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/spec/PSSParameterSpec.java
//

#ifndef _JavaSecuritySpecPSSParameterSpec_H_
#define _JavaSecuritySpecPSSParameterSpec_H_

#import "JreEmulation.h"
#include "java/security/spec/AlgorithmParameterSpec.h"

@interface JavaSecuritySpecPSSParameterSpec : NSObject < JavaSecuritySpecAlgorithmParameterSpec > {
 @public
  NSString *mdName_;
  NSString *mgfName_;
  id<JavaSecuritySpecAlgorithmParameterSpec> mgfSpec_;
  jint trailerField_;
  jint saltLen_;
}

- (instancetype)initWithInt:(jint)saltLen;

- (instancetype)initWithNSString:(NSString *)mdName
                    withNSString:(NSString *)mgfName
withJavaSecuritySpecAlgorithmParameterSpec:(id<JavaSecuritySpecAlgorithmParameterSpec>)mgfSpec
                         withInt:(jint)saltLen
                         withInt:(jint)trailerField;

- (jint)getSaltLength;

- (NSString *)getDigestAlgorithm;

- (NSString *)getMGFAlgorithm;

- (id<JavaSecuritySpecAlgorithmParameterSpec>)getMGFParameters;

- (jint)getTrailerField;

- (void)copyAllFieldsTo:(JavaSecuritySpecPSSParameterSpec *)other;

@end

FOUNDATION_EXPORT BOOL JavaSecuritySpecPSSParameterSpec_initialized;
J2OBJC_STATIC_INIT(JavaSecuritySpecPSSParameterSpec)

J2OBJC_FIELD_SETTER(JavaSecuritySpecPSSParameterSpec, mdName_, NSString *)
J2OBJC_FIELD_SETTER(JavaSecuritySpecPSSParameterSpec, mgfName_, NSString *)
J2OBJC_FIELD_SETTER(JavaSecuritySpecPSSParameterSpec, mgfSpec_, id<JavaSecuritySpecAlgorithmParameterSpec>)

FOUNDATION_EXPORT JavaSecuritySpecPSSParameterSpec *JavaSecuritySpecPSSParameterSpec_DEFAULT_;
J2OBJC_STATIC_FIELD_GETTER(JavaSecuritySpecPSSParameterSpec, DEFAULT_, JavaSecuritySpecPSSParameterSpec *)

#endif // _JavaSecuritySpecPSSParameterSpec_H_
