//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/spec/RSAKeyGenParameterSpec.java
//

#ifndef _JavaSecuritySpecRSAKeyGenParameterSpec_H_
#define _JavaSecuritySpecRSAKeyGenParameterSpec_H_

@class JavaMathBigInteger;

#import "JreEmulation.h"
#include "java/security/spec/AlgorithmParameterSpec.h"

@interface JavaSecuritySpecRSAKeyGenParameterSpec : NSObject < JavaSecuritySpecAlgorithmParameterSpec > {
 @public
  jint keysize_;
  JavaMathBigInteger *publicExponent_;
}

- (instancetype)initWithInt:(jint)keysize
     withJavaMathBigInteger:(JavaMathBigInteger *)publicExponent;

- (jint)getKeysize;

- (JavaMathBigInteger *)getPublicExponent;

- (void)copyAllFieldsTo:(JavaSecuritySpecRSAKeyGenParameterSpec *)other;

@end

FOUNDATION_EXPORT BOOL JavaSecuritySpecRSAKeyGenParameterSpec_initialized;
J2OBJC_STATIC_INIT(JavaSecuritySpecRSAKeyGenParameterSpec)

J2OBJC_FIELD_SETTER(JavaSecuritySpecRSAKeyGenParameterSpec, publicExponent_, JavaMathBigInteger *)

FOUNDATION_EXPORT JavaMathBigInteger *JavaSecuritySpecRSAKeyGenParameterSpec_F0_;
J2OBJC_STATIC_FIELD_GETTER(JavaSecuritySpecRSAKeyGenParameterSpec, F0_, JavaMathBigInteger *)

FOUNDATION_EXPORT JavaMathBigInteger *JavaSecuritySpecRSAKeyGenParameterSpec_F4_;
J2OBJC_STATIC_FIELD_GETTER(JavaSecuritySpecRSAKeyGenParameterSpec, F4_, JavaMathBigInteger *)

#endif // _JavaSecuritySpecRSAKeyGenParameterSpec_H_
