//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/spec/RSAMultiPrimePrivateCrtKeySpec.java
//

#ifndef _JavaSecuritySpecRSAMultiPrimePrivateCrtKeySpec_H_
#define _JavaSecuritySpecRSAMultiPrimePrivateCrtKeySpec_H_

@class IOSObjectArray;
@class JavaMathBigInteger;

#import "JreEmulation.h"
#include "java/security/spec/RSAPrivateKeySpec.h"

@interface JavaSecuritySpecRSAMultiPrimePrivateCrtKeySpec : JavaSecuritySpecRSAPrivateKeySpec {
 @public
  JavaMathBigInteger *publicExponent_;
  JavaMathBigInteger *primeP_;
  JavaMathBigInteger *primeQ_;
  JavaMathBigInteger *primeExponentP_;
  JavaMathBigInteger *primeExponentQ_;
  JavaMathBigInteger *crtCoefficient_;
  IOSObjectArray *otherPrimeInfo_;
}

- (instancetype)initWithJavaMathBigInteger:(JavaMathBigInteger *)modulus
                    withJavaMathBigInteger:(JavaMathBigInteger *)publicExponent
                    withJavaMathBigInteger:(JavaMathBigInteger *)privateExponent
                    withJavaMathBigInteger:(JavaMathBigInteger *)primeP
                    withJavaMathBigInteger:(JavaMathBigInteger *)primeQ
                    withJavaMathBigInteger:(JavaMathBigInteger *)primeExponentP
                    withJavaMathBigInteger:(JavaMathBigInteger *)primeExponentQ
                    withJavaMathBigInteger:(JavaMathBigInteger *)crtCoefficient
withJavaSecuritySpecRSAOtherPrimeInfoArray:(IOSObjectArray *)otherPrimeInfo;

- (JavaMathBigInteger *)getCrtCoefficient;

- (IOSObjectArray *)getOtherPrimeInfo;

- (JavaMathBigInteger *)getPrimeExponentP;

- (JavaMathBigInteger *)getPrimeExponentQ;

- (JavaMathBigInteger *)getPrimeP;

- (JavaMathBigInteger *)getPrimeQ;

- (JavaMathBigInteger *)getPublicExponent;

- (void)copyAllFieldsTo:(JavaSecuritySpecRSAMultiPrimePrivateCrtKeySpec *)other;

@end

__attribute__((always_inline)) inline void JavaSecuritySpecRSAMultiPrimePrivateCrtKeySpec_init() {}

J2OBJC_FIELD_SETTER(JavaSecuritySpecRSAMultiPrimePrivateCrtKeySpec, publicExponent_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(JavaSecuritySpecRSAMultiPrimePrivateCrtKeySpec, primeP_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(JavaSecuritySpecRSAMultiPrimePrivateCrtKeySpec, primeQ_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(JavaSecuritySpecRSAMultiPrimePrivateCrtKeySpec, primeExponentP_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(JavaSecuritySpecRSAMultiPrimePrivateCrtKeySpec, primeExponentQ_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(JavaSecuritySpecRSAMultiPrimePrivateCrtKeySpec, crtCoefficient_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(JavaSecuritySpecRSAMultiPrimePrivateCrtKeySpec, otherPrimeInfo_, IOSObjectArray *)

#endif // _JavaSecuritySpecRSAMultiPrimePrivateCrtKeySpec_H_
