//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/spec/RSAOtherPrimeInfo.java
//

#ifndef _JavaSecuritySpecRSAOtherPrimeInfo_H_
#define _JavaSecuritySpecRSAOtherPrimeInfo_H_

@class JavaMathBigInteger;

#import "JreEmulation.h"

@interface JavaSecuritySpecRSAOtherPrimeInfo : NSObject {
 @public
  JavaMathBigInteger *prime_;
  JavaMathBigInteger *primeExponent_;
  JavaMathBigInteger *crtCoefficient_;
}

- (instancetype)initWithJavaMathBigInteger:(JavaMathBigInteger *)prime
                    withJavaMathBigInteger:(JavaMathBigInteger *)primeExponent
                    withJavaMathBigInteger:(JavaMathBigInteger *)crtCoefficient;

- (JavaMathBigInteger *)getCrtCoefficient;

- (JavaMathBigInteger *)getPrime;

- (JavaMathBigInteger *)getExponent;

- (void)copyAllFieldsTo:(JavaSecuritySpecRSAOtherPrimeInfo *)other;

@end

__attribute__((always_inline)) inline void JavaSecuritySpecRSAOtherPrimeInfo_init() {}

J2OBJC_FIELD_SETTER(JavaSecuritySpecRSAOtherPrimeInfo, prime_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(JavaSecuritySpecRSAOtherPrimeInfo, primeExponent_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(JavaSecuritySpecRSAOtherPrimeInfo, crtCoefficient_, JavaMathBigInteger *)

#endif // _JavaSecuritySpecRSAOtherPrimeInfo_H_
