//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/spec/RSAPrivateCrtKeySpec.java
//

#ifndef _JavaSecuritySpecRSAPrivateCrtKeySpec_H_
#define _JavaSecuritySpecRSAPrivateCrtKeySpec_H_

@class JavaMathBigInteger;

#import "JreEmulation.h"
#include "java/security/spec/RSAPrivateKeySpec.h"

@interface JavaSecuritySpecRSAPrivateCrtKeySpec : JavaSecuritySpecRSAPrivateKeySpec {
 @public
  JavaMathBigInteger *publicExponent_;
  JavaMathBigInteger *primeP_;
  JavaMathBigInteger *primeQ_;
  JavaMathBigInteger *primeExponentP_;
  JavaMathBigInteger *primeExponentQ_;
  JavaMathBigInteger *crtCoefficient_;
}

- (instancetype)initWithJavaMathBigInteger:(JavaMathBigInteger *)modulus
                    withJavaMathBigInteger:(JavaMathBigInteger *)publicExponent
                    withJavaMathBigInteger:(JavaMathBigInteger *)privateExponent
                    withJavaMathBigInteger:(JavaMathBigInteger *)primeP
                    withJavaMathBigInteger:(JavaMathBigInteger *)primeQ
                    withJavaMathBigInteger:(JavaMathBigInteger *)primeExponentP
                    withJavaMathBigInteger:(JavaMathBigInteger *)primeExponentQ
                    withJavaMathBigInteger:(JavaMathBigInteger *)crtCoefficient;

- (JavaMathBigInteger *)getCrtCoefficient;

- (JavaMathBigInteger *)getPrimeExponentP;

- (JavaMathBigInteger *)getPrimeExponentQ;

- (JavaMathBigInteger *)getPrimeP;

- (JavaMathBigInteger *)getPrimeQ;

- (JavaMathBigInteger *)getPublicExponent;

- (void)copyAllFieldsTo:(JavaSecuritySpecRSAPrivateCrtKeySpec *)other;

@end

__attribute__((always_inline)) inline void JavaSecuritySpecRSAPrivateCrtKeySpec_init() {}

J2OBJC_FIELD_SETTER(JavaSecuritySpecRSAPrivateCrtKeySpec, publicExponent_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(JavaSecuritySpecRSAPrivateCrtKeySpec, primeP_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(JavaSecuritySpecRSAPrivateCrtKeySpec, primeQ_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(JavaSecuritySpecRSAPrivateCrtKeySpec, primeExponentP_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(JavaSecuritySpecRSAPrivateCrtKeySpec, primeExponentQ_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(JavaSecuritySpecRSAPrivateCrtKeySpec, crtCoefficient_, JavaMathBigInteger *)

#endif // _JavaSecuritySpecRSAPrivateCrtKeySpec_H_
