//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/spec/RSAPublicKeySpec.java
//

#ifndef _JavaSecuritySpecRSAPublicKeySpec_H_
#define _JavaSecuritySpecRSAPublicKeySpec_H_

@class JavaMathBigInteger;

#import "JreEmulation.h"
#include "java/security/spec/KeySpec.h"

@interface JavaSecuritySpecRSAPublicKeySpec : NSObject < JavaSecuritySpecKeySpec > {
 @public
  JavaMathBigInteger *modulus_;
  JavaMathBigInteger *publicExponent_;
}

- (instancetype)initWithJavaMathBigInteger:(JavaMathBigInteger *)modulus
                    withJavaMathBigInteger:(JavaMathBigInteger *)publicExponent;

- (JavaMathBigInteger *)getModulus;

- (JavaMathBigInteger *)getPublicExponent;

- (void)copyAllFieldsTo:(JavaSecuritySpecRSAPublicKeySpec *)other;

@end

__attribute__((always_inline)) inline void JavaSecuritySpecRSAPublicKeySpec_init() {}

J2OBJC_FIELD_SETTER(JavaSecuritySpecRSAPublicKeySpec, modulus_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(JavaSecuritySpecRSAPublicKeySpec, publicExponent_, JavaMathBigInteger *)

#endif // _JavaSecuritySpecRSAPublicKeySpec_H_
