//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/spec/RSAPrivateKeySpec.java
//

#ifndef _JavaSecuritySpecRSAPrivateKeySpec_H_
#define _JavaSecuritySpecRSAPrivateKeySpec_H_

@class JavaMathBigInteger;

#import "JreEmulation.h"
#include "java/security/spec/KeySpec.h"

@interface JavaSecuritySpecRSAPrivateKeySpec : NSObject < JavaSecuritySpecKeySpec > {
 @public
  JavaMathBigInteger *modulus_;
  JavaMathBigInteger *privateExponent_;
}

- (instancetype)initWithJavaMathBigInteger:(JavaMathBigInteger *)modulus
                    withJavaMathBigInteger:(JavaMathBigInteger *)privateExponent;

- (JavaMathBigInteger *)getModulus;

- (JavaMathBigInteger *)getPrivateExponent;

- (void)copyAllFieldsTo:(JavaSecuritySpecRSAPrivateKeySpec *)other;

@end

__attribute__((always_inline)) inline void JavaSecuritySpecRSAPrivateKeySpec_init() {}

J2OBJC_FIELD_SETTER(JavaSecuritySpecRSAPrivateKeySpec, modulus_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(JavaSecuritySpecRSAPrivateKeySpec, privateExponent_, JavaMathBigInteger *)

#endif // _JavaSecuritySpecRSAPrivateKeySpec_H_
