//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/spec/X509EncodedKeySpec.java
//

#ifndef _JavaSecuritySpecX509EncodedKeySpec_H_
#define _JavaSecuritySpecX509EncodedKeySpec_H_

@class IOSByteArray;

#import "JreEmulation.h"
#include "java/security/spec/EncodedKeySpec.h"

@interface JavaSecuritySpecX509EncodedKeySpec : JavaSecuritySpecEncodedKeySpec {
}

- (instancetype)initWithByteArray:(IOSByteArray *)encodedKey;

- (IOSByteArray *)getEncoded;

- (NSString *)getFormat;

@end

__attribute__((always_inline)) inline void JavaSecuritySpecX509EncodedKeySpec_init() {}

#endif // _JavaSecuritySpecX509EncodedKeySpec_H_
