//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/database/sqlite/SQLiteException.java
//

#ifndef _AndroidDatabaseSqliteSQLiteException_H_
#define _AndroidDatabaseSqliteSQLiteException_H_

#import "JreEmulation.h"
#include "java/lang/Exception.h"

@interface AndroidDatabaseSqliteSQLiteException : JavaLangException {
}

- (instancetype)init;

@end

__attribute__((always_inline)) inline void AndroidDatabaseSqliteSQLiteException_init() {}

#endif // _AndroidDatabaseSqliteSQLiteException_H_
