//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/database/sqlite/SQLiteOpenHelper.java
//

#ifndef _AndroidDatabaseSqliteSQLiteOpenHelper_H_
#define _AndroidDatabaseSqliteSQLiteOpenHelper_H_

@class AndroidDatabaseSqliteSQLiteDatabase;
@protocol AndroidContentContext;

#import "JreEmulation.h"

@interface AndroidDatabaseSqliteSQLiteOpenHelper : NSObject {
}

- (instancetype)initWithAndroidContentContext:(id<AndroidContentContext>)pContext
                                 withNSString:(NSString *)pDbName
                                       withId:(id)pObject
                                      withInt:(jint)pI;

- (AndroidDatabaseSqliteSQLiteDatabase *)getReadableDatabase;

- (void)onCreateWithAndroidDatabaseSqliteSQLiteDatabase:(AndroidDatabaseSqliteSQLiteDatabase *)pArg0;

- (void)onUpgradeWithAndroidDatabaseSqliteSQLiteDatabase:(AndroidDatabaseSqliteSQLiteDatabase *)pArg0
                                                 withInt:(jint)pArg1
                                                 withInt:(jint)pArg2;

@end

__attribute__((always_inline)) inline void AndroidDatabaseSqliteSQLiteOpenHelper_init() {}

#endif // _AndroidDatabaseSqliteSQLiteOpenHelper_H_
