//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/database/sqlite/SQLiteException.java
//

#ifndef _AndroidDatabaseSqliteSQLiteException_H_
#define _AndroidDatabaseSqliteSQLiteException_H_

#include "J2ObjC_header.h"
#include "java/lang/Exception.h"

@interface AndroidDatabaseSqliteSQLiteException : JavaLangException

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidDatabaseSqliteSQLiteException)

FOUNDATION_EXPORT void AndroidDatabaseSqliteSQLiteException_init(AndroidDatabaseSqliteSQLiteException *self);

FOUNDATION_EXPORT AndroidDatabaseSqliteSQLiteException *new_AndroidDatabaseSqliteSQLiteException_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(AndroidDatabaseSqliteSQLiteException)

#endif // _AndroidDatabaseSqliteSQLiteException_H_
