//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/database/sqlite/SQLiteDatabase.java
//

#ifndef _AndroidDatabaseSqliteSQLiteDatabase_H_
#define _AndroidDatabaseSqliteSQLiteDatabase_H_

#include "J2ObjC_header.h"

@protocol AndroidDatabaseCursor;

#define AndroidDatabaseSqliteSQLiteDatabase_OPEN_READONLY 1

@interface AndroidDatabaseSqliteSQLiteDatabase : NSObject

#pragma mark Public

- (instancetype)init;

- (void)close;

+ (AndroidDatabaseSqliteSQLiteDatabase *)openDatabaseWithNSString:(NSString *)path
                                                           withId:(id)factory
                                                          withInt:(jint)flags;

- (id<AndroidDatabaseCursor>)rawQueryWithNSString:(NSString *)pSqlCom
                                           withId:(id)pObject;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidDatabaseSqliteSQLiteDatabase)

J2OBJC_STATIC_FIELD_GETTER(AndroidDatabaseSqliteSQLiteDatabase, OPEN_READONLY, jint)

FOUNDATION_EXPORT AndroidDatabaseSqliteSQLiteDatabase *AndroidDatabaseSqliteSQLiteDatabase_openDatabaseWithNSString_withId_withInt_(NSString *path, id factory, jint flags);

FOUNDATION_EXPORT void AndroidDatabaseSqliteSQLiteDatabase_init(AndroidDatabaseSqliteSQLiteDatabase *self);

J2OBJC_TYPE_LITERAL_HEADER(AndroidDatabaseSqliteSQLiteDatabase)

#endif // _AndroidDatabaseSqliteSQLiteDatabase_H_
