//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/database/sqlite/SQLiteOpenHelper.java
//

#ifndef _AndroidDatabaseSqliteSQLiteOpenHelper_H_
#define _AndroidDatabaseSqliteSQLiteOpenHelper_H_

#include "J2ObjC_header.h"

@class AndroidDatabaseSqliteSQLiteDatabase;
@protocol AndroidContentContext;

@interface AndroidDatabaseSqliteSQLiteOpenHelper : NSObject

#pragma mark Public

- (instancetype)initWithAndroidContentContext:(id<AndroidContentContext>)pContext
                                 withNSString:(NSString *)pDbName
                                       withId:(id)pObject
                                      withInt:(jint)pI;

- (AndroidDatabaseSqliteSQLiteDatabase *)getReadableDatabase;

- (void)onCreateWithAndroidDatabaseSqliteSQLiteDatabase:(AndroidDatabaseSqliteSQLiteDatabase *)pArg0;

- (void)onUpgradeWithAndroidDatabaseSqliteSQLiteDatabase:(AndroidDatabaseSqliteSQLiteDatabase *)pArg0
                                                 withInt:(jint)pArg1
                                                 withInt:(jint)pArg2;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidDatabaseSqliteSQLiteOpenHelper)

FOUNDATION_EXPORT void AndroidDatabaseSqliteSQLiteOpenHelper_initWithAndroidContentContext_withNSString_withId_withInt_(AndroidDatabaseSqliteSQLiteOpenHelper *self, id<AndroidContentContext> pContext, NSString *pDbName, id pObject, jint pI);

FOUNDATION_EXPORT AndroidDatabaseSqliteSQLiteOpenHelper *new_AndroidDatabaseSqliteSQLiteOpenHelper_initWithAndroidContentContext_withNSString_withId_withInt_(id<AndroidContentContext> pContext, NSString *pDbName, id pObject, jint pI) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(AndroidDatabaseSqliteSQLiteOpenHelper)

#endif // _AndroidDatabaseSqliteSQLiteOpenHelper_H_
