//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/apache/harmony/xml/dom/AttrImpl.java
//

#ifndef _OrgApacheHarmonyXmlDomAttrImpl_H_
#define _OrgApacheHarmonyXmlDomAttrImpl_H_

@class OrgApacheHarmonyXmlDomDocumentImpl;
@class OrgApacheHarmonyXmlDomElementImpl;
@protocol OrgW3cDomElement;
@protocol OrgW3cDomTypeInfo;

#import "JreEmulation.h"
#include "org/apache/harmony/xml/dom/NodeImpl.h"
#include "org/w3c/dom/Attr.h"

@interface OrgApacheHarmonyXmlDomAttrImpl : OrgApacheHarmonyXmlDomNodeImpl < OrgW3cDomAttr > {
 @public
  OrgApacheHarmonyXmlDomElementImpl *ownerElement_;
  jboolean isId__;
  jboolean namespaceAware_;
  NSString *namespaceURI_;
  NSString *prefix_;
  NSString *localName_;
  NSString *value_;
}

- (instancetype)initWithOrgApacheHarmonyXmlDomDocumentImpl:(OrgApacheHarmonyXmlDomDocumentImpl *)document
                                              withNSString:(NSString *)namespaceURI
                                              withNSString:(NSString *)qualifiedName;

- (instancetype)initWithOrgApacheHarmonyXmlDomDocumentImpl:(OrgApacheHarmonyXmlDomDocumentImpl *)document
                                              withNSString:(NSString *)name;

- (NSString *)getLocalName;

- (NSString *)getName;

- (NSString *)getNamespaceURI;

- (NSString *)getNodeName;

- (jshort)getNodeType;

- (NSString *)getNodeValue;

- (id<OrgW3cDomElement>)getOwnerElement;

- (NSString *)getPrefix;

- (jboolean)getSpecified;

- (NSString *)getValue;

- (void)setPrefixWithNSString:(NSString *)prefix;

- (void)setValueWithNSString:(NSString *)value;

- (id<OrgW3cDomTypeInfo>)getSchemaTypeInfo;

- (jboolean)isId;

- (void)copyAllFieldsTo:(OrgApacheHarmonyXmlDomAttrImpl *)other;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlDomAttrImpl_init() {}

J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomAttrImpl, ownerElement_, OrgApacheHarmonyXmlDomElementImpl *)
J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomAttrImpl, namespaceURI_, NSString *)
J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomAttrImpl, prefix_, NSString *)
J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomAttrImpl, localName_, NSString *)
J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomAttrImpl, value_, NSString *)

#endif // _OrgApacheHarmonyXmlDomAttrImpl_H_
