//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/apache/harmony/xml/dom/CharacterDataImpl.java
//

#ifndef _OrgApacheHarmonyXmlDomCharacterDataImpl_H_
#define _OrgApacheHarmonyXmlDomCharacterDataImpl_H_

@class JavaLangStringBuffer;
@class JavaLangStringBuilder;
@class OrgApacheHarmonyXmlDomDocumentImpl;

#import "JreEmulation.h"
#include "org/apache/harmony/xml/dom/LeafNodeImpl.h"
#include "org/w3c/dom/CharacterData.h"

@interface OrgApacheHarmonyXmlDomCharacterDataImpl : OrgApacheHarmonyXmlDomLeafNodeImpl < OrgW3cDomCharacterData > {
 @public
  JavaLangStringBuffer *buffer_;
}

- (instancetype)initWithOrgApacheHarmonyXmlDomDocumentImpl:(OrgApacheHarmonyXmlDomDocumentImpl *)document
                                              withNSString:(NSString *)data;

- (void)appendDataWithNSString:(NSString *)arg;

- (void)deleteDataWithInt:(jint)offset
                  withInt:(jint)count;

- (NSString *)getData;

- (void)appendDataToWithJavaLangStringBuilder:(JavaLangStringBuilder *)stringBuilder;

- (jint)getLength;

- (NSString *)getNodeValue;

- (void)insertDataWithInt:(jint)offset
             withNSString:(NSString *)arg;

- (void)replaceDataWithInt:(jint)offset
                   withInt:(jint)count
              withNSString:(NSString *)arg;

- (void)setDataWithNSString:(NSString *)data;

- (NSString *)substringDataWithInt:(jint)offset
                           withInt:(jint)count;

- (void)copyAllFieldsTo:(OrgApacheHarmonyXmlDomCharacterDataImpl *)other;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlDomCharacterDataImpl_init() {}

J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomCharacterDataImpl, buffer_, JavaLangStringBuffer *)

#endif // _OrgApacheHarmonyXmlDomCharacterDataImpl_H_
