//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/apache/harmony/xml/dom/CommentImpl.java
//

#ifndef _OrgApacheHarmonyXmlDomCommentImpl_H_
#define _OrgApacheHarmonyXmlDomCommentImpl_H_

@class OrgApacheHarmonyXmlDomDocumentImpl;

#import "JreEmulation.h"
#include "org/apache/harmony/xml/dom/CharacterDataImpl.h"
#include "org/w3c/dom/Comment.h"

@interface OrgApacheHarmonyXmlDomCommentImpl : OrgApacheHarmonyXmlDomCharacterDataImpl < OrgW3cDomComment > {
}

- (instancetype)initWithOrgApacheHarmonyXmlDomDocumentImpl:(OrgApacheHarmonyXmlDomDocumentImpl *)document
                                              withNSString:(NSString *)data;

- (NSString *)getNodeName;

- (jshort)getNodeType;

- (jboolean)containsDashDash;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlDomCommentImpl_init() {}

#endif // _OrgApacheHarmonyXmlDomCommentImpl_H_
