//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/apache/harmony/xml/dom/DocumentTypeImpl.java
//

#ifndef _OrgApacheHarmonyXmlDomDocumentTypeImpl_H_
#define _OrgApacheHarmonyXmlDomDocumentTypeImpl_H_

@class OrgApacheHarmonyXmlDomDocumentImpl;
@protocol OrgW3cDomNamedNodeMap;

#import "JreEmulation.h"
#include "org/apache/harmony/xml/dom/LeafNodeImpl.h"
#include "org/w3c/dom/DocumentType.h"

@interface OrgApacheHarmonyXmlDomDocumentTypeImpl : OrgApacheHarmonyXmlDomLeafNodeImpl < OrgW3cDomDocumentType > {
 @public
  NSString *qualifiedName_;
  NSString *publicId_;
  NSString *systemId_;
}

- (instancetype)initWithOrgApacheHarmonyXmlDomDocumentImpl:(OrgApacheHarmonyXmlDomDocumentImpl *)document
                                              withNSString:(NSString *)qualifiedName
                                              withNSString:(NSString *)publicId
                                              withNSString:(NSString *)systemId;

- (NSString *)getNodeName;

- (jshort)getNodeType;

- (id<OrgW3cDomNamedNodeMap>)getEntities;

- (NSString *)getInternalSubset;

- (NSString *)getName;

- (id<OrgW3cDomNamedNodeMap>)getNotations;

- (NSString *)getPublicId;

- (NSString *)getSystemId;

- (NSString *)getTextContent;

- (void)copyAllFieldsTo:(OrgApacheHarmonyXmlDomDocumentTypeImpl *)other;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlDomDocumentTypeImpl_init() {}

J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomDocumentTypeImpl, qualifiedName_, NSString *)
J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomDocumentTypeImpl, publicId_, NSString *)
J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomDocumentTypeImpl, systemId_, NSString *)

#endif // _OrgApacheHarmonyXmlDomDocumentTypeImpl_H_
