//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/apache/harmony/xml/dom/DocumentFragmentImpl.java
//

#ifndef _OrgApacheHarmonyXmlDomDocumentFragmentImpl_H_
#define _OrgApacheHarmonyXmlDomDocumentFragmentImpl_H_

@class OrgApacheHarmonyXmlDomDocumentImpl;

#import "JreEmulation.h"
#include "org/apache/harmony/xml/dom/InnerNodeImpl.h"
#include "org/w3c/dom/DocumentFragment.h"

@interface OrgApacheHarmonyXmlDomDocumentFragmentImpl : OrgApacheHarmonyXmlDomInnerNodeImpl < OrgW3cDomDocumentFragment > {
}

- (instancetype)initWithOrgApacheHarmonyXmlDomDocumentImpl:(OrgApacheHarmonyXmlDomDocumentImpl *)document;

- (NSString *)getNodeName;

- (jshort)getNodeType;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlDomDocumentFragmentImpl_init() {}

#endif // _OrgApacheHarmonyXmlDomDocumentFragmentImpl_H_
