//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/apache/harmony/xml/dom/DocumentImpl.java
//

#ifndef _OrgApacheHarmonyXmlDomDocumentImpl_H_
#define _OrgApacheHarmonyXmlDomDocumentImpl_H_

@class JavaUtilWeakHashMap;
@class OrgApacheHarmonyXmlDomAttrImpl;
@class OrgApacheHarmonyXmlDomCDATASectionImpl;
@class OrgApacheHarmonyXmlDomCommentImpl;
@class OrgApacheHarmonyXmlDomDOMConfigurationImpl;
@class OrgApacheHarmonyXmlDomDOMImplementationImpl;
@class OrgApacheHarmonyXmlDomDocumentFragmentImpl;
@class OrgApacheHarmonyXmlDomElementImpl;
@class OrgApacheHarmonyXmlDomEntityReferenceImpl;
@class OrgApacheHarmonyXmlDomNodeImpl;
@class OrgApacheHarmonyXmlDomProcessingInstructionImpl;
@class OrgApacheHarmonyXmlDomTextImpl;
@protocol JavaUtilMap;
@protocol OrgW3cDomDOMConfiguration;
@protocol OrgW3cDomDOMImplementation;
@protocol OrgW3cDomDocumentType;
@protocol OrgW3cDomElement;
@protocol OrgW3cDomNode;
@protocol OrgW3cDomNodeList;

#import "JreEmulation.h"
#include "org/apache/harmony/xml/dom/InnerNodeImpl.h"
#include "org/w3c/dom/Document.h"

@interface OrgApacheHarmonyXmlDomDocumentImpl : OrgApacheHarmonyXmlDomInnerNodeImpl < OrgW3cDomDocument > {
 @public
  id<OrgW3cDomDOMImplementation> domImplementation_;
  OrgApacheHarmonyXmlDomDOMConfigurationImpl *domConfiguration_;
  NSString *documentUri_;
  NSString *inputEncoding_;
  NSString *xmlEncoding_;
  NSString *xmlVersion_;
  jboolean xmlStandalone_;
  jboolean strictErrorChecking_;
  JavaUtilWeakHashMap *nodeToUserData_;
}

- (instancetype)initWithOrgApacheHarmonyXmlDomDOMImplementationImpl:(OrgApacheHarmonyXmlDomDOMImplementationImpl *)impl
                                                       withNSString:(NSString *)namespaceURI
                                                       withNSString:(NSString *)qualifiedName
                                          withOrgW3cDomDocumentType:(id<OrgW3cDomDocumentType>)doctype
                                                       withNSString:(NSString *)inputEncoding;

+ (jboolean)isXMLIdentifierStartWithChar:(jchar)c;

+ (jboolean)isXMLIdentifierPartWithChar:(jchar)c;

+ (jboolean)isXMLIdentifierWithNSString:(NSString *)s;

- (OrgApacheHarmonyXmlDomNodeImpl *)shallowCopyWithShort:(jshort)operation
                                       withOrgW3cDomNode:(id<OrgW3cDomNode>)node;

- (id<OrgW3cDomNode>)cloneOrImportNodeWithShort:(jshort)operation
                              withOrgW3cDomNode:(id<OrgW3cDomNode>)node
                                    withBoolean:(jboolean)deep;

- (id<OrgW3cDomNode>)importNodeWithOrgW3cDomNode:(id<OrgW3cDomNode>)importedNode
                                     withBoolean:(jboolean)deep;

- (id<OrgW3cDomNode>)adoptNodeWithOrgW3cDomNode:(id<OrgW3cDomNode>)node;

- (void)changeDocumentToThisWithOrgApacheHarmonyXmlDomNodeImpl:(OrgApacheHarmonyXmlDomNodeImpl *)node;

- (id<OrgW3cDomNode>)renameNodeWithOrgW3cDomNode:(id<OrgW3cDomNode>)node
                                    withNSString:(NSString *)namespaceURI
                                    withNSString:(NSString *)qualifiedName;

- (OrgApacheHarmonyXmlDomAttrImpl *)createAttributeWithNSString:(NSString *)name;

- (OrgApacheHarmonyXmlDomAttrImpl *)createAttributeNSWithNSString:(NSString *)namespaceURI
                                                     withNSString:(NSString *)qualifiedName;

- (OrgApacheHarmonyXmlDomCDATASectionImpl *)createCDATASectionWithNSString:(NSString *)data;

- (OrgApacheHarmonyXmlDomCommentImpl *)createCommentWithNSString:(NSString *)data;

- (OrgApacheHarmonyXmlDomDocumentFragmentImpl *)createDocumentFragment;

- (OrgApacheHarmonyXmlDomElementImpl *)createElementWithNSString:(NSString *)tagName;

- (OrgApacheHarmonyXmlDomElementImpl *)createElementNSWithNSString:(NSString *)namespaceURI
                                                      withNSString:(NSString *)qualifiedName;

- (OrgApacheHarmonyXmlDomEntityReferenceImpl *)createEntityReferenceWithNSString:(NSString *)name;

- (OrgApacheHarmonyXmlDomProcessingInstructionImpl *)createProcessingInstructionWithNSString:(NSString *)target
                                                                                withNSString:(NSString *)data;

- (OrgApacheHarmonyXmlDomTextImpl *)createTextNodeWithNSString:(NSString *)data;

- (id<OrgW3cDomDocumentType>)getDoctype;

- (id<OrgW3cDomElement>)getDocumentElement;

- (id<OrgW3cDomElement>)getElementByIdWithNSString:(NSString *)elementId;

- (id<OrgW3cDomNodeList>)getElementsByTagNameWithNSString:(NSString *)name;

- (id<OrgW3cDomNodeList>)getElementsByTagNameNSWithNSString:(NSString *)namespaceURI
                                               withNSString:(NSString *)localName;

- (id<OrgW3cDomDOMImplementation>)getImplementation;

- (NSString *)getNodeName;

- (jshort)getNodeType;

- (id<OrgW3cDomNode>)insertChildAtWithOrgW3cDomNode:(id<OrgW3cDomNode>)toInsert
                                            withInt:(jint)index;

- (NSString *)getTextContent;

- (NSString *)getInputEncoding;

- (NSString *)getXmlEncoding;

- (jboolean)getXmlStandalone;

- (void)setXmlStandaloneWithBoolean:(jboolean)xmlStandalone;

- (NSString *)getXmlVersion;

- (void)setXmlVersionWithNSString:(NSString *)xmlVersion;

- (jboolean)getStrictErrorChecking;

- (void)setStrictErrorCheckingWithBoolean:(jboolean)strictErrorChecking;

- (NSString *)getDocumentURI;

- (void)setDocumentURIWithNSString:(NSString *)documentUri;

- (id<OrgW3cDomDOMConfiguration>)getDomConfig;

- (void)normalizeDocument;

- (id<JavaUtilMap>)getUserDataMapWithOrgApacheHarmonyXmlDomNodeImpl:(OrgApacheHarmonyXmlDomNodeImpl *)node;

- (id<JavaUtilMap>)getUserDataMapForReadWithOrgApacheHarmonyXmlDomNodeImpl:(OrgApacheHarmonyXmlDomNodeImpl *)node;

+ (void)notifyUserDataHandlersWithShort:(jshort)operation
                      withOrgW3cDomNode:(id<OrgW3cDomNode>)source
     withOrgApacheHarmonyXmlDomNodeImpl:(OrgApacheHarmonyXmlDomNodeImpl *)destination;

- (void)copyAllFieldsTo:(OrgApacheHarmonyXmlDomDocumentImpl *)other;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlDomDocumentImpl_init() {}

J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomDocumentImpl, domImplementation_, id<OrgW3cDomDOMImplementation>)
J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomDocumentImpl, domConfiguration_, OrgApacheHarmonyXmlDomDOMConfigurationImpl *)
J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomDocumentImpl, documentUri_, NSString *)
J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomDocumentImpl, inputEncoding_, NSString *)
J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomDocumentImpl, xmlEncoding_, NSString *)
J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomDocumentImpl, xmlVersion_, NSString *)
J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomDocumentImpl, nodeToUserData_, JavaUtilWeakHashMap *)

#endif // _OrgApacheHarmonyXmlDomDocumentImpl_H_
