//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/apache/harmony/xml/dom/DOMConfigurationImpl.java
//

#ifndef _OrgApacheHarmonyXmlDomDOMConfigurationImpl_H_
#define _OrgApacheHarmonyXmlDomDOMConfigurationImpl_H_

@class IOSObjectArray;
@protocol JavaLangCharSequence;
@protocol JavaUtilMap;
@protocol OrgW3cDomDOMErrorHandler;
@protocol OrgW3cDomNode;

#import "JreEmulation.h"
#include "org/w3c/dom/DOMConfiguration.h"
#include "org/w3c/dom/DOMStringList.h"

@interface OrgApacheHarmonyXmlDomDOMConfigurationImpl : NSObject < OrgW3cDomDOMConfiguration > {
 @public
  jboolean cdataSections_;
  jboolean comments_;
  jboolean datatypeNormalization_;
  jboolean entities_;
  id<OrgW3cDomDOMErrorHandler> errorHandler_;
  jboolean namespaces_;
  NSString *schemaLocation_;
  NSString *schemaType_;
  jboolean splitCdataSections_;
  jboolean validate_;
  jboolean wellFormed_;
}

- (jboolean)canSetParameterWithNSString:(NSString *)name
                                 withId:(id)value;

- (void)setParameterWithNSString:(NSString *)name
                          withId:(id)value;

- (id)getParameterWithNSString:(NSString *)name;

- (id<OrgW3cDomDOMStringList>)getParameterNames;

- (void)normalizeWithOrgW3cDomNode:(id<OrgW3cDomNode>)node;

- (void)checkTextValidityWithJavaLangCharSequence:(id<JavaLangCharSequence>)s;

- (jboolean)isValidWithJavaLangCharSequence:(id<JavaLangCharSequence>)text;

- (void)reportWithShort:(jshort)severity
           withNSString:(NSString *)type;

- (instancetype)init;

- (void)copyAllFieldsTo:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)other;

@end

FOUNDATION_EXPORT BOOL OrgApacheHarmonyXmlDomDOMConfigurationImpl_initialized;
J2OBJC_STATIC_INIT(OrgApacheHarmonyXmlDomDOMConfigurationImpl)

J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomDOMConfigurationImpl, errorHandler_, id<OrgW3cDomDOMErrorHandler>)
J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomDOMConfigurationImpl, schemaLocation_, NSString *)
J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomDOMConfigurationImpl, schemaType_, NSString *)

FOUNDATION_EXPORT id<JavaUtilMap> OrgApacheHarmonyXmlDomDOMConfigurationImpl_PARAMETERS_;
J2OBJC_STATIC_FIELD_GETTER(OrgApacheHarmonyXmlDomDOMConfigurationImpl, PARAMETERS_, id<JavaUtilMap>)

@protocol OrgApacheHarmonyXmlDomDOMConfigurationImpl_Parameter < NSObject, JavaObject >

- (id)getWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config;

- (void)setWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config
                                                   withId:(id)value;

- (jboolean)canSetWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config
                                                          withId:(id)value;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlDomDOMConfigurationImpl_Parameter_init() {}

@interface OrgApacheHarmonyXmlDomDOMConfigurationImpl_FixedParameter : NSObject < OrgApacheHarmonyXmlDomDOMConfigurationImpl_Parameter > {
 @public
  id onlyValue_;
}

- (instancetype)initWithId:(id)onlyValue;

- (id)getWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config;

- (void)setWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config
                                                   withId:(id)value;

- (jboolean)canSetWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config
                                                          withId:(id)value;

- (void)copyAllFieldsTo:(OrgApacheHarmonyXmlDomDOMConfigurationImpl_FixedParameter *)other;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlDomDOMConfigurationImpl_FixedParameter_init() {}

J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomDOMConfigurationImpl_FixedParameter, onlyValue_, id)

@interface OrgApacheHarmonyXmlDomDOMConfigurationImpl_BooleanParameter : NSObject < OrgApacheHarmonyXmlDomDOMConfigurationImpl_Parameter > {
}

- (jboolean)canSetWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config
                                                          withId:(id)value;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlDomDOMConfigurationImpl_BooleanParameter_init() {}

@interface OrgApacheHarmonyXmlDomDOMConfigurationImpl_$1 : OrgApacheHarmonyXmlDomDOMConfigurationImpl_BooleanParameter {
}

- (id)getWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config;

- (void)setWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config
                                                   withId:(id)value;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlDomDOMConfigurationImpl_$1_init() {}

@interface OrgApacheHarmonyXmlDomDOMConfigurationImpl_$2 : OrgApacheHarmonyXmlDomDOMConfigurationImpl_BooleanParameter {
}

- (id)getWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config;

- (void)setWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config
                                                   withId:(id)value;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlDomDOMConfigurationImpl_$2_init() {}

@interface OrgApacheHarmonyXmlDomDOMConfigurationImpl_$3 : OrgApacheHarmonyXmlDomDOMConfigurationImpl_BooleanParameter {
}

- (id)getWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config;

- (void)setWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config
                                                   withId:(id)value;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlDomDOMConfigurationImpl_$3_init() {}

@interface OrgApacheHarmonyXmlDomDOMConfigurationImpl_$4 : OrgApacheHarmonyXmlDomDOMConfigurationImpl_BooleanParameter {
}

- (id)getWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config;

- (void)setWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config
                                                   withId:(id)value;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlDomDOMConfigurationImpl_$4_init() {}

@interface OrgApacheHarmonyXmlDomDOMConfigurationImpl_$5 : NSObject < OrgApacheHarmonyXmlDomDOMConfigurationImpl_Parameter > {
}

- (id)getWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config;

- (void)setWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config
                                                   withId:(id)value;

- (jboolean)canSetWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config
                                                          withId:(id)value;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlDomDOMConfigurationImpl_$5_init() {}

@interface OrgApacheHarmonyXmlDomDOMConfigurationImpl_$6 : OrgApacheHarmonyXmlDomDOMConfigurationImpl_BooleanParameter {
}

- (id)getWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config;

- (void)setWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config
                                                   withId:(id)value;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlDomDOMConfigurationImpl_$6_init() {}

@interface OrgApacheHarmonyXmlDomDOMConfigurationImpl_$7 : OrgApacheHarmonyXmlDomDOMConfigurationImpl_BooleanParameter {
}

- (id)getWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config;

- (void)setWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config
                                                   withId:(id)value;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlDomDOMConfigurationImpl_$7_init() {}

@interface OrgApacheHarmonyXmlDomDOMConfigurationImpl_$8 : NSObject < OrgApacheHarmonyXmlDomDOMConfigurationImpl_Parameter > {
}

- (id)getWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config;

- (void)setWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config
                                                   withId:(id)value;

- (jboolean)canSetWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config
                                                          withId:(id)value;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlDomDOMConfigurationImpl_$8_init() {}

@interface OrgApacheHarmonyXmlDomDOMConfigurationImpl_$9 : NSObject < OrgApacheHarmonyXmlDomDOMConfigurationImpl_Parameter > {
}

- (id)getWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config;

- (void)setWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config
                                                   withId:(id)value;

- (jboolean)canSetWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config
                                                          withId:(id)value;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlDomDOMConfigurationImpl_$9_init() {}

@interface OrgApacheHarmonyXmlDomDOMConfigurationImpl_$10 : OrgApacheHarmonyXmlDomDOMConfigurationImpl_BooleanParameter {
}

- (id)getWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config;

- (void)setWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config
                                                   withId:(id)value;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlDomDOMConfigurationImpl_$10_init() {}

@interface OrgApacheHarmonyXmlDomDOMConfigurationImpl_$11 : OrgApacheHarmonyXmlDomDOMConfigurationImpl_BooleanParameter {
}

- (id)getWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config;

- (void)setWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config
                                                   withId:(id)value;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlDomDOMConfigurationImpl_$11_init() {}

@interface OrgApacheHarmonyXmlDomDOMConfigurationImpl_$12 : OrgApacheHarmonyXmlDomDOMConfigurationImpl_BooleanParameter {
}

- (id)getWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config;

- (void)setWithOrgApacheHarmonyXmlDomDOMConfigurationImpl:(OrgApacheHarmonyXmlDomDOMConfigurationImpl *)config
                                                   withId:(id)value;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlDomDOMConfigurationImpl_$12_init() {}

@interface OrgApacheHarmonyXmlDomDOMConfigurationImpl_$13 : NSObject < OrgW3cDomDOMStringList > {
 @public
  IOSObjectArray *val$result_;
}

- (NSString *)itemWithInt:(jint)index;

- (jint)getLength;

- (jboolean)containsWithNSString:(NSString *)str;

- (instancetype)initWithNSStringArray:(IOSObjectArray *)capture$0;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlDomDOMConfigurationImpl_$13_init() {}

J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomDOMConfigurationImpl_$13, val$result_, IOSObjectArray *)

#endif // _OrgApacheHarmonyXmlDomDOMConfigurationImpl_H_
