//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/apache/harmony/xml/dom/DOMErrorImpl.java
//

#ifndef _OrgApacheHarmonyXmlDomDOMErrorImpl_H_
#define _OrgApacheHarmonyXmlDomDOMErrorImpl_H_

@protocol OrgW3cDomNode;

#import "JreEmulation.h"
#include "org/w3c/dom/DOMError.h"
#include "org/w3c/dom/DOMLocator.h"

@interface OrgApacheHarmonyXmlDomDOMErrorImpl : NSObject < OrgW3cDomDOMError > {
 @public
  jshort severity_;
  NSString *type_;
}

- (instancetype)initWithShort:(jshort)severity
                 withNSString:(NSString *)type;

- (jshort)getSeverity;

- (NSString *)getMessage;

- (NSString *)getType;

- (id)getRelatedException;

- (id)getRelatedData;

- (id<OrgW3cDomDOMLocator>)getLocation;

- (void)copyAllFieldsTo:(OrgApacheHarmonyXmlDomDOMErrorImpl *)other;

@end

FOUNDATION_EXPORT BOOL OrgApacheHarmonyXmlDomDOMErrorImpl_initialized;
J2OBJC_STATIC_INIT(OrgApacheHarmonyXmlDomDOMErrorImpl)

J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomDOMErrorImpl, type_, NSString *)

FOUNDATION_EXPORT id<OrgW3cDomDOMLocator> OrgApacheHarmonyXmlDomDOMErrorImpl_NULL_DOM_LOCATOR_;
J2OBJC_STATIC_FIELD_GETTER(OrgApacheHarmonyXmlDomDOMErrorImpl, NULL_DOM_LOCATOR_, id<OrgW3cDomDOMLocator>)

@interface OrgApacheHarmonyXmlDomDOMErrorImpl_$1 : NSObject < OrgW3cDomDOMLocator > {
}

- (jint)getLineNumber;

- (jint)getColumnNumber;

- (jint)getByteOffset;

- (jint)getUtf16Offset;

- (id<OrgW3cDomNode>)getRelatedNode;

- (NSString *)getUri;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlDomDOMErrorImpl_$1_init() {}

#endif // _OrgApacheHarmonyXmlDomDOMErrorImpl_H_
