//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/apache/harmony/xml/dom/DOMImplementationImpl.java
//

#ifndef _OrgApacheHarmonyXmlDomDOMImplementationImpl_H_
#define _OrgApacheHarmonyXmlDomDOMImplementationImpl_H_

@protocol OrgW3cDomDocument;
@protocol OrgW3cDomDocumentType;

#import "JreEmulation.h"
#include "org/w3c/dom/DOMImplementation.h"

@interface OrgApacheHarmonyXmlDomDOMImplementationImpl : NSObject < OrgW3cDomDOMImplementation > {
}

- (instancetype)init;

- (id<OrgW3cDomDocument>)createDocumentWithNSString:(NSString *)namespaceURI
                                       withNSString:(NSString *)qualifiedName
                          withOrgW3cDomDocumentType:(id<OrgW3cDomDocumentType>)doctype;

- (id<OrgW3cDomDocumentType>)createDocumentTypeWithNSString:(NSString *)qualifiedName
                                               withNSString:(NSString *)publicId
                                               withNSString:(NSString *)systemId;

- (jboolean)hasFeatureWithNSString:(NSString *)feature
                      withNSString:(NSString *)version_;

+ (OrgApacheHarmonyXmlDomDOMImplementationImpl *)getInstance;

- (id)getFeatureWithNSString:(NSString *)feature
                withNSString:(NSString *)version_;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlDomDOMImplementationImpl_init() {}

FOUNDATION_EXPORT OrgApacheHarmonyXmlDomDOMImplementationImpl *OrgApacheHarmonyXmlDomDOMImplementationImpl_instance_;
J2OBJC_STATIC_FIELD_GETTER(OrgApacheHarmonyXmlDomDOMImplementationImpl, instance_, OrgApacheHarmonyXmlDomDOMImplementationImpl *)
J2OBJC_STATIC_FIELD_SETTER(OrgApacheHarmonyXmlDomDOMImplementationImpl, instance_, OrgApacheHarmonyXmlDomDOMImplementationImpl *)

#endif // _OrgApacheHarmonyXmlDomDOMImplementationImpl_H_
