//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/apache/harmony/xml/dom/ElementImpl.java
//

#ifndef _OrgApacheHarmonyXmlDomElementImpl_H_
#define _OrgApacheHarmonyXmlDomElementImpl_H_

@class OrgApacheHarmonyXmlDomAttrImpl;
@class OrgApacheHarmonyXmlDomDocumentImpl;
@protocol JavaUtilList;
@protocol OrgW3cDomAttr;
@protocol OrgW3cDomNode;
@protocol OrgW3cDomNodeList;
@protocol OrgW3cDomTypeInfo;

#import "JreEmulation.h"
#include "org/apache/harmony/xml/dom/InnerNodeImpl.h"
#include "org/w3c/dom/Element.h"
#include "org/w3c/dom/NamedNodeMap.h"

@interface OrgApacheHarmonyXmlDomElementImpl : OrgApacheHarmonyXmlDomInnerNodeImpl < OrgW3cDomElement > {
 @public
  jboolean namespaceAware_;
  NSString *namespaceURI_;
  NSString *prefix_;
  NSString *localName_;
  id<JavaUtilList> attributes_;
}

- (instancetype)initWithOrgApacheHarmonyXmlDomDocumentImpl:(OrgApacheHarmonyXmlDomDocumentImpl *)document
                                              withNSString:(NSString *)namespaceURI
                                              withNSString:(NSString *)qualifiedName;

- (instancetype)initWithOrgApacheHarmonyXmlDomDocumentImpl:(OrgApacheHarmonyXmlDomDocumentImpl *)document
                                              withNSString:(NSString *)name;

- (jint)indexOfAttributeWithNSString:(NSString *)name;

- (jint)indexOfAttributeNSWithNSString:(NSString *)namespaceURI
                          withNSString:(NSString *)localName;

- (NSString *)getAttributeWithNSString:(NSString *)name;

- (NSString *)getAttributeNSWithNSString:(NSString *)namespaceURI
                            withNSString:(NSString *)localName;

- (OrgApacheHarmonyXmlDomAttrImpl *)getAttributeNodeWithNSString:(NSString *)name;

- (OrgApacheHarmonyXmlDomAttrImpl *)getAttributeNodeNSWithNSString:(NSString *)namespaceURI
                                                      withNSString:(NSString *)localName;

- (id<OrgW3cDomNamedNodeMap>)getAttributes;

- (id<OrgW3cDomElement>)getElementByIdWithNSString:(NSString *)name;

- (id<OrgW3cDomNodeList>)getElementsByTagNameWithNSString:(NSString *)name;

- (id<OrgW3cDomNodeList>)getElementsByTagNameNSWithNSString:(NSString *)namespaceURI
                                               withNSString:(NSString *)localName;

- (NSString *)getLocalName;

- (NSString *)getNamespaceURI;

- (NSString *)getNodeName;

- (jshort)getNodeType;

- (NSString *)getPrefix;

- (NSString *)getTagName;

- (jboolean)hasAttributeWithNSString:(NSString *)name;

- (jboolean)hasAttributeNSWithNSString:(NSString *)namespaceURI
                          withNSString:(NSString *)localName;

- (jboolean)hasAttributes;

- (void)removeAttributeWithNSString:(NSString *)name;

- (void)removeAttributeNSWithNSString:(NSString *)namespaceURI
                         withNSString:(NSString *)localName;

- (id<OrgW3cDomAttr>)removeAttributeNodeWithOrgW3cDomAttr:(id<OrgW3cDomAttr>)oldAttr;

- (void)setAttributeWithNSString:(NSString *)name
                    withNSString:(NSString *)value;

- (void)setAttributeNSWithNSString:(NSString *)namespaceURI
                      withNSString:(NSString *)qualifiedName
                      withNSString:(NSString *)value;

- (id<OrgW3cDomAttr>)setAttributeNodeWithOrgW3cDomAttr:(id<OrgW3cDomAttr>)newAttr;

- (id<OrgW3cDomAttr>)setAttributeNodeNSWithOrgW3cDomAttr:(id<OrgW3cDomAttr>)newAttr;

- (void)setPrefixWithNSString:(NSString *)prefix;

- (id<OrgW3cDomTypeInfo>)getSchemaTypeInfo;

- (void)setIdAttributeWithNSString:(NSString *)name
                       withBoolean:(jboolean)isId;

- (void)setIdAttributeNSWithNSString:(NSString *)namespaceURI
                        withNSString:(NSString *)localName
                         withBoolean:(jboolean)isId;

- (void)setIdAttributeNodeWithOrgW3cDomAttr:(id<OrgW3cDomAttr>)idAttr
                                withBoolean:(jboolean)isId;

- (void)copyAllFieldsTo:(OrgApacheHarmonyXmlDomElementImpl *)other;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlDomElementImpl_init() {}

J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomElementImpl, namespaceURI_, NSString *)
J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomElementImpl, prefix_, NSString *)
J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomElementImpl, localName_, NSString *)
J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomElementImpl, attributes_, id<JavaUtilList>)

@interface OrgApacheHarmonyXmlDomElementImpl_ElementAttrNamedNodeMapImpl : NSObject < OrgW3cDomNamedNodeMap > {
 @public
  OrgApacheHarmonyXmlDomElementImpl *this$0_;
}

- (jint)getLength;

- (jint)indexOfItemWithNSString:(NSString *)name;

- (jint)indexOfItemNSWithNSString:(NSString *)namespaceURI
                     withNSString:(NSString *)localName;

- (id<OrgW3cDomNode>)getNamedItemWithNSString:(NSString *)name;

- (id<OrgW3cDomNode>)getNamedItemNSWithNSString:(NSString *)namespaceURI
                                   withNSString:(NSString *)localName;

- (id<OrgW3cDomNode>)itemWithInt:(jint)index;

- (id<OrgW3cDomNode>)removeNamedItemWithNSString:(NSString *)name;

- (id<OrgW3cDomNode>)removeNamedItemNSWithNSString:(NSString *)namespaceURI
                                      withNSString:(NSString *)localName;

- (id<OrgW3cDomNode>)setNamedItemWithOrgW3cDomNode:(id<OrgW3cDomNode>)arg;

- (id<OrgW3cDomNode>)setNamedItemNSWithOrgW3cDomNode:(id<OrgW3cDomNode>)arg;

- (instancetype)initWithOrgApacheHarmonyXmlDomElementImpl:(OrgApacheHarmonyXmlDomElementImpl *)outer$;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlDomElementImpl_ElementAttrNamedNodeMapImpl_init() {}

J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomElementImpl_ElementAttrNamedNodeMapImpl, this$0_, OrgApacheHarmonyXmlDomElementImpl *)

#endif // _OrgApacheHarmonyXmlDomElementImpl_H_
