//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/apache/harmony/xml/dom/EntityReferenceImpl.java
//

#ifndef _OrgApacheHarmonyXmlDomEntityReferenceImpl_H_
#define _OrgApacheHarmonyXmlDomEntityReferenceImpl_H_

@class OrgApacheHarmonyXmlDomDocumentImpl;

#import "JreEmulation.h"
#include "org/apache/harmony/xml/dom/LeafNodeImpl.h"
#include "org/w3c/dom/EntityReference.h"

@interface OrgApacheHarmonyXmlDomEntityReferenceImpl : OrgApacheHarmonyXmlDomLeafNodeImpl < OrgW3cDomEntityReference > {
 @public
  NSString *name_;
}

- (instancetype)initWithOrgApacheHarmonyXmlDomDocumentImpl:(OrgApacheHarmonyXmlDomDocumentImpl *)document
                                              withNSString:(NSString *)name;

- (NSString *)getNodeName;

- (jshort)getNodeType;

- (void)copyAllFieldsTo:(OrgApacheHarmonyXmlDomEntityReferenceImpl *)other;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlDomEntityReferenceImpl_init() {}

J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomEntityReferenceImpl, name_, NSString *)

#endif // _OrgApacheHarmonyXmlDomEntityReferenceImpl_H_
