//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/apache/harmony/xml/dom/InnerNodeImpl.java
//

#ifndef _OrgApacheHarmonyXmlDomInnerNodeImpl_H_
#define _OrgApacheHarmonyXmlDomInnerNodeImpl_H_

@class JavaLangStringBuilder;
@class OrgApacheHarmonyXmlDomDocumentImpl;
@class OrgApacheHarmonyXmlDomNodeListImpl;
@protocol JavaUtilList;
@protocol OrgW3cDomNode;
@protocol OrgW3cDomNodeList;

#import "JreEmulation.h"
#include "org/apache/harmony/xml/dom/LeafNodeImpl.h"

@interface OrgApacheHarmonyXmlDomInnerNodeImpl : OrgApacheHarmonyXmlDomLeafNodeImpl {
 @public
  id<JavaUtilList> children_;
}

- (instancetype)initWithOrgApacheHarmonyXmlDomDocumentImpl:(OrgApacheHarmonyXmlDomDocumentImpl *)document;

- (id<OrgW3cDomNode>)appendChildWithOrgW3cDomNode:(id<OrgW3cDomNode>)newChild;

- (id<OrgW3cDomNodeList>)getChildNodes;

- (id<OrgW3cDomNode>)getFirstChild;

- (id<OrgW3cDomNode>)getLastChild;

- (id<OrgW3cDomNode>)getNextSibling;

- (jboolean)hasChildNodes;

- (id<OrgW3cDomNode>)insertBeforeWithOrgW3cDomNode:(id<OrgW3cDomNode>)newChild
                                 withOrgW3cDomNode:(id<OrgW3cDomNode>)refChild;

- (id<OrgW3cDomNode>)insertChildAtWithOrgW3cDomNode:(id<OrgW3cDomNode>)newChild
                                            withInt:(jint)index;

- (jboolean)isParentOfWithOrgW3cDomNode:(id<OrgW3cDomNode>)node;

- (void)normalize;

- (void)refreshIndicesWithInt:(jint)fromIndex;

- (id<OrgW3cDomNode>)removeChildWithOrgW3cDomNode:(id<OrgW3cDomNode>)oldChild;

- (id<OrgW3cDomNode>)replaceChildWithOrgW3cDomNode:(id<OrgW3cDomNode>)newChild
                                 withOrgW3cDomNode:(id<OrgW3cDomNode>)oldChild;

- (NSString *)getTextContent;

- (void)getTextContentWithJavaLangStringBuilder:(JavaLangStringBuilder *)buf;

- (jboolean)hasTextContentWithOrgW3cDomNode:(id<OrgW3cDomNode>)child;

- (void)getElementsByTagNameWithOrgApacheHarmonyXmlDomNodeListImpl:(OrgApacheHarmonyXmlDomNodeListImpl *)outArg
                                                      withNSString:(NSString *)name;

- (void)getElementsByTagNameNSWithOrgApacheHarmonyXmlDomNodeListImpl:(OrgApacheHarmonyXmlDomNodeListImpl *)outArg
                                                        withNSString:(NSString *)namespaceURI
                                                        withNSString:(NSString *)localName;

+ (jboolean)matchesNameOrWildcardWithNSString:(NSString *)pattern
                                 withNSString:(NSString *)s;

- (void)copyAllFieldsTo:(OrgApacheHarmonyXmlDomInnerNodeImpl *)other;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlDomInnerNodeImpl_init() {}

J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomInnerNodeImpl, children_, id<JavaUtilList>)

#endif // _OrgApacheHarmonyXmlDomInnerNodeImpl_H_
