//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/apache/harmony/xml/dom/LeafNodeImpl.java
//

#ifndef _OrgApacheHarmonyXmlDomLeafNodeImpl_H_
#define _OrgApacheHarmonyXmlDomLeafNodeImpl_H_

@class OrgApacheHarmonyXmlDomDocumentImpl;
@class OrgApacheHarmonyXmlDomInnerNodeImpl;
@protocol OrgW3cDomNode;

#import "JreEmulation.h"
#include "org/apache/harmony/xml/dom/NodeImpl.h"

@interface OrgApacheHarmonyXmlDomLeafNodeImpl : OrgApacheHarmonyXmlDomNodeImpl {
 @public
  OrgApacheHarmonyXmlDomInnerNodeImpl *parent_;
  jint index_;
}

- (instancetype)initWithOrgApacheHarmonyXmlDomDocumentImpl:(OrgApacheHarmonyXmlDomDocumentImpl *)document;

- (id<OrgW3cDomNode>)getNextSibling;

- (id<OrgW3cDomNode>)getParentNode;

- (id<OrgW3cDomNode>)getPreviousSibling;

- (jboolean)isParentOfWithOrgW3cDomNode:(id<OrgW3cDomNode>)node;

- (void)copyAllFieldsTo:(OrgApacheHarmonyXmlDomLeafNodeImpl *)other;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlDomLeafNodeImpl_init() {}

J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomLeafNodeImpl, parent_, OrgApacheHarmonyXmlDomInnerNodeImpl *)

#endif // _OrgApacheHarmonyXmlDomLeafNodeImpl_H_
