//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/apache/harmony/xml/dom/NodeListImpl.java
//

#ifndef _OrgApacheHarmonyXmlDomNodeListImpl_H_
#define _OrgApacheHarmonyXmlDomNodeListImpl_H_

@class OrgApacheHarmonyXmlDomNodeImpl;
@protocol JavaUtilList;
@protocol OrgW3cDomNode;

#import "JreEmulation.h"
#include "org/w3c/dom/NodeList.h"

@interface OrgApacheHarmonyXmlDomNodeListImpl : NSObject < OrgW3cDomNodeList > {
 @public
  id<JavaUtilList> children_;
}

- (instancetype)init;

- (instancetype)initWithJavaUtilList:(id<JavaUtilList>)list;

- (void)addWithOrgApacheHarmonyXmlDomNodeImpl:(OrgApacheHarmonyXmlDomNodeImpl *)node;

- (jint)getLength;

- (id<OrgW3cDomNode>)itemWithInt:(jint)index;

- (void)copyAllFieldsTo:(OrgApacheHarmonyXmlDomNodeListImpl *)other;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlDomNodeListImpl_init() {}

J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomNodeListImpl, children_, id<JavaUtilList>)

#endif // _OrgApacheHarmonyXmlDomNodeListImpl_H_
