//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/apache/harmony/xml/dom/NotationImpl.java
//

#ifndef _OrgApacheHarmonyXmlDomNotationImpl_H_
#define _OrgApacheHarmonyXmlDomNotationImpl_H_

@class OrgApacheHarmonyXmlDomDocumentImpl;

#import "JreEmulation.h"
#include "org/apache/harmony/xml/dom/LeafNodeImpl.h"
#include "org/w3c/dom/Notation.h"

@interface OrgApacheHarmonyXmlDomNotationImpl : OrgApacheHarmonyXmlDomLeafNodeImpl < OrgW3cDomNotation > {
 @public
  NSString *notationName_;
  NSString *publicID_;
  NSString *systemID_;
}

- (instancetype)initWithOrgApacheHarmonyXmlDomDocumentImpl:(OrgApacheHarmonyXmlDomDocumentImpl *)document
                                              withNSString:(NSString *)notationName
                                              withNSString:(NSString *)publicID
                                              withNSString:(NSString *)systemID;

- (NSString *)getNodeName;

- (jshort)getNodeType;

- (NSString *)getPublicId;

- (NSString *)getSystemId;

- (void)copyAllFieldsTo:(OrgApacheHarmonyXmlDomNotationImpl *)other;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlDomNotationImpl_init() {}

J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomNotationImpl, notationName_, NSString *)
J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomNotationImpl, publicID_, NSString *)
J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomNotationImpl, systemID_, NSString *)

#endif // _OrgApacheHarmonyXmlDomNotationImpl_H_
