//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/apache/harmony/xml/dom/ProcessingInstructionImpl.java
//

#ifndef _OrgApacheHarmonyXmlDomProcessingInstructionImpl_H_
#define _OrgApacheHarmonyXmlDomProcessingInstructionImpl_H_

@class OrgApacheHarmonyXmlDomDocumentImpl;

#import "JreEmulation.h"
#include "org/apache/harmony/xml/dom/LeafNodeImpl.h"
#include "org/w3c/dom/ProcessingInstruction.h"

@interface OrgApacheHarmonyXmlDomProcessingInstructionImpl : OrgApacheHarmonyXmlDomLeafNodeImpl < OrgW3cDomProcessingInstruction > {
 @public
  NSString *target_;
  NSString *data_;
}

- (instancetype)initWithOrgApacheHarmonyXmlDomDocumentImpl:(OrgApacheHarmonyXmlDomDocumentImpl *)document
                                              withNSString:(NSString *)target
                                              withNSString:(NSString *)data;

- (NSString *)getData;

- (NSString *)getNodeName;

- (jshort)getNodeType;

- (NSString *)getNodeValue;

- (NSString *)getTarget;

- (void)setDataWithNSString:(NSString *)data;

- (void)copyAllFieldsTo:(OrgApacheHarmonyXmlDomProcessingInstructionImpl *)other;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlDomProcessingInstructionImpl_init() {}

J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomProcessingInstructionImpl, target_, NSString *)
J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomProcessingInstructionImpl, data_, NSString *)

#endif // _OrgApacheHarmonyXmlDomProcessingInstructionImpl_H_
