//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/app/Application.java
//

#ifndef _AndroidAppApplication_H_
#define _AndroidAppApplication_H_

@protocol AndroidContentContext;

#import "JreEmulation.h"

@interface AndroidAppApplication : NSObject {
}

- (void)onCreate;

- (void)onTerminate;

- (id<AndroidContentContext>)getApplicationContext;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void AndroidAppApplication_init() {}

#endif // _AndroidAppApplication_H_
