//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/app/Application.java
//

#ifndef _AndroidAppApplication_H_
#define _AndroidAppApplication_H_

#include "J2ObjC_header.h"

@protocol AndroidContentContext;

@interface AndroidAppApplication : NSObject

#pragma mark Public

- (instancetype)init;

- (id<AndroidContentContext>)getApplicationContext;

- (void)onCreate;

- (void)onTerminate;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidAppApplication)

FOUNDATION_EXPORT void AndroidAppApplication_init(AndroidAppApplication *self);

J2OBJC_TYPE_LITERAL_HEADER(AndroidAppApplication)

#endif // _AndroidAppApplication_H_
