//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/security/auth/AuthPermission.java
//

#ifndef _JavaxSecurityAuthAuthPermission_H_
#define _JavaxSecurityAuthAuthPermission_H_

#include "J2ObjC_header.h"
#include "java/security/BasicPermission.h"

@class JavaSecurityPermission;

@interface JavaxSecurityAuthAuthPermission : JavaSecurityBasicPermission

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)name;

- (instancetype)initWithNSString:(NSString *)name
                    withNSString:(NSString *)actions;

- (NSString *)getActions;

- (jboolean)impliesWithJavaSecurityPermission:(JavaSecurityPermission *)permission;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxSecurityAuthAuthPermission)

FOUNDATION_EXPORT void JavaxSecurityAuthAuthPermission_initWithNSString_(JavaxSecurityAuthAuthPermission *self, NSString *name);

FOUNDATION_EXPORT JavaxSecurityAuthAuthPermission *new_JavaxSecurityAuthAuthPermission_initWithNSString_(NSString *name) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JavaxSecurityAuthAuthPermission_initWithNSString_withNSString_(JavaxSecurityAuthAuthPermission *self, NSString *name, NSString *actions);

FOUNDATION_EXPORT JavaxSecurityAuthAuthPermission *new_JavaxSecurityAuthAuthPermission_initWithNSString_withNSString_(NSString *name, NSString *actions) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaxSecurityAuthAuthPermission)

#endif // _JavaxSecurityAuthAuthPermission_H_
