//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/security/auth/Destroyable.java
//

#ifndef _JavaxSecurityAuthDestroyable_H_
#define _JavaxSecurityAuthDestroyable_H_

#import "JreEmulation.h"

@protocol JavaxSecurityAuthDestroyable < NSObject, JavaObject >

- (void)destroy;

- (jboolean)isDestroyed;

@end

__attribute__((always_inline)) inline void JavaxSecurityAuthDestroyable_init() {}

#endif // _JavaxSecurityAuthDestroyable_H_
