//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/security/auth/DestroyFailedException.java
//

#ifndef _JavaxSecurityAuthDestroyFailedException_H_
#define _JavaxSecurityAuthDestroyFailedException_H_

#import "JreEmulation.h"
#include "java/lang/Exception.h"

#define JavaxSecurityAuthDestroyFailedException_serialVersionUID -7790152857282749162LL

@interface JavaxSecurityAuthDestroyFailedException : JavaLangException {
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)message;

@end

__attribute__((always_inline)) inline void JavaxSecurityAuthDestroyFailedException_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaxSecurityAuthDestroyFailedException, serialVersionUID, jlong)

#endif // _JavaxSecurityAuthDestroyFailedException_H_
