//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/security/auth/PrivateCredentialPermission.java
//

#ifndef _JavaxSecurityAuthPrivateCredentialPermission_H_
#define _JavaxSecurityAuthPrivateCredentialPermission_H_

@class IOSObjectArray;

#import "JreEmulation.h"
#include "java/security/Permission.h"

@interface JavaxSecurityAuthPrivateCredentialPermission : JavaSecurityPermission {
}

- (instancetype)initWithNSString:(NSString *)name
                    withNSString:(NSString *)action;

- (IOSObjectArray *)getPrincipals;

- (NSString *)getCredentialClass;

- (NSString *)getActions;

- (jboolean)impliesWithJavaSecurityPermission:(JavaSecurityPermission *)permission;

- (jboolean)isEqual:(id)pObj;

- (NSUInteger)hash;

@end

__attribute__((always_inline)) inline void JavaxSecurityAuthPrivateCredentialPermission_init() {}

#endif // _JavaxSecurityAuthPrivateCredentialPermission_H_
