//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/security/auth/SubjectDomainCombiner.java
//

#ifndef _JavaxSecurityAuthSubjectDomainCombiner_H_
#define _JavaxSecurityAuthSubjectDomainCombiner_H_

@class IOSObjectArray;
@class JavaxSecurityAuthSubject;

#import "JreEmulation.h"
#include "java/security/DomainCombiner.h"

@interface JavaxSecurityAuthSubjectDomainCombiner : NSObject < JavaSecurityDomainCombiner > {
}

- (instancetype)initWithJavaxSecurityAuthSubject:(JavaxSecurityAuthSubject *)subject;

- (JavaxSecurityAuthSubject *)getSubject;

- (IOSObjectArray *)combineWithJavaSecurityProtectionDomainArray:(IOSObjectArray *)currentDomains
                           withJavaSecurityProtectionDomainArray:(IOSObjectArray *)assignedDomains;

@end

__attribute__((always_inline)) inline void JavaxSecurityAuthSubjectDomainCombiner_init() {}

#endif // _JavaxSecurityAuthSubjectDomainCombiner_H_
