//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/cert/X509CRLEntry.java
//

#ifndef _JavaSecurityCertX509CRLEntry_H_
#define _JavaSecurityCertX509CRLEntry_H_

#include "J2ObjC_header.h"
#include "java/security/cert/X509Extension.h"

@class IOSByteArray;
@class JavaMathBigInteger;
@class JavaUtilDate;
@class JavaxSecurityAuthX500X500Principal;

@interface JavaSecurityCertX509CRLEntry : NSObject < JavaSecurityCertX509Extension >

#pragma mark Public

- (instancetype)init;

- (jboolean)isEqual:(id)other;

- (JavaxSecurityAuthX500X500Principal *)getCertificateIssuer;

- (IOSByteArray *)getEncoded;

- (JavaUtilDate *)getRevocationDate;

- (JavaMathBigInteger *)getSerialNumber;

- (jboolean)hasExtensions;

- (NSUInteger)hash;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaSecurityCertX509CRLEntry)

FOUNDATION_EXPORT void JavaSecurityCertX509CRLEntry_init(JavaSecurityCertX509CRLEntry *self);

J2OBJC_TYPE_LITERAL_HEADER(JavaSecurityCertX509CRLEntry)

#endif // _JavaSecurityCertX509CRLEntry_H_
