//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/cert/X509CRLEntry.java
//

#ifndef _JavaSecurityCertX509CRLEntry_H_
#define _JavaSecurityCertX509CRLEntry_H_

@class IOSByteArray;
@class JavaMathBigInteger;
@class JavaUtilDate;
@class JavaxSecurityAuthX500X500Principal;

#import "JreEmulation.h"
#include "java/security/cert/X509Extension.h"

@interface JavaSecurityCertX509CRLEntry : NSObject < JavaSecurityCertX509Extension > {
}

- (instancetype)init;

- (jboolean)isEqual:(id)other;

- (NSUInteger)hash;

- (IOSByteArray *)getEncoded;

- (JavaMathBigInteger *)getSerialNumber;

- (JavaxSecurityAuthX500X500Principal *)getCertificateIssuer;

- (JavaUtilDate *)getRevocationDate;

- (jboolean)hasExtensions;

- (NSString *)description;

@end

__attribute__((always_inline)) inline void JavaSecurityCertX509CRLEntry_init() {}

#endif // _JavaSecurityCertX509CRLEntry_H_
