//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/graphics/Bitmap.java
//

#ifndef _AndroidGraphicsBitmap_H_
#define _AndroidGraphicsBitmap_H_

#include "J2ObjC_header.h"

@protocol AndroidGraphicsBitmap < NSObject, JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidGraphicsBitmap)

J2OBJC_TYPE_LITERAL_HEADER(AndroidGraphicsBitmap)

#endif // _AndroidGraphicsBitmap_H_
