//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/graphics/Bitmap.java
//

#ifndef _AndroidGraphicsBitmap_H_
#define _AndroidGraphicsBitmap_H_

#import "JreEmulation.h"

@protocol AndroidGraphicsBitmap < NSObject, JavaObject >

@end

__attribute__((always_inline)) inline void AndroidGraphicsBitmap_init() {}

#endif // _AndroidGraphicsBitmap_H_
