//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/graphics/Color.java
//

#ifndef _AndroidGraphicsColor_H_
#define _AndroidGraphicsColor_H_

#include "J2ObjC_header.h"

@class IOSFloatArray;

#define AndroidGraphicsColor_BLACK -16777216
#define AndroidGraphicsColor_DKGRAY -12303292
#define AndroidGraphicsColor_GRAY -7829368
#define AndroidGraphicsColor_LTGRAY -3355444
#define AndroidGraphicsColor_WHITE -1
#define AndroidGraphicsColor_RED -65536
#define AndroidGraphicsColor_GREEN -16711936
#define AndroidGraphicsColor_BLUE -16776961
#define AndroidGraphicsColor_YELLOW -256
#define AndroidGraphicsColor_CYAN -16711681
#define AndroidGraphicsColor_MAGENTA -65281
#define AndroidGraphicsColor_TRANSPARENT 0

@interface AndroidGraphicsColor : NSObject

#pragma mark Public

- (instancetype)init;

+ (jint)alphaWithInt:(jint)color;

+ (jint)argbWithInt:(jint)alpha
            withInt:(jint)red
            withInt:(jint)green
            withInt:(jint)blue;

+ (jint)blueWithInt:(jint)color;

+ (jfloat)brightnessWithInt:(jint)color;

+ (void)colorToHSVWithInt:(jint)color
           withFloatArray:(IOSFloatArray *)hsv;

+ (jint)greenWithInt:(jint)color;

+ (jint)HSVToColorWithFloatArray:(IOSFloatArray *)hsv;

+ (jint)HSVToColorWithInt:(jint)alpha
           withFloatArray:(IOSFloatArray *)hsv;

+ (jfloat)hueWithInt:(jint)color;

+ (jint)parseColorWithNSString:(NSString *)colorString;

+ (jint)redWithInt:(jint)color;

+ (jint)rgbWithInt:(jint)red
           withInt:(jint)green
           withInt:(jint)blue;

+ (void)RGBToHSVWithInt:(jint)red
                withInt:(jint)green
                withInt:(jint)blue
         withFloatArray:(IOSFloatArray *)hsv;

+ (jfloat)saturationWithInt:(jint)color;

@end

J2OBJC_STATIC_INIT(AndroidGraphicsColor)

J2OBJC_STATIC_FIELD_GETTER(AndroidGraphicsColor, BLACK, jint)

J2OBJC_STATIC_FIELD_GETTER(AndroidGraphicsColor, DKGRAY, jint)

J2OBJC_STATIC_FIELD_GETTER(AndroidGraphicsColor, GRAY, jint)

J2OBJC_STATIC_FIELD_GETTER(AndroidGraphicsColor, LTGRAY, jint)

J2OBJC_STATIC_FIELD_GETTER(AndroidGraphicsColor, WHITE, jint)

J2OBJC_STATIC_FIELD_GETTER(AndroidGraphicsColor, RED, jint)

J2OBJC_STATIC_FIELD_GETTER(AndroidGraphicsColor, GREEN, jint)

J2OBJC_STATIC_FIELD_GETTER(AndroidGraphicsColor, BLUE, jint)

J2OBJC_STATIC_FIELD_GETTER(AndroidGraphicsColor, YELLOW, jint)

J2OBJC_STATIC_FIELD_GETTER(AndroidGraphicsColor, CYAN, jint)

J2OBJC_STATIC_FIELD_GETTER(AndroidGraphicsColor, MAGENTA, jint)

J2OBJC_STATIC_FIELD_GETTER(AndroidGraphicsColor, TRANSPARENT, jint)

FOUNDATION_EXPORT jint AndroidGraphicsColor_alphaWithInt_(jint color);

FOUNDATION_EXPORT jint AndroidGraphicsColor_redWithInt_(jint color);

FOUNDATION_EXPORT jint AndroidGraphicsColor_greenWithInt_(jint color);

FOUNDATION_EXPORT jint AndroidGraphicsColor_blueWithInt_(jint color);

FOUNDATION_EXPORT jint AndroidGraphicsColor_rgbWithInt_withInt_withInt_(jint red, jint green, jint blue);

FOUNDATION_EXPORT jint AndroidGraphicsColor_argbWithInt_withInt_withInt_withInt_(jint alpha, jint red, jint green, jint blue);

FOUNDATION_EXPORT jfloat AndroidGraphicsColor_hueWithInt_(jint color);

FOUNDATION_EXPORT jfloat AndroidGraphicsColor_saturationWithInt_(jint color);

FOUNDATION_EXPORT jfloat AndroidGraphicsColor_brightnessWithInt_(jint color);

FOUNDATION_EXPORT jint AndroidGraphicsColor_parseColorWithNSString_(NSString *colorString);

FOUNDATION_EXPORT void AndroidGraphicsColor_RGBToHSVWithInt_withInt_withInt_withFloatArray_(jint red, jint green, jint blue, IOSFloatArray *hsv);

FOUNDATION_EXPORT void AndroidGraphicsColor_colorToHSVWithInt_withFloatArray_(jint color, IOSFloatArray *hsv);

FOUNDATION_EXPORT jint AndroidGraphicsColor_HSVToColorWithFloatArray_(IOSFloatArray *hsv);

FOUNDATION_EXPORT jint AndroidGraphicsColor_HSVToColorWithInt_withFloatArray_(jint alpha, IOSFloatArray *hsv);

FOUNDATION_EXPORT void AndroidGraphicsColor_init(AndroidGraphicsColor *self);

FOUNDATION_EXPORT AndroidGraphicsColor *new_AndroidGraphicsColor_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(AndroidGraphicsColor)

#endif // _AndroidGraphicsColor_H_
