//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/graphics/DashPathEffect.java
//

#ifndef _AndroidGraphicsDashPathEffect_H_
#define _AndroidGraphicsDashPathEffect_H_

#include "J2ObjC_header.h"

@class IOSFloatArray;

@interface AndroidGraphicsDashPathEffect : NSObject

#pragma mark Public

- (instancetype)initWithFloatArray:(IOSFloatArray *)intervals
                         withFloat:(jfloat)phase;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidGraphicsDashPathEffect)

FOUNDATION_EXPORT void AndroidGraphicsDashPathEffect_initWithFloatArray_withFloat_(AndroidGraphicsDashPathEffect *self, IOSFloatArray *intervals, jfloat phase);

FOUNDATION_EXPORT AndroidGraphicsDashPathEffect *new_AndroidGraphicsDashPathEffect_initWithFloatArray_withFloat_(IOSFloatArray *intervals, jfloat phase) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(AndroidGraphicsDashPathEffect)

#endif // _AndroidGraphicsDashPathEffect_H_
