//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/graphics/Paint.java
//

#ifndef _AndroidGraphicsPaint_H_
#define _AndroidGraphicsPaint_H_

@class AndroidGraphicsPaint_AlignEnum;
@class AndroidGraphicsPaint_StyleEnum;

#import "JreEmulation.h"
#include "java/lang/Enum.h"

@interface AndroidGraphicsPaint : NSObject {
}

- (jfloat)getTextSize;

- (void)setTextSizeWithFloat:(jfloat)pFontSize;

- (void)setColorWithInt:(jint)pColor;

- (void)setAntiAliasWithBoolean:(jboolean)pB;

- (jfloat)ascent;

- (jfloat)descent;

- (jfloat)measureTextWithNSString:(NSString *)pText;

- (AndroidGraphicsPaint_StyleEnum *)getStyle;

- (void)setColorFilterWithId:(id)pObject;

- (void)setStrokeWidthWithFloat:(jfloat)pStrokeWidth;

- (void)setStyleWithAndroidGraphicsPaint_StyleEnum:(AndroidGraphicsPaint_StyleEnum *)pStroke;

- (void)setTextAlignWithAndroidGraphicsPaint_AlignEnum:(AndroidGraphicsPaint_AlignEnum *)pLeft;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void AndroidGraphicsPaint_init() {}

typedef enum {
  AndroidGraphicsPaint_Align_LEFT = 0,
  AndroidGraphicsPaint_Align_CENTER = 1,
  AndroidGraphicsPaint_Align_RIGHT = 2,
} AndroidGraphicsPaint_Align;

@interface AndroidGraphicsPaint_AlignEnum : JavaLangEnum < NSCopying > {
 @public
  jint nativeInt_;
}

- (instancetype)initWithInt:(jint)nativeInt
               withNSString:(NSString *)__name
                    withInt:(jint)__ordinal;

+ (IOSObjectArray *)values;
FOUNDATION_EXPORT IOSObjectArray *AndroidGraphicsPaint_AlignEnum_values();

+ (AndroidGraphicsPaint_AlignEnum *)valueOfWithNSString:(NSString *)name;

FOUNDATION_EXPORT AndroidGraphicsPaint_AlignEnum *AndroidGraphicsPaint_AlignEnum_valueOfWithNSString_(NSString *name);- (id)copyWithZone:(NSZone *)zone;

@end

FOUNDATION_EXPORT BOOL AndroidGraphicsPaint_AlignEnum_initialized;
J2OBJC_STATIC_INIT(AndroidGraphicsPaint_AlignEnum)

FOUNDATION_EXPORT AndroidGraphicsPaint_AlignEnum *AndroidGraphicsPaint_AlignEnum_values_[];

#define AndroidGraphicsPaint_AlignEnum_LEFT AndroidGraphicsPaint_AlignEnum_values_[AndroidGraphicsPaint_Align_LEFT]
J2OBJC_STATIC_FIELD_GETTER(AndroidGraphicsPaint_AlignEnum, LEFT, AndroidGraphicsPaint_AlignEnum *)

#define AndroidGraphicsPaint_AlignEnum_CENTER AndroidGraphicsPaint_AlignEnum_values_[AndroidGraphicsPaint_Align_CENTER]
J2OBJC_STATIC_FIELD_GETTER(AndroidGraphicsPaint_AlignEnum, CENTER, AndroidGraphicsPaint_AlignEnum *)

#define AndroidGraphicsPaint_AlignEnum_RIGHT AndroidGraphicsPaint_AlignEnum_values_[AndroidGraphicsPaint_Align_RIGHT]
J2OBJC_STATIC_FIELD_GETTER(AndroidGraphicsPaint_AlignEnum, RIGHT, AndroidGraphicsPaint_AlignEnum *)

typedef enum {
  AndroidGraphicsPaint_Style_FILL = 0,
  AndroidGraphicsPaint_Style_STROKE = 1,
  AndroidGraphicsPaint_Style_FILL_AND_STROKE = 2,
} AndroidGraphicsPaint_Style;

@interface AndroidGraphicsPaint_StyleEnum : JavaLangEnum < NSCopying > {
 @public
  jint nativeInt_;
}

- (instancetype)initWithInt:(jint)nativeInt
               withNSString:(NSString *)__name
                    withInt:(jint)__ordinal;

+ (IOSObjectArray *)values;
FOUNDATION_EXPORT IOSObjectArray *AndroidGraphicsPaint_StyleEnum_values();

+ (AndroidGraphicsPaint_StyleEnum *)valueOfWithNSString:(NSString *)name;

FOUNDATION_EXPORT AndroidGraphicsPaint_StyleEnum *AndroidGraphicsPaint_StyleEnum_valueOfWithNSString_(NSString *name);- (id)copyWithZone:(NSZone *)zone;

@end

FOUNDATION_EXPORT BOOL AndroidGraphicsPaint_StyleEnum_initialized;
J2OBJC_STATIC_INIT(AndroidGraphicsPaint_StyleEnum)

FOUNDATION_EXPORT AndroidGraphicsPaint_StyleEnum *AndroidGraphicsPaint_StyleEnum_values_[];

#define AndroidGraphicsPaint_StyleEnum_FILL AndroidGraphicsPaint_StyleEnum_values_[AndroidGraphicsPaint_Style_FILL]
J2OBJC_STATIC_FIELD_GETTER(AndroidGraphicsPaint_StyleEnum, FILL, AndroidGraphicsPaint_StyleEnum *)

#define AndroidGraphicsPaint_StyleEnum_STROKE AndroidGraphicsPaint_StyleEnum_values_[AndroidGraphicsPaint_Style_STROKE]
J2OBJC_STATIC_FIELD_GETTER(AndroidGraphicsPaint_StyleEnum, STROKE, AndroidGraphicsPaint_StyleEnum *)

#define AndroidGraphicsPaint_StyleEnum_FILL_AND_STROKE AndroidGraphicsPaint_StyleEnum_values_[AndroidGraphicsPaint_Style_FILL_AND_STROKE]
J2OBJC_STATIC_FIELD_GETTER(AndroidGraphicsPaint_StyleEnum, FILL_AND_STROKE, AndroidGraphicsPaint_StyleEnum *)

#endif // _AndroidGraphicsPaint_H_
