//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/graphics/Path.java
//

#ifndef _AndroidGraphicsPath_H_
#define _AndroidGraphicsPath_H_

#include "J2ObjC_header.h"

@interface AndroidGraphicsPath : NSObject

#pragma mark Public

- (instancetype)init;

- (void)lineToWithFloat:(jfloat)pX
              withFloat:(jfloat)pY;

- (void)moveToWithFloat:(jfloat)pX
              withFloat:(jfloat)pY;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidGraphicsPath)

FOUNDATION_EXPORT void AndroidGraphicsPath_init(AndroidGraphicsPath *self);

FOUNDATION_EXPORT AndroidGraphicsPath *new_AndroidGraphicsPath_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(AndroidGraphicsPath)

#endif // _AndroidGraphicsPath_H_
