//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/graphics/Path.java
//

#ifndef _AndroidGraphicsPath_H_
#define _AndroidGraphicsPath_H_

#import "JreEmulation.h"

@interface AndroidGraphicsPath : NSObject {
}

- (void)lineToWithFloat:(jfloat)pX
              withFloat:(jfloat)pY;

- (void)moveToWithFloat:(jfloat)pX
              withFloat:(jfloat)pY;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void AndroidGraphicsPath_init() {}

#endif // _AndroidGraphicsPath_H_
