//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/graphics/Rect.java
//

#ifndef _AndroidGraphicsRect_H_
#define _AndroidGraphicsRect_H_

#import "JreEmulation.h"

@interface AndroidGraphicsRect : NSObject {
 @public
  jint left_;
  jint top_;
  jint right_;
  jint bottom_;
}

- (jboolean)containsWithInt:(jint)pX
                    withInt:(jint)pY;

- (jint)width;

- (jint)height;

- (instancetype)init;

- (void)copyAllFieldsTo:(AndroidGraphicsRect *)other;

@end

__attribute__((always_inline)) inline void AndroidGraphicsRect_init() {}

#endif // _AndroidGraphicsRect_H_
