//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/graphics/Rect.java
//

#ifndef _AndroidGraphicsRect_H_
#define _AndroidGraphicsRect_H_

#include "J2ObjC_header.h"

@interface AndroidGraphicsRect : NSObject {
 @public
  jint left_;
  jint top_;
  jint right_;
  jint bottom_;
}

#pragma mark Public

- (instancetype)init;

- (jboolean)containsWithInt:(jint)pX
                    withInt:(jint)pY;

- (jint)height;

- (jint)width;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidGraphicsRect)

FOUNDATION_EXPORT void AndroidGraphicsRect_init(AndroidGraphicsRect *self);

FOUNDATION_EXPORT AndroidGraphicsRect *new_AndroidGraphicsRect_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(AndroidGraphicsRect)

#endif // _AndroidGraphicsRect_H_
