//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/security/auth/callback/CallbackHandler.java
//

#ifndef _JavaxSecurityAuthCallbackCallbackHandler_H_
#define _JavaxSecurityAuthCallbackCallbackHandler_H_

@class IOSObjectArray;

#import "JreEmulation.h"

@protocol JavaxSecurityAuthCallbackCallbackHandler < NSObject, JavaObject >

- (void)handleWithJavaxSecurityAuthCallbackCallbackArray:(IOSObjectArray *)callbacks;

@end

__attribute__((always_inline)) inline void JavaxSecurityAuthCallbackCallbackHandler_init() {}

#endif // _JavaxSecurityAuthCallbackCallbackHandler_H_
