//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/security/auth/callback/Callback.java
//

#ifndef _JavaxSecurityAuthCallbackCallback_H_
#define _JavaxSecurityAuthCallbackCallback_H_

#import "JreEmulation.h"

@protocol JavaxSecurityAuthCallbackCallback < NSObject, JavaObject >

@end

__attribute__((always_inline)) inline void JavaxSecurityAuthCallbackCallback_init() {}

#endif // _JavaxSecurityAuthCallbackCallback_H_
