//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/security/auth/callback/PasswordCallback.java
//

#ifndef _JavaxSecurityAuthCallbackPasswordCallback_H_
#define _JavaxSecurityAuthCallbackPasswordCallback_H_

@class IOSCharArray;

#import "JreEmulation.h"
#include "java/io/Serializable.h"
#include "javax/security/auth/callback/Callback.h"

#define JavaxSecurityAuthCallbackPasswordCallback_serialVersionUID 2267422647454909926LL

@interface JavaxSecurityAuthCallbackPasswordCallback : NSObject < JavaxSecurityAuthCallbackCallback, JavaIoSerializable > {
 @public
  NSString *prompt_;
  jboolean echoOn_;
  IOSCharArray *inputPassword_;
}

- (void)setPromptWithNSString:(NSString *)prompt;

- (instancetype)initWithNSString:(NSString *)prompt
                     withBoolean:(jboolean)echoOn;

- (NSString *)getPrompt;

- (jboolean)isEchoOn;

- (void)setPasswordWithCharArray:(IOSCharArray *)password;

- (IOSCharArray *)getPassword;

- (void)clearPassword;

- (void)copyAllFieldsTo:(JavaxSecurityAuthCallbackPasswordCallback *)other;

@end

__attribute__((always_inline)) inline void JavaxSecurityAuthCallbackPasswordCallback_init() {}

J2OBJC_FIELD_SETTER(JavaxSecurityAuthCallbackPasswordCallback, prompt_, NSString *)
J2OBJC_FIELD_SETTER(JavaxSecurityAuthCallbackPasswordCallback, inputPassword_, IOSCharArray *)

J2OBJC_STATIC_FIELD_GETTER(JavaxSecurityAuthCallbackPasswordCallback, serialVersionUID, jlong)

#endif // _JavaxSecurityAuthCallbackPasswordCallback_H_
