//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/security/auth/callback/UnsupportedCallbackException.java
//

#ifndef _JavaxSecurityAuthCallbackUnsupportedCallbackException_H_
#define _JavaxSecurityAuthCallbackUnsupportedCallbackException_H_

@protocol JavaxSecurityAuthCallbackCallback;

#import "JreEmulation.h"
#include "java/lang/Exception.h"

#define JavaxSecurityAuthCallbackUnsupportedCallbackException_serialVersionUID -6873556327655666839LL

@interface JavaxSecurityAuthCallbackUnsupportedCallbackException : JavaLangException {
 @public
  id<JavaxSecurityAuthCallbackCallback> callback_;
}

- (instancetype)initWithJavaxSecurityAuthCallbackCallback:(id<JavaxSecurityAuthCallbackCallback>)callback;

- (instancetype)initWithJavaxSecurityAuthCallbackCallback:(id<JavaxSecurityAuthCallbackCallback>)callback
                                             withNSString:(NSString *)message;

- (id<JavaxSecurityAuthCallbackCallback>)getCallback;

- (void)copyAllFieldsTo:(JavaxSecurityAuthCallbackUnsupportedCallbackException *)other;

@end

__attribute__((always_inline)) inline void JavaxSecurityAuthCallbackUnsupportedCallbackException_init() {}

J2OBJC_FIELD_SETTER(JavaxSecurityAuthCallbackUnsupportedCallbackException, callback_, id<JavaxSecurityAuthCallbackCallback>)

J2OBJC_STATIC_FIELD_GETTER(JavaxSecurityAuthCallbackUnsupportedCallbackException, serialVersionUID, jlong)

#endif // _JavaxSecurityAuthCallbackUnsupportedCallbackException_H_
