//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/xml/transform/stream/FilePathToURI.java
//

#ifndef _JavaxXmlTransformStreamFilePathToURI_H_
#define _JavaxXmlTransformStreamFilePathToURI_H_

@class IOSBooleanArray;
@class IOSCharArray;

#import "JreEmulation.h"

@interface JavaxXmlTransformStreamFilePathToURI : NSObject {
}

+ (NSString *)filepath2URIWithNSString:(NSString *)path;

- (instancetype)init;

@end

FOUNDATION_EXPORT BOOL JavaxXmlTransformStreamFilePathToURI_initialized;
J2OBJC_STATIC_INIT(JavaxXmlTransformStreamFilePathToURI)

FOUNDATION_EXPORT IOSBooleanArray *JavaxXmlTransformStreamFilePathToURI_gNeedEscaping_;
J2OBJC_STATIC_FIELD_GETTER(JavaxXmlTransformStreamFilePathToURI, gNeedEscaping_, IOSBooleanArray *)
J2OBJC_STATIC_FIELD_SETTER(JavaxXmlTransformStreamFilePathToURI, gNeedEscaping_, IOSBooleanArray *)

FOUNDATION_EXPORT IOSCharArray *JavaxXmlTransformStreamFilePathToURI_gAfterEscaping1_;
J2OBJC_STATIC_FIELD_GETTER(JavaxXmlTransformStreamFilePathToURI, gAfterEscaping1_, IOSCharArray *)
J2OBJC_STATIC_FIELD_SETTER(JavaxXmlTransformStreamFilePathToURI, gAfterEscaping1_, IOSCharArray *)

FOUNDATION_EXPORT IOSCharArray *JavaxXmlTransformStreamFilePathToURI_gAfterEscaping2_;
J2OBJC_STATIC_FIELD_GETTER(JavaxXmlTransformStreamFilePathToURI, gAfterEscaping2_, IOSCharArray *)
J2OBJC_STATIC_FIELD_SETTER(JavaxXmlTransformStreamFilePathToURI, gAfterEscaping2_, IOSCharArray *)

FOUNDATION_EXPORT IOSCharArray *JavaxXmlTransformStreamFilePathToURI_gHexChs_;
J2OBJC_STATIC_FIELD_GETTER(JavaxXmlTransformStreamFilePathToURI, gHexChs_, IOSCharArray *)
J2OBJC_STATIC_FIELD_SETTER(JavaxXmlTransformStreamFilePathToURI, gHexChs_, IOSCharArray *)

#endif // _JavaxXmlTransformStreamFilePathToURI_H_
