//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/xml/transform/stream/StreamResult.java
//

#ifndef _JavaxXmlTransformStreamStreamResult_H_
#define _JavaxXmlTransformStreamStreamResult_H_

@class JavaIoFile;
@class JavaIoOutputStream;
@class JavaIoWriter;

#import "JreEmulation.h"
#include "javax/xml/transform/Result.h"

@interface JavaxXmlTransformStreamStreamResult : NSObject < JavaxXmlTransformResult > {
 @public
  NSString *systemId_;
  JavaIoOutputStream *outputStream_;
  JavaIoWriter *writer_;
}

- (instancetype)init;

- (instancetype)initWithJavaIoOutputStream:(JavaIoOutputStream *)outputStream;

- (instancetype)initWithJavaIoWriter:(JavaIoWriter *)writer;

- (instancetype)initWithNSString:(NSString *)systemId;

- (instancetype)initWithJavaIoFile:(JavaIoFile *)f;

- (void)setOutputStreamWithJavaIoOutputStream:(JavaIoOutputStream *)outputStream;

- (JavaIoOutputStream *)getOutputStream;

- (void)setWriterWithJavaIoWriter:(JavaIoWriter *)writer;

- (JavaIoWriter *)getWriter;

- (void)setSystemIdWithNSString:(NSString *)systemId;

- (void)setSystemIdWithJavaIoFile:(JavaIoFile *)f;

- (NSString *)getSystemId;

- (void)copyAllFieldsTo:(JavaxXmlTransformStreamStreamResult *)other;

@end

__attribute__((always_inline)) inline void JavaxXmlTransformStreamStreamResult_init() {}

J2OBJC_FIELD_SETTER(JavaxXmlTransformStreamStreamResult, systemId_, NSString *)
J2OBJC_FIELD_SETTER(JavaxXmlTransformStreamStreamResult, outputStream_, JavaIoOutputStream *)
J2OBJC_FIELD_SETTER(JavaxXmlTransformStreamStreamResult, writer_, JavaIoWriter *)

FOUNDATION_EXPORT NSString *JavaxXmlTransformStreamStreamResult_FEATURE_;
J2OBJC_STATIC_FIELD_GETTER(JavaxXmlTransformStreamStreamResult, FEATURE_, NSString *)

#endif // _JavaxXmlTransformStreamStreamResult_H_
