//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/AlgorithmParameters.java
//

#ifndef _JavaSecurityAlgorithmParameters_H_
#define _JavaSecurityAlgorithmParameters_H_

@class IOSByteArray;
@class IOSClass;
@class JavaSecurityAlgorithmParametersSpi;
@class JavaSecurityProvider;
@class OrgApacheHarmonySecurityFortressEngine;
@protocol JavaSecuritySpecAlgorithmParameterSpec;

#import "JreEmulation.h"

@interface JavaSecurityAlgorithmParameters : NSObject {
 @public
  JavaSecurityProvider *provider_;
  JavaSecurityAlgorithmParametersSpi *spiImpl_;
  NSString *algorithm_;
  jboolean initialized_;
}

- (instancetype)initWithJavaSecurityAlgorithmParametersSpi:(JavaSecurityAlgorithmParametersSpi *)algPramSpi
                                  withJavaSecurityProvider:(JavaSecurityProvider *)provider
                                              withNSString:(NSString *)algorithm;

+ (JavaSecurityAlgorithmParameters *)getInstanceWithNSString:(NSString *)algorithm;

+ (JavaSecurityAlgorithmParameters *)getInstanceWithNSString:(NSString *)algorithm
                                                withNSString:(NSString *)provider;

+ (JavaSecurityAlgorithmParameters *)getInstanceWithNSString:(NSString *)algorithm
                                    withJavaSecurityProvider:(JavaSecurityProvider *)provider;

- (JavaSecurityProvider *)getProvider;

- (NSString *)getAlgorithm;

- (void)init__WithJavaSecuritySpecAlgorithmParameterSpec:(id<JavaSecuritySpecAlgorithmParameterSpec>)paramSpec OBJC_METHOD_FAMILY_NONE;

- (void)init__WithByteArray:(IOSByteArray *)params OBJC_METHOD_FAMILY_NONE;

- (void)init__WithByteArray:(IOSByteArray *)params
               withNSString:(NSString *)format OBJC_METHOD_FAMILY_NONE;

- (id)getParameterSpecWithIOSClass:(IOSClass *)paramSpec;

- (IOSByteArray *)getEncoded;

- (IOSByteArray *)getEncodedWithNSString:(NSString *)format;

- (NSString *)description;

- (void)copyAllFieldsTo:(JavaSecurityAlgorithmParameters *)other;

@end

FOUNDATION_EXPORT BOOL JavaSecurityAlgorithmParameters_initialized;
J2OBJC_STATIC_INIT(JavaSecurityAlgorithmParameters)

J2OBJC_FIELD_SETTER(JavaSecurityAlgorithmParameters, provider_, JavaSecurityProvider *)
J2OBJC_FIELD_SETTER(JavaSecurityAlgorithmParameters, spiImpl_, JavaSecurityAlgorithmParametersSpi *)
J2OBJC_FIELD_SETTER(JavaSecurityAlgorithmParameters, algorithm_, NSString *)

FOUNDATION_EXPORT NSString *JavaSecurityAlgorithmParameters_SEVICE_;
J2OBJC_STATIC_FIELD_GETTER(JavaSecurityAlgorithmParameters, SEVICE_, NSString *)

FOUNDATION_EXPORT OrgApacheHarmonySecurityFortressEngine *JavaSecurityAlgorithmParameters_ENGINE_;
J2OBJC_STATIC_FIELD_GETTER(JavaSecurityAlgorithmParameters, ENGINE_, OrgApacheHarmonySecurityFortressEngine *)

#endif // _JavaSecurityAlgorithmParameters_H_
