//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/AlgorithmParameterGeneratorSpi.java
//

#ifndef _JavaSecurityAlgorithmParameterGeneratorSpi_H_
#define _JavaSecurityAlgorithmParameterGeneratorSpi_H_

@class JavaSecurityAlgorithmParameters;
@class JavaSecuritySecureRandom;
@protocol JavaSecuritySpecAlgorithmParameterSpec;

#import "JreEmulation.h"

@interface JavaSecurityAlgorithmParameterGeneratorSpi : NSObject {
}

- (instancetype)init;

- (void)engineInitWithInt:(jint)size
withJavaSecuritySecureRandom:(JavaSecuritySecureRandom *)random;

- (void)engineInitWithJavaSecuritySpecAlgorithmParameterSpec:(id<JavaSecuritySpecAlgorithmParameterSpec>)genParamSpec
                                withJavaSecuritySecureRandom:(JavaSecuritySecureRandom *)random;

- (JavaSecurityAlgorithmParameters *)engineGenerateParameters;

@end

__attribute__((always_inline)) inline void JavaSecurityAlgorithmParameterGeneratorSpi_init() {}

#endif // _JavaSecurityAlgorithmParameterGeneratorSpi_H_
