//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/AlgorithmParameterGenerator.java
//

#ifndef _JavaSecurityAlgorithmParameterGenerator_H_
#define _JavaSecurityAlgorithmParameterGenerator_H_

@class JavaSecurityAlgorithmParameterGeneratorSpi;
@class JavaSecurityAlgorithmParameters;
@class JavaSecurityProvider;
@class JavaSecuritySecureRandom;
@class OrgApacheHarmonySecurityFortressEngine;
@protocol JavaSecuritySpecAlgorithmParameterSpec;

#import "JreEmulation.h"

@interface JavaSecurityAlgorithmParameterGenerator : NSObject {
 @public
  JavaSecurityProvider *provider_;
  JavaSecurityAlgorithmParameterGeneratorSpi *spiImpl_;
  NSString *algorithm_;
}

- (instancetype)initWithJavaSecurityAlgorithmParameterGeneratorSpi:(JavaSecurityAlgorithmParameterGeneratorSpi *)paramGenSpi
                                          withJavaSecurityProvider:(JavaSecurityProvider *)provider
                                                      withNSString:(NSString *)algorithm;

- (NSString *)getAlgorithm;

+ (JavaSecurityAlgorithmParameterGenerator *)getInstanceWithNSString:(NSString *)algorithm;

+ (JavaSecurityAlgorithmParameterGenerator *)getInstanceWithNSString:(NSString *)algorithm
                                                        withNSString:(NSString *)provider;

+ (JavaSecurityAlgorithmParameterGenerator *)getInstanceWithNSString:(NSString *)algorithm
                                            withJavaSecurityProvider:(JavaSecurityProvider *)provider;

- (JavaSecurityProvider *)getProvider;

- (void)init__WithInt:(jint)size OBJC_METHOD_FAMILY_NONE;

- (void)init__WithInt:(jint)size
withJavaSecuritySecureRandom:(JavaSecuritySecureRandom *)random OBJC_METHOD_FAMILY_NONE;

- (void)init__WithJavaSecuritySpecAlgorithmParameterSpec:(id<JavaSecuritySpecAlgorithmParameterSpec>)genParamSpec OBJC_METHOD_FAMILY_NONE;

- (void)init__WithJavaSecuritySpecAlgorithmParameterSpec:(id<JavaSecuritySpecAlgorithmParameterSpec>)genParamSpec
                            withJavaSecuritySecureRandom:(JavaSecuritySecureRandom *)random OBJC_METHOD_FAMILY_NONE;

- (JavaSecurityAlgorithmParameters *)generateParameters;

- (void)copyAllFieldsTo:(JavaSecurityAlgorithmParameterGenerator *)other;

@end

FOUNDATION_EXPORT BOOL JavaSecurityAlgorithmParameterGenerator_initialized;
J2OBJC_STATIC_INIT(JavaSecurityAlgorithmParameterGenerator)

J2OBJC_FIELD_SETTER(JavaSecurityAlgorithmParameterGenerator, provider_, JavaSecurityProvider *)
J2OBJC_FIELD_SETTER(JavaSecurityAlgorithmParameterGenerator, spiImpl_, JavaSecurityAlgorithmParameterGeneratorSpi *)
J2OBJC_FIELD_SETTER(JavaSecurityAlgorithmParameterGenerator, algorithm_, NSString *)

FOUNDATION_EXPORT NSString *JavaSecurityAlgorithmParameterGenerator_SERVICE_;
J2OBJC_STATIC_FIELD_GETTER(JavaSecurityAlgorithmParameterGenerator, SERVICE_, NSString *)

FOUNDATION_EXPORT OrgApacheHarmonySecurityFortressEngine *JavaSecurityAlgorithmParameterGenerator_ENGINE_;
J2OBJC_STATIC_FIELD_GETTER(JavaSecurityAlgorithmParameterGenerator, ENGINE_, OrgApacheHarmonySecurityFortressEngine *)

FOUNDATION_EXPORT JavaSecuritySecureRandom *JavaSecurityAlgorithmParameterGenerator_RANDOM_;
J2OBJC_STATIC_FIELD_GETTER(JavaSecurityAlgorithmParameterGenerator, RANDOM_, JavaSecuritySecureRandom *)

#endif // _JavaSecurityAlgorithmParameterGenerator_H_
