//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/AlgorithmParametersSpi.java
//

#ifndef _JavaSecurityAlgorithmParametersSpi_H_
#define _JavaSecurityAlgorithmParametersSpi_H_

@class IOSByteArray;
@class IOSClass;
@protocol JavaSecuritySpecAlgorithmParameterSpec;

#import "JreEmulation.h"

@interface JavaSecurityAlgorithmParametersSpi : NSObject {
}

- (void)engineInitWithJavaSecuritySpecAlgorithmParameterSpec:(id<JavaSecuritySpecAlgorithmParameterSpec>)paramSpec;

- (void)engineInitWithByteArray:(IOSByteArray *)params;

- (void)engineInitWithByteArray:(IOSByteArray *)params
                   withNSString:(NSString *)format;

- (id)engineGetParameterSpecWithIOSClass:(IOSClass *)paramSpec;

- (IOSByteArray *)engineGetEncoded;

- (IOSByteArray *)engineGetEncodedWithNSString:(NSString *)format;

- (NSString *)engineToString;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void JavaSecurityAlgorithmParametersSpi_init() {}

#endif // _JavaSecurityAlgorithmParametersSpi_H_
