//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/AuthProvider.java
//

#ifndef _JavaSecurityAuthProvider_H_
#define _JavaSecurityAuthProvider_H_

#include "J2ObjC_header.h"
#include "java/security/Provider.h"

@class JavaxSecurityAuthSubject;
@protocol JavaxSecurityAuthCallbackCallbackHandler;

@interface JavaSecurityAuthProvider : JavaSecurityProvider

#pragma mark Public

- (void)loginWithJavaxSecurityAuthSubject:(JavaxSecurityAuthSubject *)subject
withJavaxSecurityAuthCallbackCallbackHandler:(id<JavaxSecurityAuthCallbackCallbackHandler>)handler;

- (void)logout;

- (void)setCallbackHandlerWithJavaxSecurityAuthCallbackCallbackHandler:(id<JavaxSecurityAuthCallbackCallbackHandler>)handler;

#pragma mark Protected

- (instancetype)initWithNSString:(NSString *)name
                      withDouble:(jdouble)version_
                    withNSString:(NSString *)info;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaSecurityAuthProvider)

FOUNDATION_EXPORT void JavaSecurityAuthProvider_initWithNSString_withDouble_withNSString_(JavaSecurityAuthProvider *self, NSString *name, jdouble version_, NSString *info);

J2OBJC_TYPE_LITERAL_HEADER(JavaSecurityAuthProvider)

#endif // _JavaSecurityAuthProvider_H_
