//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/AuthProvider.java
//

#ifndef _JavaSecurityAuthProvider_H_
#define _JavaSecurityAuthProvider_H_

@class JavaxSecurityAuthSubject;
@protocol JavaxSecurityAuthCallbackCallbackHandler;

#import "JreEmulation.h"
#include "java/security/Provider.h"

@interface JavaSecurityAuthProvider : JavaSecurityProvider {
}

- (instancetype)initWithNSString:(NSString *)name
                      withDouble:(jdouble)version_
                    withNSString:(NSString *)info;

- (void)loginWithJavaxSecurityAuthSubject:(JavaxSecurityAuthSubject *)subject
withJavaxSecurityAuthCallbackCallbackHandler:(id<JavaxSecurityAuthCallbackCallbackHandler>)handler;

- (void)logout;

- (void)setCallbackHandlerWithJavaxSecurityAuthCallbackCallbackHandler:(id<JavaxSecurityAuthCallbackCallbackHandler>)handler;

@end

__attribute__((always_inline)) inline void JavaSecurityAuthProvider_init() {}

#endif // _JavaSecurityAuthProvider_H_
