//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/Certificate.java
//

#ifndef _JavaSecurityCertificate_H_
#define _JavaSecurityCertificate_H_

#include "J2ObjC_header.h"

@class JavaIoInputStream;
@class JavaIoOutputStream;
@protocol JavaSecurityPrincipal;
@protocol JavaSecurityPublicKey;

@protocol JavaSecurityCertificate < NSObject, JavaObject >

- (void)decodeWithJavaIoInputStream:(JavaIoInputStream *)stream;

- (void)encodeWithJavaIoOutputStream:(JavaIoOutputStream *)stream;

- (NSString *)getFormat;

- (id<JavaSecurityPrincipal>)getGuarantor;

- (id<JavaSecurityPrincipal>)getPrincipal;

- (id<JavaSecurityPublicKey>)getPublicKey;

- (NSString *)toStringWithBoolean:(jboolean)detailed;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaSecurityCertificate)

J2OBJC_TYPE_LITERAL_HEADER(JavaSecurityCertificate)

#endif // _JavaSecurityCertificate_H_
