//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/Certificate.java
//

#ifndef _JavaSecurityCertificate_H_
#define _JavaSecurityCertificate_H_

@class JavaIoInputStream;
@class JavaIoOutputStream;
@protocol JavaSecurityPrincipal;
@protocol JavaSecurityPublicKey;

#import "JreEmulation.h"

@protocol JavaSecurityCertificate < NSObject, JavaObject >

- (void)decodeWithJavaIoInputStream:(JavaIoInputStream *)stream;

- (void)encodeWithJavaIoOutputStream:(JavaIoOutputStream *)stream;

- (NSString *)getFormat;

- (id<JavaSecurityPrincipal>)getGuarantor;

- (id<JavaSecurityPrincipal>)getPrincipal;

- (id<JavaSecurityPublicKey>)getPublicKey;

- (NSString *)toStringWithBoolean:(jboolean)detailed;

@end

__attribute__((always_inline)) inline void JavaSecurityCertificate_init() {}

#endif // _JavaSecurityCertificate_H_
