//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/CodeSigner.java
//

#ifndef _JavaSecurityCodeSigner_H_
#define _JavaSecurityCodeSigner_H_

@class JavaSecurityCertCertPath;
@class JavaSecurityTimestamp;

#import "JreEmulation.h"
#include "java/io/Serializable.h"

#define JavaSecurityCodeSigner_serialVersionUID 6819288105193937581LL

@interface JavaSecurityCodeSigner : NSObject < JavaIoSerializable > {
 @public
  JavaSecurityCertCertPath *signerCertPath_;
  JavaSecurityTimestamp *timestamp_;
  jint hash__;
}

- (instancetype)initWithJavaSecurityCertCertPath:(JavaSecurityCertCertPath *)signerCertPath
                       withJavaSecurityTimestamp:(JavaSecurityTimestamp *)timestamp;

- (jboolean)isEqual:(id)obj;

- (JavaSecurityCertCertPath *)getSignerCertPath;

- (JavaSecurityTimestamp *)getTimestamp;

- (NSUInteger)hash;

- (NSString *)description;

- (void)copyAllFieldsTo:(JavaSecurityCodeSigner *)other;

@end

__attribute__((always_inline)) inline void JavaSecurityCodeSigner_init() {}

J2OBJC_FIELD_SETTER(JavaSecurityCodeSigner, signerCertPath_, JavaSecurityCertCertPath *)
J2OBJC_FIELD_SETTER(JavaSecurityCodeSigner, timestamp_, JavaSecurityTimestamp *)

J2OBJC_STATIC_FIELD_GETTER(JavaSecurityCodeSigner, serialVersionUID, jlong)

#endif // _JavaSecurityCodeSigner_H_
