//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/CodeSigner.java
//

#ifndef _JavaSecurityCodeSigner_H_
#define _JavaSecurityCodeSigner_H_

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"

@class JavaSecurityCertCertPath;
@class JavaSecurityTimestamp;

@interface JavaSecurityCodeSigner : NSObject < JavaIoSerializable >

#pragma mark Public

- (instancetype)initWithJavaSecurityCertCertPath:(JavaSecurityCertCertPath *)signerCertPath
                       withJavaSecurityTimestamp:(JavaSecurityTimestamp *)timestamp;

- (jboolean)isEqual:(id)obj;

- (JavaSecurityCertCertPath *)getSignerCertPath;

- (JavaSecurityTimestamp *)getTimestamp;

- (NSUInteger)hash;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaSecurityCodeSigner)

FOUNDATION_EXPORT void JavaSecurityCodeSigner_initWithJavaSecurityCertCertPath_withJavaSecurityTimestamp_(JavaSecurityCodeSigner *self, JavaSecurityCertCertPath *signerCertPath, JavaSecurityTimestamp *timestamp);

FOUNDATION_EXPORT JavaSecurityCodeSigner *new_JavaSecurityCodeSigner_initWithJavaSecurityCertCertPath_withJavaSecurityTimestamp_(JavaSecurityCertCertPath *signerCertPath, JavaSecurityTimestamp *timestamp) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaSecurityCodeSigner)

#endif // _JavaSecurityCodeSigner_H_
