//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/DigestInputStream.java
//

#ifndef _JavaSecurityDigestInputStream_H_
#define _JavaSecurityDigestInputStream_H_

#include "J2ObjC_header.h"
#include "java/io/FilterInputStream.h"

@class IOSByteArray;
@class JavaIoInputStream;
@class JavaSecurityMessageDigest;

@interface JavaSecurityDigestInputStream : JavaIoFilterInputStream {
 @public
  JavaSecurityMessageDigest *digest_;
}

#pragma mark Public

- (instancetype)initWithJavaIoInputStream:(JavaIoInputStream *)stream
            withJavaSecurityMessageDigest:(JavaSecurityMessageDigest *)digest;

- (JavaSecurityMessageDigest *)getMessageDigest;

- (void)onWithBoolean:(jboolean)on;

- (jint)read;

- (jint)readWithByteArray:(IOSByteArray *)buffer
                  withInt:(jint)byteOffset
                  withInt:(jint)byteCount;

- (void)setMessageDigestWithJavaSecurityMessageDigest:(JavaSecurityMessageDigest *)digest;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaSecurityDigestInputStream)

J2OBJC_FIELD_SETTER(JavaSecurityDigestInputStream, digest_, JavaSecurityMessageDigest *)

FOUNDATION_EXPORT void JavaSecurityDigestInputStream_initWithJavaIoInputStream_withJavaSecurityMessageDigest_(JavaSecurityDigestInputStream *self, JavaIoInputStream *stream, JavaSecurityMessageDigest *digest);

FOUNDATION_EXPORT JavaSecurityDigestInputStream *new_JavaSecurityDigestInputStream_initWithJavaIoInputStream_withJavaSecurityMessageDigest_(JavaIoInputStream *stream, JavaSecurityMessageDigest *digest) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaSecurityDigestInputStream)

#endif // _JavaSecurityDigestInputStream_H_
