//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/DigestInputStream.java
//

#ifndef _JavaSecurityDigestInputStream_H_
#define _JavaSecurityDigestInputStream_H_

@class IOSByteArray;
@class JavaIoInputStream;
@class JavaSecurityMessageDigest;

#import "JreEmulation.h"
#include "java/io/FilterInputStream.h"

@interface JavaSecurityDigestInputStream : JavaIoFilterInputStream {
 @public
  JavaSecurityMessageDigest *digest_;
  jboolean isOn_;
}

- (instancetype)initWithJavaIoInputStream:(JavaIoInputStream *)stream
            withJavaSecurityMessageDigest:(JavaSecurityMessageDigest *)digest;

- (JavaSecurityMessageDigest *)getMessageDigest;

- (void)setMessageDigestWithJavaSecurityMessageDigest:(JavaSecurityMessageDigest *)digest;

- (jint)read;

- (jint)readWithByteArray:(IOSByteArray *)buffer
                  withInt:(jint)byteOffset
                  withInt:(jint)byteCount;

- (void)onWithBoolean:(jboolean)on;

- (NSString *)description;

- (void)copyAllFieldsTo:(JavaSecurityDigestInputStream *)other;

@end

__attribute__((always_inline)) inline void JavaSecurityDigestInputStream_init() {}

J2OBJC_FIELD_SETTER(JavaSecurityDigestInputStream, digest_, JavaSecurityMessageDigest *)

#endif // _JavaSecurityDigestInputStream_H_
