//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/Identity.java
//

#ifndef _JavaSecurityIdentity_H_
#define _JavaSecurityIdentity_H_

@class IOSObjectArray;
@class JavaSecurityIdentityScope;
@class JavaUtilVector;
@protocol JavaSecurityCertificate;
@protocol JavaSecurityPublicKey;

#import "JreEmulation.h"
#include "java/io/Serializable.h"
#include "java/security/Principal.h"

#define JavaSecurityIdentity_serialVersionUID 3609922007826600659LL

@interface JavaSecurityIdentity : NSObject < JavaSecurityPrincipal, JavaIoSerializable > {
 @public
  NSString *name_;
  id<JavaSecurityPublicKey> publicKey_;
  NSString *info_;
  JavaSecurityIdentityScope *scope_;
  JavaUtilVector *certificates__;
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)name;

- (instancetype)initWithNSString:(NSString *)name
   withJavaSecurityIdentityScope:(JavaSecurityIdentityScope *)scope;

- (void)addCertificateWithJavaSecurityCertificate:(id<JavaSecurityCertificate>)certificate;

+ (jboolean)checkKeysEqualWithJavaSecurityPublicKey:(id<JavaSecurityPublicKey>)pk1
                          withJavaSecurityPublicKey:(id<JavaSecurityPublicKey>)pk2;

- (void)removeCertificateWithJavaSecurityCertificate:(id<JavaSecurityCertificate>)certificate;

- (IOSObjectArray *)certificates;

- (jboolean)identityEqualsWithJavaSecurityIdentity:(JavaSecurityIdentity *)identity;

- (NSString *)toStringWithBoolean:(jboolean)detailed;

- (JavaSecurityIdentityScope *)getScope;

- (void)setPublicKeyWithJavaSecurityPublicKey:(id<JavaSecurityPublicKey>)key;

- (id<JavaSecurityPublicKey>)getPublicKey;

- (void)setInfoWithNSString:(NSString *)info;

- (NSString *)getInfo;

- (jboolean)isEqual:(id)obj;

- (NSString *)getName;

- (NSUInteger)hash;

- (NSString *)description;

- (void)copyAllFieldsTo:(JavaSecurityIdentity *)other;

@end

__attribute__((always_inline)) inline void JavaSecurityIdentity_init() {}

J2OBJC_FIELD_SETTER(JavaSecurityIdentity, name_, NSString *)
J2OBJC_FIELD_SETTER(JavaSecurityIdentity, publicKey_, id<JavaSecurityPublicKey>)
J2OBJC_FIELD_SETTER(JavaSecurityIdentity, info_, NSString *)
J2OBJC_FIELD_SETTER(JavaSecurityIdentity, scope_, JavaSecurityIdentityScope *)
J2OBJC_FIELD_SETTER(JavaSecurityIdentity, certificates__, JavaUtilVector *)

J2OBJC_STATIC_FIELD_GETTER(JavaSecurityIdentity, serialVersionUID, jlong)

#endif // _JavaSecurityIdentity_H_
