//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/IdentityScope.java
//

#ifndef _JavaSecurityIdentityScope_H_
#define _JavaSecurityIdentityScope_H_

@protocol JavaSecurityPrincipal;
@protocol JavaSecurityPublicKey;
@protocol JavaUtilEnumeration;

#import "JreEmulation.h"
#include "java/security/Identity.h"

#define JavaSecurityIdentityScope_serialVersionUID -2337346281189773310LL

@interface JavaSecurityIdentityScope : JavaSecurityIdentity {
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)name;

- (instancetype)initWithNSString:(NSString *)name
   withJavaSecurityIdentityScope:(JavaSecurityIdentityScope *)scope;

+ (JavaSecurityIdentityScope *)getSystemScope;

+ (void)setSystemScopeWithJavaSecurityIdentityScope:(JavaSecurityIdentityScope *)scope;

- (jint)size;

- (JavaSecurityIdentity *)getIdentityWithNSString:(NSString *)name;

- (JavaSecurityIdentity *)getIdentityWithJavaSecurityPrincipal:(id<JavaSecurityPrincipal>)principal;

- (JavaSecurityIdentity *)getIdentityWithJavaSecurityPublicKey:(id<JavaSecurityPublicKey>)key;

- (void)addIdentityWithJavaSecurityIdentity:(JavaSecurityIdentity *)identity;

- (void)removeIdentityWithJavaSecurityIdentity:(JavaSecurityIdentity *)identity;

- (id<JavaUtilEnumeration>)identities;

- (NSString *)description;

@end

__attribute__((always_inline)) inline void JavaSecurityIdentityScope_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaSecurityIdentityScope, serialVersionUID, jlong)

FOUNDATION_EXPORT JavaSecurityIdentityScope *JavaSecurityIdentityScope_systemScope_;
J2OBJC_STATIC_FIELD_GETTER(JavaSecurityIdentityScope, systemScope_, JavaSecurityIdentityScope *)
J2OBJC_STATIC_FIELD_SETTER(JavaSecurityIdentityScope, systemScope_, JavaSecurityIdentityScope *)

#endif // _JavaSecurityIdentityScope_H_
