//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/Identity.java
//

#ifndef _JavaSecurityIdentity_H_
#define _JavaSecurityIdentity_H_

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"
#include "java/security/Principal.h"

@class IOSObjectArray;
@class JavaSecurityIdentityScope;
@protocol JavaSecurityCertificate;
@protocol JavaSecurityPublicKey;

@interface JavaSecurityIdentity : NSObject < JavaSecurityPrincipal, JavaIoSerializable >

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)name;

- (instancetype)initWithNSString:(NSString *)name
   withJavaSecurityIdentityScope:(JavaSecurityIdentityScope *)scope;

- (void)addCertificateWithJavaSecurityCertificate:(id<JavaSecurityCertificate>)certificate;

- (IOSObjectArray *)certificates;

- (jboolean)isEqual:(id)obj;

- (NSString *)getInfo;

- (NSString *)getName;

- (id<JavaSecurityPublicKey>)getPublicKey;

- (JavaSecurityIdentityScope *)getScope;

- (NSUInteger)hash;

- (void)removeCertificateWithJavaSecurityCertificate:(id<JavaSecurityCertificate>)certificate;

- (void)setInfoWithNSString:(NSString *)info;

- (void)setPublicKeyWithJavaSecurityPublicKey:(id<JavaSecurityPublicKey>)key;

- (NSString *)description;

- (NSString *)toStringWithBoolean:(jboolean)detailed;

#pragma mark Protected

- (instancetype)init;

- (jboolean)identityEqualsWithJavaSecurityIdentity:(JavaSecurityIdentity *)identity;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaSecurityIdentity)

FOUNDATION_EXPORT void JavaSecurityIdentity_init(JavaSecurityIdentity *self);

FOUNDATION_EXPORT void JavaSecurityIdentity_initWithNSString_(JavaSecurityIdentity *self, NSString *name);

FOUNDATION_EXPORT void JavaSecurityIdentity_initWithNSString_withJavaSecurityIdentityScope_(JavaSecurityIdentity *self, NSString *name, JavaSecurityIdentityScope *scope);

J2OBJC_TYPE_LITERAL_HEADER(JavaSecurityIdentity)

#endif // _JavaSecurityIdentity_H_
