//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/InvalidAlgorithmParameterException.java
//

#ifndef _JavaSecurityInvalidAlgorithmParameterException_H_
#define _JavaSecurityInvalidAlgorithmParameterException_H_

@class JavaLangThrowable;

#import "JreEmulation.h"
#include "java/security/GeneralSecurityException.h"

#define JavaSecurityInvalidAlgorithmParameterException_serialVersionUID 2864672297499471472LL

@interface JavaSecurityInvalidAlgorithmParameterException : JavaSecurityGeneralSecurityException {
}

- (instancetype)initWithNSString:(NSString *)msg;

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)message
           withJavaLangThrowable:(JavaLangThrowable *)cause;

- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)cause;

@end

__attribute__((always_inline)) inline void JavaSecurityInvalidAlgorithmParameterException_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaSecurityInvalidAlgorithmParameterException, serialVersionUID, jlong)

#endif // _JavaSecurityInvalidAlgorithmParameterException_H_
