//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/KeyFactory.java
//

#ifndef _JavaSecurityKeyFactory_H_
#define _JavaSecurityKeyFactory_H_

@class IOSClass;
@class JavaSecurityKeyFactorySpi;
@class JavaSecurityProvider;
@class OrgApacheHarmonySecurityFortressEngine;
@protocol JavaSecurityKey;
@protocol JavaSecurityPrivateKey;
@protocol JavaSecurityPublicKey;
@protocol JavaSecuritySpecKeySpec;

#import "JreEmulation.h"

@interface JavaSecurityKeyFactory : NSObject {
 @public
  JavaSecurityProvider *provider_;
  JavaSecurityKeyFactorySpi *spiImpl_;
  NSString *algorithm_;
}

- (instancetype)initWithJavaSecurityKeyFactorySpi:(JavaSecurityKeyFactorySpi *)keyFacSpi
                         withJavaSecurityProvider:(JavaSecurityProvider *)provider
                                     withNSString:(NSString *)algorithm;

+ (JavaSecurityKeyFactory *)getInstanceWithNSString:(NSString *)algorithm;

+ (JavaSecurityKeyFactory *)getInstanceWithNSString:(NSString *)algorithm
                                       withNSString:(NSString *)provider;

+ (JavaSecurityKeyFactory *)getInstanceWithNSString:(NSString *)algorithm
                           withJavaSecurityProvider:(JavaSecurityProvider *)provider;

- (JavaSecurityProvider *)getProvider;

- (NSString *)getAlgorithm;

- (id<JavaSecurityPublicKey>)generatePublicWithJavaSecuritySpecKeySpec:(id<JavaSecuritySpecKeySpec>)keySpec;

- (id<JavaSecurityPrivateKey>)generatePrivateWithJavaSecuritySpecKeySpec:(id<JavaSecuritySpecKeySpec>)keySpec;

- (id)getKeySpecWithJavaSecurityKey:(id<JavaSecurityKey>)key
                       withIOSClass:(IOSClass *)keySpec;

- (id<JavaSecurityKey>)translateKeyWithJavaSecurityKey:(id<JavaSecurityKey>)key;

- (void)copyAllFieldsTo:(JavaSecurityKeyFactory *)other;

@end

FOUNDATION_EXPORT BOOL JavaSecurityKeyFactory_initialized;
J2OBJC_STATIC_INIT(JavaSecurityKeyFactory)

J2OBJC_FIELD_SETTER(JavaSecurityKeyFactory, provider_, JavaSecurityProvider *)
J2OBJC_FIELD_SETTER(JavaSecurityKeyFactory, spiImpl_, JavaSecurityKeyFactorySpi *)
J2OBJC_FIELD_SETTER(JavaSecurityKeyFactory, algorithm_, NSString *)

FOUNDATION_EXPORT NSString *JavaSecurityKeyFactory_SERVICE_;
J2OBJC_STATIC_FIELD_GETTER(JavaSecurityKeyFactory, SERVICE_, NSString *)

FOUNDATION_EXPORT OrgApacheHarmonySecurityFortressEngine *JavaSecurityKeyFactory_ENGINE_;
J2OBJC_STATIC_FIELD_GETTER(JavaSecurityKeyFactory, ENGINE_, OrgApacheHarmonySecurityFortressEngine *)

#endif // _JavaSecurityKeyFactory_H_
