//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/KeyFactorySpi.java
//

#ifndef _JavaSecurityKeyFactorySpi_H_
#define _JavaSecurityKeyFactorySpi_H_

@class IOSClass;
@protocol JavaSecurityKey;
@protocol JavaSecurityPrivateKey;
@protocol JavaSecurityPublicKey;
@protocol JavaSecuritySpecKeySpec;

#import "JreEmulation.h"

@interface JavaSecurityKeyFactorySpi : NSObject {
}

- (id<JavaSecurityPublicKey>)engineGeneratePublicWithJavaSecuritySpecKeySpec:(id<JavaSecuritySpecKeySpec>)keySpec;

- (id<JavaSecurityPrivateKey>)engineGeneratePrivateWithJavaSecuritySpecKeySpec:(id<JavaSecuritySpecKeySpec>)keySpec;

- (id)engineGetKeySpecWithJavaSecurityKey:(id<JavaSecurityKey>)key
                             withIOSClass:(IOSClass *)keySpec;

- (id<JavaSecurityKey>)engineTranslateKeyWithJavaSecurityKey:(id<JavaSecurityKey>)key;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void JavaSecurityKeyFactorySpi_init() {}

#endif // _JavaSecurityKeyFactorySpi_H_
