//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/KeyPair.java
//

#ifndef _JavaSecurityKeyPair_H_
#define _JavaSecurityKeyPair_H_

@protocol JavaSecurityPrivateKey;
@protocol JavaSecurityPublicKey;

#import "JreEmulation.h"
#include "java/io/Serializable.h"

#define JavaSecurityKeyPair_serialVersionUID -7565189502268009837LL

@interface JavaSecurityKeyPair : NSObject < JavaIoSerializable > {
 @public
  id<JavaSecurityPrivateKey> privateKey_;
  id<JavaSecurityPublicKey> publicKey_;
}

- (instancetype)initWithJavaSecurityPublicKey:(id<JavaSecurityPublicKey>)publicKey
                   withJavaSecurityPrivateKey:(id<JavaSecurityPrivateKey>)privateKey;

- (id<JavaSecurityPrivateKey>)getPrivate;

- (id<JavaSecurityPublicKey>)getPublic;

- (void)copyAllFieldsTo:(JavaSecurityKeyPair *)other;

@end

__attribute__((always_inline)) inline void JavaSecurityKeyPair_init() {}

J2OBJC_FIELD_SETTER(JavaSecurityKeyPair, privateKey_, id<JavaSecurityPrivateKey>)
J2OBJC_FIELD_SETTER(JavaSecurityKeyPair, publicKey_, id<JavaSecurityPublicKey>)

J2OBJC_STATIC_FIELD_GETTER(JavaSecurityKeyPair, serialVersionUID, jlong)

#endif // _JavaSecurityKeyPair_H_
