//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/KeyPairGeneratorSpi.java
//

#ifndef _JavaSecurityKeyPairGeneratorSpi_H_
#define _JavaSecurityKeyPairGeneratorSpi_H_

@class JavaSecurityKeyPair;
@class JavaSecuritySecureRandom;
@protocol JavaSecuritySpecAlgorithmParameterSpec;

#import "JreEmulation.h"

@interface JavaSecurityKeyPairGeneratorSpi : NSObject {
}

- (instancetype)init;

- (JavaSecurityKeyPair *)generateKeyPair;

- (void)initialize__WithInt:(jint)keysize
withJavaSecuritySecureRandom:(JavaSecuritySecureRandom *)random OBJC_METHOD_FAMILY_NONE;

- (void)initialize__WithJavaSecuritySpecAlgorithmParameterSpec:(id<JavaSecuritySpecAlgorithmParameterSpec>)params
                                  withJavaSecuritySecureRandom:(JavaSecuritySecureRandom *)random OBJC_METHOD_FAMILY_NONE;

@end

__attribute__((always_inline)) inline void JavaSecurityKeyPairGeneratorSpi_init() {}

#endif // _JavaSecurityKeyPairGeneratorSpi_H_
