//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/KeyPairGenerator.java
//

#ifndef _JavaSecurityKeyPairGenerator_H_
#define _JavaSecurityKeyPairGenerator_H_

@class JavaSecurityKeyPair;
@class JavaSecurityProvider;
@class JavaSecuritySecureRandom;
@class OrgApacheHarmonySecurityFortressEngine;
@protocol JavaSecuritySpecAlgorithmParameterSpec;

#import "JreEmulation.h"
#include "java/security/KeyPairGeneratorSpi.h"

@interface JavaSecurityKeyPairGenerator : JavaSecurityKeyPairGeneratorSpi {
 @public
  JavaSecurityProvider *provider_;
  NSString *algorithm_;
}

- (instancetype)initWithNSString:(NSString *)algorithm;

- (NSString *)getAlgorithm;

+ (JavaSecurityKeyPairGenerator *)getInstanceWithNSString:(NSString *)algorithm;

+ (JavaSecurityKeyPairGenerator *)getInstanceWithNSString:(NSString *)algorithm
                                             withNSString:(NSString *)provider;

+ (JavaSecurityKeyPairGenerator *)getInstanceWithNSString:(NSString *)algorithm
                                 withJavaSecurityProvider:(JavaSecurityProvider *)provider;

- (JavaSecurityProvider *)getProvider;

- (void)initialize__WithInt:(jint)keysize OBJC_METHOD_FAMILY_NONE;

- (void)initialize__WithJavaSecuritySpecAlgorithmParameterSpec:(id<JavaSecuritySpecAlgorithmParameterSpec>)param OBJC_METHOD_FAMILY_NONE;

- (JavaSecurityKeyPair *)genKeyPair;

- (JavaSecurityKeyPair *)generateKeyPair;

- (void)initialize__WithInt:(jint)keysize
withJavaSecuritySecureRandom:(JavaSecuritySecureRandom *)random OBJC_METHOD_FAMILY_NONE;

- (void)initialize__WithJavaSecuritySpecAlgorithmParameterSpec:(id<JavaSecuritySpecAlgorithmParameterSpec>)param
                                  withJavaSecuritySecureRandom:(JavaSecuritySecureRandom *)random OBJC_METHOD_FAMILY_NONE;

- (void)copyAllFieldsTo:(JavaSecurityKeyPairGenerator *)other;

@end

FOUNDATION_EXPORT BOOL JavaSecurityKeyPairGenerator_initialized;
J2OBJC_STATIC_INIT(JavaSecurityKeyPairGenerator)

J2OBJC_FIELD_SETTER(JavaSecurityKeyPairGenerator, provider_, JavaSecurityProvider *)
J2OBJC_FIELD_SETTER(JavaSecurityKeyPairGenerator, algorithm_, NSString *)

FOUNDATION_EXPORT NSString *JavaSecurityKeyPairGenerator_SERVICE_;
J2OBJC_STATIC_FIELD_GETTER(JavaSecurityKeyPairGenerator, SERVICE_, NSString *)

FOUNDATION_EXPORT OrgApacheHarmonySecurityFortressEngine *JavaSecurityKeyPairGenerator_ENGINE_;
J2OBJC_STATIC_FIELD_GETTER(JavaSecurityKeyPairGenerator, ENGINE_, OrgApacheHarmonySecurityFortressEngine *)

FOUNDATION_EXPORT JavaSecuritySecureRandom *JavaSecurityKeyPairGenerator_RANDOM_;
J2OBJC_STATIC_FIELD_GETTER(JavaSecurityKeyPairGenerator, RANDOM_, JavaSecuritySecureRandom *)

@interface JavaSecurityKeyPairGenerator_KeyPairGeneratorImpl : JavaSecurityKeyPairGenerator {
 @public
  JavaSecurityKeyPairGeneratorSpi *spiImpl_;
}

- (instancetype)initWithJavaSecurityKeyPairGeneratorSpi:(JavaSecurityKeyPairGeneratorSpi *)keyPairGeneratorSpi
                               withJavaSecurityProvider:(JavaSecurityProvider *)provider
                                           withNSString:(NSString *)algorithm;

- (void)initialize__WithInt:(jint)keysize
withJavaSecuritySecureRandom:(JavaSecuritySecureRandom *)random OBJC_METHOD_FAMILY_NONE;

- (JavaSecurityKeyPair *)generateKeyPair;

- (void)initialize__WithJavaSecuritySpecAlgorithmParameterSpec:(id<JavaSecuritySpecAlgorithmParameterSpec>)param
                                  withJavaSecuritySecureRandom:(JavaSecuritySecureRandom *)random OBJC_METHOD_FAMILY_NONE;

- (void)copyAllFieldsTo:(JavaSecurityKeyPairGenerator_KeyPairGeneratorImpl *)other;

@end

__attribute__((always_inline)) inline void JavaSecurityKeyPairGenerator_KeyPairGeneratorImpl_init() {}

J2OBJC_FIELD_SETTER(JavaSecurityKeyPairGenerator_KeyPairGeneratorImpl, spiImpl_, JavaSecurityKeyPairGeneratorSpi *)

#endif // _JavaSecurityKeyPairGenerator_H_
