//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/KeyRep.java
//

#ifndef _JavaSecurityKeyRep_H_
#define _JavaSecurityKeyRep_H_

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"
#include "java/lang/Enum.h"

@class IOSByteArray;
@class JavaSecurityKeyRep_TypeEnum;

@interface JavaSecurityKeyRep : NSObject < JavaIoSerializable >

#pragma mark Public

- (instancetype)initWithJavaSecurityKeyRep_TypeEnum:(JavaSecurityKeyRep_TypeEnum *)type
                                       withNSString:(NSString *)algorithm
                                       withNSString:(NSString *)format
                                      withByteArray:(IOSByteArray *)encoded;

#pragma mark Protected

- (id)readResolve;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaSecurityKeyRep)

FOUNDATION_EXPORT void JavaSecurityKeyRep_initWithJavaSecurityKeyRep_TypeEnum_withNSString_withNSString_withByteArray_(JavaSecurityKeyRep *self, JavaSecurityKeyRep_TypeEnum *type, NSString *algorithm, NSString *format, IOSByteArray *encoded);

FOUNDATION_EXPORT JavaSecurityKeyRep *new_JavaSecurityKeyRep_initWithJavaSecurityKeyRep_TypeEnum_withNSString_withNSString_withByteArray_(JavaSecurityKeyRep_TypeEnum *type, NSString *algorithm, NSString *format, IOSByteArray *encoded) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaSecurityKeyRep)

typedef NS_ENUM(NSUInteger, JavaSecurityKeyRep_Type) {
  JavaSecurityKeyRep_Type_SECRET = 0,
  JavaSecurityKeyRep_Type_PUBLIC = 1,
  JavaSecurityKeyRep_Type_PRIVATE = 2,
};

@interface JavaSecurityKeyRep_TypeEnum : JavaLangEnum < NSCopying >

#pragma mark Package-Private

+ (IOSObjectArray *)values;
FOUNDATION_EXPORT IOSObjectArray *JavaSecurityKeyRep_TypeEnum_values();

+ (JavaSecurityKeyRep_TypeEnum *)valueOfWithNSString:(NSString *)name;
FOUNDATION_EXPORT JavaSecurityKeyRep_TypeEnum *JavaSecurityKeyRep_TypeEnum_valueOfWithNSString_(NSString *name);

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(JavaSecurityKeyRep_TypeEnum)

FOUNDATION_EXPORT JavaSecurityKeyRep_TypeEnum *JavaSecurityKeyRep_TypeEnum_values_[];

#define JavaSecurityKeyRep_TypeEnum_SECRET JavaSecurityKeyRep_TypeEnum_values_[JavaSecurityKeyRep_Type_SECRET]
J2OBJC_ENUM_CONSTANT_GETTER(JavaSecurityKeyRep_TypeEnum, SECRET)

#define JavaSecurityKeyRep_TypeEnum_PUBLIC JavaSecurityKeyRep_TypeEnum_values_[JavaSecurityKeyRep_Type_PUBLIC]
J2OBJC_ENUM_CONSTANT_GETTER(JavaSecurityKeyRep_TypeEnum, PUBLIC)

#define JavaSecurityKeyRep_TypeEnum_PRIVATE JavaSecurityKeyRep_TypeEnum_values_[JavaSecurityKeyRep_Type_PRIVATE]
J2OBJC_ENUM_CONSTANT_GETTER(JavaSecurityKeyRep_TypeEnum, PRIVATE)

J2OBJC_TYPE_LITERAL_HEADER(JavaSecurityKeyRep_TypeEnum)

#endif // _JavaSecurityKeyRep_H_
