//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/KeyStore.java
//

#ifndef _JavaSecurityKeyStore_H_
#define _JavaSecurityKeyStore_H_

@class IOSByteArray;
@class IOSCharArray;
@class IOSClass;
@class IOSObjectArray;
@class JavaIoFile;
@class JavaIoInputStream;
@class JavaIoOutputStream;
@class JavaSecurityCertCertificate;
@class JavaSecurityKeyStoreException;
@class JavaSecurityKeyStoreSpi;
@class JavaSecurityProvider;
@class JavaUtilDate;
@class OrgApacheHarmonySecurityFortressEngine;
@protocol JavaSecurityKey;
@protocol JavaSecurityKeyStore_Entry;
@protocol JavaSecurityKeyStore_LoadStoreParameter;
@protocol JavaSecurityKeyStore_ProtectionParameter;
@protocol JavaSecurityPrivateKey;
@protocol JavaUtilEnumeration;
@protocol JavaxCryptoSecretKey;
@protocol JavaxSecurityAuthCallbackCallbackHandler;

#import "JreEmulation.h"
#include "javax/security/auth/Destroyable.h"

@interface JavaSecurityKeyStore : NSObject {
 @public
  jboolean isInit_;
  JavaSecurityKeyStoreSpi *implSpi_;
  JavaSecurityProvider *provider_;
  NSString *type_;
}

- (instancetype)initWithJavaSecurityKeyStoreSpi:(JavaSecurityKeyStoreSpi *)keyStoreSpi
                       withJavaSecurityProvider:(JavaSecurityProvider *)provider
                                   withNSString:(NSString *)type;

+ (void)throwNotInitialized;

+ (JavaSecurityKeyStore *)getInstanceWithNSString:(NSString *)type;

+ (JavaSecurityKeyStore *)getInstanceWithNSString:(NSString *)type
                                     withNSString:(NSString *)provider;

+ (JavaSecurityKeyStore *)getInstanceWithNSString:(NSString *)type
                         withJavaSecurityProvider:(JavaSecurityProvider *)provider;

+ (NSString *)getDefaultType;

- (JavaSecurityProvider *)getProvider;

- (NSString *)getType;

- (id<JavaSecurityKey>)getKeyWithNSString:(NSString *)alias
                            withCharArray:(IOSCharArray *)password;

- (IOSObjectArray *)getCertificateChainWithNSString:(NSString *)alias;

- (JavaSecurityCertCertificate *)getCertificateWithNSString:(NSString *)alias;

- (JavaUtilDate *)getCreationDateWithNSString:(NSString *)alias;

- (void)setKeyEntryWithNSString:(NSString *)alias
            withJavaSecurityKey:(id<JavaSecurityKey>)key
                  withCharArray:(IOSCharArray *)password
withJavaSecurityCertCertificateArray:(IOSObjectArray *)chain;

- (void)setKeyEntryWithNSString:(NSString *)alias
                  withByteArray:(IOSByteArray *)key
withJavaSecurityCertCertificateArray:(IOSObjectArray *)chain;

- (void)setCertificateEntryWithNSString:(NSString *)alias
        withJavaSecurityCertCertificate:(JavaSecurityCertCertificate *)cert;

- (void)deleteEntryWithNSString:(NSString *)alias;

- (id<JavaUtilEnumeration>)aliases;

- (jboolean)containsAliasWithNSString:(NSString *)alias;

- (jint)size;

- (jboolean)isKeyEntryWithNSString:(NSString *)alias;

- (jboolean)isCertificateEntryWithNSString:(NSString *)alias;

- (NSString *)getCertificateAliasWithJavaSecurityCertCertificate:(JavaSecurityCertCertificate *)cert;

- (void)storeWithJavaIoOutputStream:(JavaIoOutputStream *)stream
                      withCharArray:(IOSCharArray *)password;

- (void)storeWithJavaSecurityKeyStore_LoadStoreParameter:(id<JavaSecurityKeyStore_LoadStoreParameter>)param;

- (void)load__WithJavaIoInputStream:(JavaIoInputStream *)stream
                      withCharArray:(IOSCharArray *)password;

- (void)load__WithJavaSecurityKeyStore_LoadStoreParameter:(id<JavaSecurityKeyStore_LoadStoreParameter>)param;

- (id<JavaSecurityKeyStore_Entry>)getEntryWithNSString:(NSString *)alias
          withJavaSecurityKeyStore_ProtectionParameter:(id<JavaSecurityKeyStore_ProtectionParameter>)param;

- (void)setEntryWithNSString:(NSString *)alias
withJavaSecurityKeyStore_Entry:(id<JavaSecurityKeyStore_Entry>)entry_
withJavaSecurityKeyStore_ProtectionParameter:(id<JavaSecurityKeyStore_ProtectionParameter>)param;

- (jboolean)entryInstanceOfWithNSString:(NSString *)alias
                           withIOSClass:(IOSClass *)entryClass;

- (void)copyAllFieldsTo:(JavaSecurityKeyStore *)other;

@end

FOUNDATION_EXPORT BOOL JavaSecurityKeyStore_initialized;
J2OBJC_STATIC_INIT(JavaSecurityKeyStore)

J2OBJC_FIELD_SETTER(JavaSecurityKeyStore, implSpi_, JavaSecurityKeyStoreSpi *)
J2OBJC_FIELD_SETTER(JavaSecurityKeyStore, provider_, JavaSecurityProvider *)
J2OBJC_FIELD_SETTER(JavaSecurityKeyStore, type_, NSString *)

FOUNDATION_EXPORT NSString *JavaSecurityKeyStore_SERVICE_;
J2OBJC_STATIC_FIELD_GETTER(JavaSecurityKeyStore, SERVICE_, NSString *)

FOUNDATION_EXPORT OrgApacheHarmonySecurityFortressEngine *JavaSecurityKeyStore_ENGINE_;
J2OBJC_STATIC_FIELD_GETTER(JavaSecurityKeyStore, ENGINE_, OrgApacheHarmonySecurityFortressEngine *)

FOUNDATION_EXPORT NSString *JavaSecurityKeyStore_PROPERTY_NAME_;
J2OBJC_STATIC_FIELD_GETTER(JavaSecurityKeyStore, PROPERTY_NAME_, NSString *)

FOUNDATION_EXPORT NSString *JavaSecurityKeyStore_DEFAULT_KEYSTORE_TYPE_;
J2OBJC_STATIC_FIELD_GETTER(JavaSecurityKeyStore, DEFAULT_KEYSTORE_TYPE_, NSString *)

@interface JavaSecurityKeyStore_Builder : NSObject {
}

- (instancetype)init;

- (JavaSecurityKeyStore *)getKeyStore;

- (id<JavaSecurityKeyStore_ProtectionParameter>)getProtectionParameterWithNSString:(NSString *)alias;

+ (JavaSecurityKeyStore_Builder *)newInstanceWithJavaSecurityKeyStore:(JavaSecurityKeyStore *)keyStore
                         withJavaSecurityKeyStore_ProtectionParameter:(id<JavaSecurityKeyStore_ProtectionParameter>)protectionParameter OBJC_METHOD_FAMILY_NONE;

+ (JavaSecurityKeyStore_Builder *)newInstanceWithNSString:(NSString *)type
                                 withJavaSecurityProvider:(JavaSecurityProvider *)provider
                                           withJavaIoFile:(JavaIoFile *)file
             withJavaSecurityKeyStore_ProtectionParameter:(id<JavaSecurityKeyStore_ProtectionParameter>)protectionParameter OBJC_METHOD_FAMILY_NONE;

+ (JavaSecurityKeyStore_Builder *)newInstanceWithNSString:(NSString *)type
                                 withJavaSecurityProvider:(JavaSecurityProvider *)provider
             withJavaSecurityKeyStore_ProtectionParameter:(id<JavaSecurityKeyStore_ProtectionParameter>)protectionParameter OBJC_METHOD_FAMILY_NONE;

@end

__attribute__((always_inline)) inline void JavaSecurityKeyStore_Builder_init() {}

@interface JavaSecurityKeyStore_Builder_BuilderImpl : JavaSecurityKeyStore_Builder {
 @public
  JavaSecurityKeyStore *keyStore_;
  id<JavaSecurityKeyStore_ProtectionParameter> protParameter_;
  NSString *typeForKeyStore_;
  JavaSecurityProvider *providerForKeyStore_;
  JavaIoFile *fileForLoad_;
  jboolean isGetKeyStore_;
  JavaSecurityKeyStoreException *lastException_;
}

- (instancetype)initWithJavaSecurityKeyStore:(JavaSecurityKeyStore *)ks
withJavaSecurityKeyStore_ProtectionParameter:(id<JavaSecurityKeyStore_ProtectionParameter>)pp
                              withJavaIoFile:(JavaIoFile *)file
                                withNSString:(NSString *)type
                    withJavaSecurityProvider:(JavaSecurityProvider *)provider;

- (JavaSecurityKeyStore *)getKeyStore;

- (id<JavaSecurityKeyStore_ProtectionParameter>)getProtectionParameterWithNSString:(NSString *)alias;

- (void)copyAllFieldsTo:(JavaSecurityKeyStore_Builder_BuilderImpl *)other;

@end

__attribute__((always_inline)) inline void JavaSecurityKeyStore_Builder_BuilderImpl_init() {}

J2OBJC_FIELD_SETTER(JavaSecurityKeyStore_Builder_BuilderImpl, keyStore_, JavaSecurityKeyStore *)
J2OBJC_FIELD_SETTER(JavaSecurityKeyStore_Builder_BuilderImpl, protParameter_, id<JavaSecurityKeyStore_ProtectionParameter>)
J2OBJC_FIELD_SETTER(JavaSecurityKeyStore_Builder_BuilderImpl, typeForKeyStore_, NSString *)
J2OBJC_FIELD_SETTER(JavaSecurityKeyStore_Builder_BuilderImpl, providerForKeyStore_, JavaSecurityProvider *)
J2OBJC_FIELD_SETTER(JavaSecurityKeyStore_Builder_BuilderImpl, fileForLoad_, JavaIoFile *)
J2OBJC_FIELD_SETTER(JavaSecurityKeyStore_Builder_BuilderImpl, lastException_, JavaSecurityKeyStoreException *)

@protocol JavaSecurityKeyStore_LoadStoreParameter < NSObject, JavaObject >

- (id<JavaSecurityKeyStore_ProtectionParameter>)getProtectionParameter;

@end

__attribute__((always_inline)) inline void JavaSecurityKeyStore_LoadStoreParameter_init() {}

@interface JavaSecurityKeyStore_Builder_TmpLSParameter : NSObject < JavaSecurityKeyStore_LoadStoreParameter > {
 @public
  id<JavaSecurityKeyStore_ProtectionParameter> protPar_;
}

- (instancetype)initWithJavaSecurityKeyStore_ProtectionParameter:(id<JavaSecurityKeyStore_ProtectionParameter>)protPar;

- (id<JavaSecurityKeyStore_ProtectionParameter>)getProtectionParameter;

- (void)copyAllFieldsTo:(JavaSecurityKeyStore_Builder_TmpLSParameter *)other;

@end

__attribute__((always_inline)) inline void JavaSecurityKeyStore_Builder_TmpLSParameter_init() {}

J2OBJC_FIELD_SETTER(JavaSecurityKeyStore_Builder_TmpLSParameter, protPar_, id<JavaSecurityKeyStore_ProtectionParameter>)

@protocol JavaSecurityKeyStore_ProtectionParameter < NSObject, JavaObject >

@end

__attribute__((always_inline)) inline void JavaSecurityKeyStore_ProtectionParameter_init() {}

@interface JavaSecurityKeyStore_CallbackHandlerProtection : NSObject < JavaSecurityKeyStore_ProtectionParameter > {
 @public
  id<JavaxSecurityAuthCallbackCallbackHandler> callbackHandler_;
}

- (instancetype)initWithJavaxSecurityAuthCallbackCallbackHandler:(id<JavaxSecurityAuthCallbackCallbackHandler>)handler;

- (id<JavaxSecurityAuthCallbackCallbackHandler>)getCallbackHandler;

- (void)copyAllFieldsTo:(JavaSecurityKeyStore_CallbackHandlerProtection *)other;

@end

__attribute__((always_inline)) inline void JavaSecurityKeyStore_CallbackHandlerProtection_init() {}

J2OBJC_FIELD_SETTER(JavaSecurityKeyStore_CallbackHandlerProtection, callbackHandler_, id<JavaxSecurityAuthCallbackCallbackHandler>)

@interface JavaSecurityKeyStore_PasswordProtection : NSObject < JavaSecurityKeyStore_ProtectionParameter, JavaxSecurityAuthDestroyable > {
 @public
  IOSCharArray *password_;
  jboolean isDestroyed__;
}

- (instancetype)initWithCharArray:(IOSCharArray *)password;

- (IOSCharArray *)getPassword;

- (void)destroy;

- (jboolean)isDestroyed;

- (void)copyAllFieldsTo:(JavaSecurityKeyStore_PasswordProtection *)other;

@end

__attribute__((always_inline)) inline void JavaSecurityKeyStore_PasswordProtection_init() {}

J2OBJC_FIELD_SETTER(JavaSecurityKeyStore_PasswordProtection, password_, IOSCharArray *)

@protocol JavaSecurityKeyStore_Entry < NSObject, JavaObject >

@end

__attribute__((always_inline)) inline void JavaSecurityKeyStore_Entry_init() {}

@interface JavaSecurityKeyStore_PrivateKeyEntry : NSObject < JavaSecurityKeyStore_Entry > {
 @public
  IOSObjectArray *chain_;
  id<JavaSecurityPrivateKey> privateKey_;
}

- (instancetype)initWithJavaSecurityPrivateKey:(id<JavaSecurityPrivateKey>)privateKey
          withJavaSecurityCertCertificateArray:(IOSObjectArray *)chain;

- (id<JavaSecurityPrivateKey>)getPrivateKey;

- (IOSObjectArray *)getCertificateChain;

- (JavaSecurityCertCertificate *)getCertificate;

- (NSString *)description;

- (void)copyAllFieldsTo:(JavaSecurityKeyStore_PrivateKeyEntry *)other;

@end

__attribute__((always_inline)) inline void JavaSecurityKeyStore_PrivateKeyEntry_init() {}

J2OBJC_FIELD_SETTER(JavaSecurityKeyStore_PrivateKeyEntry, chain_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(JavaSecurityKeyStore_PrivateKeyEntry, privateKey_, id<JavaSecurityPrivateKey>)

@interface JavaSecurityKeyStore_SecretKeyEntry : NSObject < JavaSecurityKeyStore_Entry > {
 @public
  id<JavaxCryptoSecretKey> secretKey_;
}

- (instancetype)initWithJavaxCryptoSecretKey:(id<JavaxCryptoSecretKey>)secretKey;

- (id<JavaxCryptoSecretKey>)getSecretKey;

- (NSString *)description;

- (void)copyAllFieldsTo:(JavaSecurityKeyStore_SecretKeyEntry *)other;

@end

__attribute__((always_inline)) inline void JavaSecurityKeyStore_SecretKeyEntry_init() {}

J2OBJC_FIELD_SETTER(JavaSecurityKeyStore_SecretKeyEntry, secretKey_, id<JavaxCryptoSecretKey>)

@interface JavaSecurityKeyStore_TrustedCertificateEntry : NSObject < JavaSecurityKeyStore_Entry > {
 @public
  JavaSecurityCertCertificate *trustCertificate_;
}

- (instancetype)initWithJavaSecurityCertCertificate:(JavaSecurityCertCertificate *)trustCertificate;

- (JavaSecurityCertCertificate *)getTrustedCertificate;

- (NSString *)description;

- (void)copyAllFieldsTo:(JavaSecurityKeyStore_TrustedCertificateEntry *)other;

@end

__attribute__((always_inline)) inline void JavaSecurityKeyStore_TrustedCertificateEntry_init() {}

J2OBJC_FIELD_SETTER(JavaSecurityKeyStore_TrustedCertificateEntry, trustCertificate_, JavaSecurityCertCertificate *)

#endif // _JavaSecurityKeyStore_H_
