//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/KeyStoreSpi.java
//

#ifndef _JavaSecurityKeyStoreSpi_H_
#define _JavaSecurityKeyStoreSpi_H_

@class IOSByteArray;
@class IOSCharArray;
@class IOSClass;
@class IOSObjectArray;
@class JavaIoInputStream;
@class JavaIoOutputStream;
@class JavaSecurityCertCertificate;
@class JavaUtilDate;
@protocol JavaSecurityKey;
@protocol JavaSecurityKeyStore_Entry;
@protocol JavaSecurityKeyStore_LoadStoreParameter;
@protocol JavaSecurityKeyStore_ProtectionParameter;
@protocol JavaUtilEnumeration;

#import "JreEmulation.h"

@interface JavaSecurityKeyStoreSpi : NSObject {
}

- (id<JavaSecurityKey>)engineGetKeyWithNSString:(NSString *)alias
                                  withCharArray:(IOSCharArray *)password;

- (IOSObjectArray *)engineGetCertificateChainWithNSString:(NSString *)alias;

- (JavaSecurityCertCertificate *)engineGetCertificateWithNSString:(NSString *)alias;

- (JavaUtilDate *)engineGetCreationDateWithNSString:(NSString *)alias;

- (void)engineSetKeyEntryWithNSString:(NSString *)alias
                  withJavaSecurityKey:(id<JavaSecurityKey>)key
                        withCharArray:(IOSCharArray *)password
 withJavaSecurityCertCertificateArray:(IOSObjectArray *)chain;

- (void)engineSetKeyEntryWithNSString:(NSString *)alias
                        withByteArray:(IOSByteArray *)key
 withJavaSecurityCertCertificateArray:(IOSObjectArray *)chain;

- (void)engineSetCertificateEntryWithNSString:(NSString *)alias
              withJavaSecurityCertCertificate:(JavaSecurityCertCertificate *)cert;

- (void)engineDeleteEntryWithNSString:(NSString *)alias;

- (id<JavaUtilEnumeration>)engineAliases;

- (jboolean)engineContainsAliasWithNSString:(NSString *)alias;

- (jint)engineSize;

- (jboolean)engineIsKeyEntryWithNSString:(NSString *)alias;

- (jboolean)engineIsCertificateEntryWithNSString:(NSString *)alias;

- (NSString *)engineGetCertificateAliasWithJavaSecurityCertCertificate:(JavaSecurityCertCertificate *)cert;

- (void)engineStoreWithJavaIoOutputStream:(JavaIoOutputStream *)stream
                            withCharArray:(IOSCharArray *)password;

- (void)engineStoreWithJavaSecurityKeyStore_LoadStoreParameter:(id<JavaSecurityKeyStore_LoadStoreParameter>)param;

- (void)engineLoadWithJavaIoInputStream:(JavaIoInputStream *)stream
                          withCharArray:(IOSCharArray *)password;

- (void)engineLoadWithJavaSecurityKeyStore_LoadStoreParameter:(id<JavaSecurityKeyStore_LoadStoreParameter>)param;

- (id<JavaSecurityKeyStore_Entry>)engineGetEntryWithNSString:(NSString *)alias
                withJavaSecurityKeyStore_ProtectionParameter:(id<JavaSecurityKeyStore_ProtectionParameter>)protParam;

- (void)engineSetEntryWithNSString:(NSString *)alias
    withJavaSecurityKeyStore_Entry:(id<JavaSecurityKeyStore_Entry>)entry_
withJavaSecurityKeyStore_ProtectionParameter:(id<JavaSecurityKeyStore_ProtectionParameter>)protParam;

- (jboolean)engineEntryInstanceOfWithNSString:(NSString *)alias
                                 withIOSClass:(IOSClass *)entryClass;

+ (IOSCharArray *)getPasswordFromCallBackWithJavaSecurityKeyStore_ProtectionParameter:(id<JavaSecurityKeyStore_ProtectionParameter>)protParam;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void JavaSecurityKeyStoreSpi_init() {}

#endif // _JavaSecurityKeyStoreSpi_H_
