//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/KeyStoreException.java
//

#ifndef _JavaSecurityKeyStoreException_H_
#define _JavaSecurityKeyStoreException_H_

@class JavaLangThrowable;

#import "JreEmulation.h"
#include "java/security/GeneralSecurityException.h"

#define JavaSecurityKeyStoreException_serialVersionUID -1119353179322377262LL

@interface JavaSecurityKeyStoreException : JavaSecurityGeneralSecurityException {
}

- (instancetype)initWithNSString:(NSString *)msg;

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)message
           withJavaLangThrowable:(JavaLangThrowable *)cause;

- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)cause;

@end

__attribute__((always_inline)) inline void JavaSecurityKeyStoreException_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaSecurityKeyStoreException, serialVersionUID, jlong)

#endif // _JavaSecurityKeyStoreException_H_
