//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/PolicySpi.java
//

#ifndef _JavaSecurityPolicySpi_H_
#define _JavaSecurityPolicySpi_H_

@class JavaSecurityCodeSource;
@class JavaSecurityPermission;
@class JavaSecurityPermissionCollection;
@class JavaSecurityProtectionDomain;

#import "JreEmulation.h"

@interface JavaSecurityPolicySpi : NSObject {
}

- (instancetype)init;

- (jboolean)engineImpliesWithJavaSecurityProtectionDomain:(JavaSecurityProtectionDomain *)domain
                               withJavaSecurityPermission:(JavaSecurityPermission *)permission;

- (void)engineRefresh;

- (JavaSecurityPermissionCollection *)engineGetPermissionsWithJavaSecurityCodeSource:(JavaSecurityCodeSource *)codesource;

- (JavaSecurityPermissionCollection *)engineGetPermissionsWithJavaSecurityProtectionDomain:(JavaSecurityProtectionDomain *)domain;

@end

__attribute__((always_inline)) inline void JavaSecurityPolicySpi_init() {}

#endif // _JavaSecurityPolicySpi_H_
