//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/PolicySpi.java
//

#ifndef _JavaSecurityPolicySpi_H_
#define _JavaSecurityPolicySpi_H_

#include "J2ObjC_header.h"

@class JavaSecurityCodeSource;
@class JavaSecurityPermission;
@class JavaSecurityPermissionCollection;
@class JavaSecurityProtectionDomain;

@interface JavaSecurityPolicySpi : NSObject

#pragma mark Public

- (instancetype)init;

#pragma mark Protected

- (JavaSecurityPermissionCollection *)engineGetPermissionsWithJavaSecurityCodeSource:(JavaSecurityCodeSource *)codesource;

- (JavaSecurityPermissionCollection *)engineGetPermissionsWithJavaSecurityProtectionDomain:(JavaSecurityProtectionDomain *)domain;

- (jboolean)engineImpliesWithJavaSecurityProtectionDomain:(JavaSecurityProtectionDomain *)domain
                               withJavaSecurityPermission:(JavaSecurityPermission *)permission;

- (void)engineRefresh;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaSecurityPolicySpi)

FOUNDATION_EXPORT void JavaSecurityPolicySpi_init(JavaSecurityPolicySpi *self);

J2OBJC_TYPE_LITERAL_HEADER(JavaSecurityPolicySpi)

#endif // _JavaSecurityPolicySpi_H_
