//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/PrivateKey.java
//

#ifndef _JavaSecurityPrivateKey_H_
#define _JavaSecurityPrivateKey_H_

#import "JreEmulation.h"
#include "java/security/Key.h"

#define JavaSecurityPrivateKey_serialVersionUID 6034044314589513430LL

@protocol JavaSecurityPrivateKey < JavaSecurityKey, NSObject, JavaObject >
@end

__attribute__((always_inline)) inline void JavaSecurityPrivateKey_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaSecurityPrivateKey, serialVersionUID, jlong)

#endif // _JavaSecurityPrivateKey_H_
