//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/ProviderException.java
//

#ifndef _JavaSecurityProviderException_H_
#define _JavaSecurityProviderException_H_

@class JavaLangThrowable;

#import "JreEmulation.h"
#include "java/lang/RuntimeException.h"

#define JavaSecurityProviderException_serialVersionUID 5256023526693665674LL

@interface JavaSecurityProviderException : JavaLangRuntimeException {
}

- (instancetype)initWithNSString:(NSString *)msg;

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)message
           withJavaLangThrowable:(JavaLangThrowable *)cause;

- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)cause;

@end

__attribute__((always_inline)) inline void JavaSecurityProviderException_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaSecurityProviderException, serialVersionUID, jlong)

#endif // _JavaSecurityProviderException_H_
