//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/SignatureSpi.java
//

#ifndef _JavaSecuritySignatureSpi_H_
#define _JavaSecuritySignatureSpi_H_

@class IOSByteArray;
@class JavaNioByteBuffer;
@class JavaSecurityAlgorithmParameters;
@class JavaSecuritySecureRandom;
@protocol JavaSecurityPrivateKey;
@protocol JavaSecurityPublicKey;
@protocol JavaSecuritySpecAlgorithmParameterSpec;

#import "JreEmulation.h"

@interface JavaSecuritySignatureSpi : NSObject {
 @public
  JavaSecuritySecureRandom *appRandom_;
}

- (void)engineInitVerifyWithJavaSecurityPublicKey:(id<JavaSecurityPublicKey>)publicKey;

- (void)engineInitSignWithJavaSecurityPrivateKey:(id<JavaSecurityPrivateKey>)privateKey;

- (void)engineInitSignWithJavaSecurityPrivateKey:(id<JavaSecurityPrivateKey>)privateKey
                    withJavaSecuritySecureRandom:(JavaSecuritySecureRandom *)random;

- (void)engineUpdateWithByte:(jbyte)b;

- (void)engineUpdateWithByteArray:(IOSByteArray *)b
                          withInt:(jint)off
                          withInt:(jint)len;

- (void)engineUpdateWithJavaNioByteBuffer:(JavaNioByteBuffer *)input;

- (IOSByteArray *)engineSign;

- (jint)engineSignWithByteArray:(IOSByteArray *)outbuf
                        withInt:(jint)offset
                        withInt:(jint)len;

- (jboolean)engineVerifyWithByteArray:(IOSByteArray *)sigBytes;

- (jboolean)engineVerifyWithByteArray:(IOSByteArray *)sigBytes
                              withInt:(jint)offset
                              withInt:(jint)length;

- (void)engineSetParameterWithNSString:(NSString *)param
                                withId:(id)value;

- (void)engineSetParameterWithJavaSecuritySpecAlgorithmParameterSpec:(id<JavaSecuritySpecAlgorithmParameterSpec>)params;

- (JavaSecurityAlgorithmParameters *)engineGetParameters;

- (id)engineGetParameterWithNSString:(NSString *)param;

- (id)clone;

- (instancetype)init;

- (void)copyAllFieldsTo:(JavaSecuritySignatureSpi *)other;

@end

__attribute__((always_inline)) inline void JavaSecuritySignatureSpi_init() {}

J2OBJC_FIELD_SETTER(JavaSecuritySignatureSpi, appRandom_, JavaSecuritySecureRandom *)

#endif // _JavaSecuritySignatureSpi_H_
