//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/Signature.java
//

#ifndef _JavaSecuritySignature_H_
#define _JavaSecuritySignature_H_

@class IOSByteArray;
@class JavaNioByteBuffer;
@class JavaSecurityAlgorithmParameters;
@class JavaSecurityCertCertificate;
@class JavaSecurityProvider;
@class JavaSecurityProvider_Service;
@class JavaSecuritySecureRandom;
@class OrgApacheHarmonySecurityFortressEngine;
@class OrgApacheHarmonySecurityFortressEngine_SpiAndProvider;
@protocol JavaSecurityKey;
@protocol JavaSecurityPrivateKey;
@protocol JavaSecurityPublicKey;
@protocol JavaSecuritySpecAlgorithmParameterSpec;

#import "JreEmulation.h"
#include "java/security/SignatureSpi.h"

#define JavaSecuritySignature_SIGN 2
#define JavaSecuritySignature_UNINITIALIZED 0
#define JavaSecuritySignature_VERIFY 3

@interface JavaSecuritySignature : JavaSecuritySignatureSpi {
 @public
  JavaSecurityProvider *provider_;
  NSString *algorithm_;
  jint state_;
}

- (instancetype)initWithNSString:(NSString *)algorithm;

+ (JavaSecuritySignature *)getInstanceWithNSString:(NSString *)algorithm;

+ (JavaSecuritySignature *)getInstanceWithNSString:(NSString *)algorithm
                                      withNSString:(NSString *)provider;

+ (JavaSecuritySignature *)getInstanceWithNSString:(NSString *)algorithm
                          withJavaSecurityProvider:(JavaSecurityProvider *)provider;

+ (JavaSecuritySignature *)getSignatureWithNSString:(NSString *)algorithm
                           withJavaSecurityProvider:(JavaSecurityProvider *)provider;

+ (OrgApacheHarmonySecurityFortressEngine_SpiAndProvider *)tryAlgorithmWithJavaSecurityKey:(id<JavaSecurityKey>)key
                                                                  withJavaSecurityProvider:(JavaSecurityProvider *)provider
                                                                              withNSString:(NSString *)algorithm;

+ (OrgApacheHarmonySecurityFortressEngine_SpiAndProvider *)tryAlgorithmWithProviderWithJavaSecurityKey:(id<JavaSecurityKey>)key
                                                                      withJavaSecurityProvider_Service:(JavaSecurityProvider_Service *)service;

- (JavaSecurityProvider *)getProvider;

- (void)ensureProviderChosen;

- (NSString *)getAlgorithm;

- (void)initVerifyWithJavaSecurityPublicKey:(id<JavaSecurityPublicKey>)publicKey OBJC_METHOD_FAMILY_NONE;

- (void)initVerifyWithJavaSecurityCertCertificate:(JavaSecurityCertCertificate *)certificate OBJC_METHOD_FAMILY_NONE;

- (void)initSignWithJavaSecurityPrivateKey:(id<JavaSecurityPrivateKey>)privateKey OBJC_METHOD_FAMILY_NONE;

- (void)initSignWithJavaSecurityPrivateKey:(id<JavaSecurityPrivateKey>)privateKey
              withJavaSecuritySecureRandom:(JavaSecuritySecureRandom *)random OBJC_METHOD_FAMILY_NONE;

- (IOSByteArray *)sign;

- (jint)signWithByteArray:(IOSByteArray *)outbuf
                  withInt:(jint)offset
                  withInt:(jint)len;

- (jboolean)verifyWithByteArray:(IOSByteArray *)signature;

- (jboolean)verifyWithByteArray:(IOSByteArray *)signature
                        withInt:(jint)offset
                        withInt:(jint)length;

- (void)updateWithByte:(jbyte)b;

- (void)updateWithByteArray:(IOSByteArray *)data;

- (void)updateWithByteArray:(IOSByteArray *)data
                    withInt:(jint)off
                    withInt:(jint)len;

- (void)updateWithJavaNioByteBuffer:(JavaNioByteBuffer *)data;

- (NSString *)description;

- (NSString *)stateToStringWithInt:(jint)state;

- (void)setParameterWithNSString:(NSString *)param
                          withId:(id)value;

- (void)setParameterWithJavaSecuritySpecAlgorithmParameterSpec:(id<JavaSecuritySpecAlgorithmParameterSpec>)params;

- (JavaSecurityAlgorithmParameters *)getParameters;

- (id)getParameterWithNSString:(NSString *)param;

- (void)copyAllFieldsTo:(JavaSecuritySignature *)other;

@end

FOUNDATION_EXPORT BOOL JavaSecuritySignature_initialized;
J2OBJC_STATIC_INIT(JavaSecuritySignature)

J2OBJC_FIELD_SETTER(JavaSecuritySignature, provider_, JavaSecurityProvider *)
J2OBJC_FIELD_SETTER(JavaSecuritySignature, algorithm_, NSString *)

FOUNDATION_EXPORT NSString *JavaSecuritySignature_SERVICE_;
J2OBJC_STATIC_FIELD_GETTER(JavaSecuritySignature, SERVICE_, NSString *)

FOUNDATION_EXPORT OrgApacheHarmonySecurityFortressEngine *JavaSecuritySignature_ENGINE_;
J2OBJC_STATIC_FIELD_GETTER(JavaSecuritySignature, ENGINE_, OrgApacheHarmonySecurityFortressEngine *)

J2OBJC_STATIC_FIELD_GETTER(JavaSecuritySignature, UNINITIALIZED, jint)

J2OBJC_STATIC_FIELD_GETTER(JavaSecuritySignature, SIGN, jint)

J2OBJC_STATIC_FIELD_GETTER(JavaSecuritySignature, VERIFY, jint)

@interface JavaSecuritySignature_SignatureImpl : JavaSecuritySignature {
 @public
  id initLock_;
  JavaSecurityProvider *specifiedProvider_;
  JavaSecuritySignatureSpi *spiImpl_;
}

- (instancetype)initWithNSString:(NSString *)algorithm
        withJavaSecurityProvider:(JavaSecurityProvider *)provider;

- (instancetype)initWithNSString:(NSString *)algorithm
        withJavaSecurityProvider:(JavaSecurityProvider *)provider
    withJavaSecuritySignatureSpi:(JavaSecuritySignatureSpi *)spi;

- (void)ensureProviderChosen;

- (IOSByteArray *)engineSign;

- (void)engineUpdateWithByte:(jbyte)arg0;

- (jboolean)engineVerifyWithByteArray:(IOSByteArray *)arg0;

- (void)engineUpdateWithByteArray:(IOSByteArray *)arg0
                          withInt:(jint)arg1
                          withInt:(jint)arg2;

- (void)engineInitSignWithJavaSecurityPrivateKey:(id<JavaSecurityPrivateKey>)arg0;

- (void)engineInitVerifyWithJavaSecurityPublicKey:(id<JavaSecurityPublicKey>)arg0;

- (id)engineGetParameterWithNSString:(NSString *)arg0;

- (void)engineSetParameterWithNSString:(NSString *)arg0
                                withId:(id)arg1;

- (void)engineSetParameterWithJavaSecuritySpecAlgorithmParameterSpec:(id<JavaSecuritySpecAlgorithmParameterSpec>)arg0;

- (id)clone;

- (JavaSecuritySignatureSpi *)getSpiWithJavaSecurityKey:(id<JavaSecurityKey>)key;

- (JavaSecuritySignatureSpi *)getSpi;

- (void)copyAllFieldsTo:(JavaSecuritySignature_SignatureImpl *)other;

@end

__attribute__((always_inline)) inline void JavaSecuritySignature_SignatureImpl_init() {}

J2OBJC_FIELD_SETTER(JavaSecuritySignature_SignatureImpl, initLock_, id)
J2OBJC_FIELD_SETTER(JavaSecuritySignature_SignatureImpl, specifiedProvider_, JavaSecurityProvider *)
J2OBJC_FIELD_SETTER(JavaSecuritySignature_SignatureImpl, spiImpl_, JavaSecuritySignatureSpi *)

#endif // _JavaSecuritySignature_H_
