//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/Signer.java
//

#ifndef _JavaSecuritySigner_H_
#define _JavaSecuritySigner_H_

@class JavaSecurityIdentityScope;
@class JavaSecurityKeyPair;
@protocol JavaSecurityPrivateKey;

#import "JreEmulation.h"
#include "java/security/Identity.h"

#define JavaSecuritySigner_serialVersionUID -1763464102261361480LL

@interface JavaSecuritySigner : JavaSecurityIdentity {
 @public
  id<JavaSecurityPrivateKey> privateKey_;
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)name;

- (instancetype)initWithNSString:(NSString *)name
   withJavaSecurityIdentityScope:(JavaSecurityIdentityScope *)scope;

- (id<JavaSecurityPrivateKey>)getPrivateKey;

- (void)setKeyPairWithJavaSecurityKeyPair:(JavaSecurityKeyPair *)pair;

- (NSString *)description;

- (void)copyAllFieldsTo:(JavaSecuritySigner *)other;

@end

__attribute__((always_inline)) inline void JavaSecuritySigner_init() {}

J2OBJC_FIELD_SETTER(JavaSecuritySigner, privateKey_, id<JavaSecurityPrivateKey>)

J2OBJC_STATIC_FIELD_GETTER(JavaSecuritySigner, serialVersionUID, jlong)

#endif // _JavaSecuritySigner_H_
