//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/Timestamp.java
//

#ifndef _JavaSecurityTimestamp_H_
#define _JavaSecurityTimestamp_H_

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"

@class JavaSecurityCertCertPath;
@class JavaUtilDate;

@interface JavaSecurityTimestamp : NSObject < JavaIoSerializable >

#pragma mark Public

- (instancetype)initWithJavaUtilDate:(JavaUtilDate *)timestamp
        withJavaSecurityCertCertPath:(JavaSecurityCertCertPath *)signerCertPath;

- (jboolean)isEqual:(id)obj;

- (JavaSecurityCertCertPath *)getSignerCertPath;

- (JavaUtilDate *)getTimestamp;

- (NSUInteger)hash;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaSecurityTimestamp)

FOUNDATION_EXPORT void JavaSecurityTimestamp_initWithJavaUtilDate_withJavaSecurityCertCertPath_(JavaSecurityTimestamp *self, JavaUtilDate *timestamp, JavaSecurityCertCertPath *signerCertPath);

FOUNDATION_EXPORT JavaSecurityTimestamp *new_JavaSecurityTimestamp_initWithJavaUtilDate_withJavaSecurityCertCertPath_(JavaUtilDate *timestamp, JavaSecurityCertCertPath *signerCertPath) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaSecurityTimestamp)

#endif // _JavaSecurityTimestamp_H_
