//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/Timestamp.java
//

#ifndef _JavaSecurityTimestamp_H_
#define _JavaSecurityTimestamp_H_

@class JavaSecurityCertCertPath;
@class JavaUtilDate;

#import "JreEmulation.h"
#include "java/io/Serializable.h"

#define JavaSecurityTimestamp_serialVersionUID -5502683707821851294LL

@interface JavaSecurityTimestamp : NSObject < JavaIoSerializable > {
 @public
  JavaUtilDate *timestamp_;
  JavaSecurityCertCertPath *signerCertPath_;
  jint hash__;
}

- (instancetype)initWithJavaUtilDate:(JavaUtilDate *)timestamp
        withJavaSecurityCertCertPath:(JavaSecurityCertCertPath *)signerCertPath;

- (jboolean)isEqual:(id)obj;

- (JavaSecurityCertCertPath *)getSignerCertPath;

- (JavaUtilDate *)getTimestamp;

- (NSUInteger)hash;

- (NSString *)description;

- (void)copyAllFieldsTo:(JavaSecurityTimestamp *)other;

@end

__attribute__((always_inline)) inline void JavaSecurityTimestamp_init() {}

J2OBJC_FIELD_SETTER(JavaSecurityTimestamp, timestamp_, JavaUtilDate *)
J2OBJC_FIELD_SETTER(JavaSecurityTimestamp, signerCertPath_, JavaSecurityCertCertPath *)

J2OBJC_STATIC_FIELD_GETTER(JavaSecurityTimestamp, serialVersionUID, jlong)

#endif // _JavaSecurityTimestamp_H_
