//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/UnresolvedPermission.java
//

#ifndef _JavaSecurityUnresolvedPermission_H_
#define _JavaSecurityUnresolvedPermission_H_

@class IOSObjectArray;

#import "JreEmulation.h"
#include "java/io/Serializable.h"
#include "java/security/Permission.h"

@interface JavaSecurityUnresolvedPermission : JavaSecurityPermission < JavaIoSerializable > {
}

- (instancetype)initWithNSString:(NSString *)type
                    withNSString:(NSString *)name
                    withNSString:(NSString *)actions
withJavaSecurityCertCertificateArray:(IOSObjectArray *)certs;

- (NSString *)getUnresolvedName;

- (NSString *)getUnresolvedActions;

- (NSString *)getUnresolvedType;

- (IOSObjectArray *)getUnresolvedCerts;

- (NSString *)getActions;

- (jboolean)impliesWithJavaSecurityPermission:(JavaSecurityPermission *)permission;

- (jboolean)isEqual:(id)pObj;

- (NSUInteger)hash;

@end

__attribute__((always_inline)) inline void JavaSecurityUnresolvedPermission_init() {}

#endif // _JavaSecurityUnresolvedPermission_H_
