//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/UnrecoverableEntryException.java
//

#ifndef _JavaSecurityUnrecoverableEntryException_H_
#define _JavaSecurityUnrecoverableEntryException_H_

#import "JreEmulation.h"
#include "java/security/GeneralSecurityException.h"

#define JavaSecurityUnrecoverableEntryException_serialVersionUID -4527142945246286535LL

@interface JavaSecurityUnrecoverableEntryException : JavaSecurityGeneralSecurityException {
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)msg;

@end

__attribute__((always_inline)) inline void JavaSecurityUnrecoverableEntryException_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaSecurityUnrecoverableEntryException, serialVersionUID, jlong)

#endif // _JavaSecurityUnrecoverableEntryException_H_
