//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/UnrecoverableKeyException.java
//

#ifndef _JavaSecurityUnrecoverableKeyException_H_
#define _JavaSecurityUnrecoverableKeyException_H_

#import "JreEmulation.h"
#include "java/security/UnrecoverableEntryException.h"

#define JavaSecurityUnrecoverableKeyException_serialVersionUID 7275063078190151277LL

@interface JavaSecurityUnrecoverableKeyException : JavaSecurityUnrecoverableEntryException {
}

- (instancetype)initWithNSString:(NSString *)msg;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void JavaSecurityUnrecoverableKeyException_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaSecurityUnrecoverableKeyException, serialVersionUID, jlong)

#endif // _JavaSecurityUnrecoverableKeyException_H_
