//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/crypto/spec/DESKeySpec.java
//

#ifndef _JavaxCryptoSpecDESKeySpec_H_
#define _JavaxCryptoSpecDESKeySpec_H_

@class IOSByteArray;
@class IOSObjectArray;

#import "JreEmulation.h"
#include "java/security/spec/KeySpec.h"

#define JavaxCryptoSpecDESKeySpec_DES_KEY_LEN 8

@interface JavaxCryptoSpecDESKeySpec : NSObject < JavaSecuritySpecKeySpec > {
 @public
  IOSByteArray *key_;
}

- (instancetype)initWithByteArray:(IOSByteArray *)key;

- (instancetype)initWithByteArray:(IOSByteArray *)key
                          withInt:(jint)offset;

- (IOSByteArray *)getKey;

+ (jboolean)isParityAdjustedWithByteArray:(IOSByteArray *)key
                                  withInt:(jint)offset;

+ (jboolean)isWeakWithByteArray:(IOSByteArray *)key
                        withInt:(jint)offset;

- (void)copyAllFieldsTo:(JavaxCryptoSpecDESKeySpec *)other;

@end

FOUNDATION_EXPORT BOOL JavaxCryptoSpecDESKeySpec_initialized;
J2OBJC_STATIC_INIT(JavaxCryptoSpecDESKeySpec)

J2OBJC_FIELD_SETTER(JavaxCryptoSpecDESKeySpec, key_, IOSByteArray *)

J2OBJC_STATIC_FIELD_GETTER(JavaxCryptoSpecDESKeySpec, DES_KEY_LEN, jint)

FOUNDATION_EXPORT IOSObjectArray *JavaxCryptoSpecDESKeySpec_SEMIWEAKS_;
J2OBJC_STATIC_FIELD_GETTER(JavaxCryptoSpecDESKeySpec, SEMIWEAKS_, IOSObjectArray *)

#endif // _JavaxCryptoSpecDESKeySpec_H_
