//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/crypto/spec/DHGenParameterSpec.java
//

#ifndef _JavaxCryptoSpecDHGenParameterSpec_H_
#define _JavaxCryptoSpecDHGenParameterSpec_H_

#include "J2ObjC_header.h"
#include "java/security/spec/AlgorithmParameterSpec.h"

@interface JavaxCryptoSpecDHGenParameterSpec : NSObject < JavaSecuritySpecAlgorithmParameterSpec >

#pragma mark Public

- (instancetype)initWithInt:(jint)primeSize
                    withInt:(jint)exponentSize;

- (jint)getExponentSize;

- (jint)getPrimeSize;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxCryptoSpecDHGenParameterSpec)

FOUNDATION_EXPORT void JavaxCryptoSpecDHGenParameterSpec_initWithInt_withInt_(JavaxCryptoSpecDHGenParameterSpec *self, jint primeSize, jint exponentSize);

FOUNDATION_EXPORT JavaxCryptoSpecDHGenParameterSpec *new_JavaxCryptoSpecDHGenParameterSpec_initWithInt_withInt_(jint primeSize, jint exponentSize) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaxCryptoSpecDHGenParameterSpec)

#endif // _JavaxCryptoSpecDHGenParameterSpec_H_
