//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/crypto/spec/DHGenParameterSpec.java
//

#ifndef _JavaxCryptoSpecDHGenParameterSpec_H_
#define _JavaxCryptoSpecDHGenParameterSpec_H_

#import "JreEmulation.h"
#include "java/security/spec/AlgorithmParameterSpec.h"

@interface JavaxCryptoSpecDHGenParameterSpec : NSObject < JavaSecuritySpecAlgorithmParameterSpec > {
 @public
  jint primeSize_;
  jint exponentSize_;
}

- (instancetype)initWithInt:(jint)primeSize
                    withInt:(jint)exponentSize;

- (jint)getPrimeSize;

- (jint)getExponentSize;

- (void)copyAllFieldsTo:(JavaxCryptoSpecDHGenParameterSpec *)other;

@end

__attribute__((always_inline)) inline void JavaxCryptoSpecDHGenParameterSpec_init() {}

#endif // _JavaxCryptoSpecDHGenParameterSpec_H_
