//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/crypto/spec/DHParameterSpec.java
//

#ifndef _JavaxCryptoSpecDHParameterSpec_H_
#define _JavaxCryptoSpecDHParameterSpec_H_

@class JavaMathBigInteger;

#import "JreEmulation.h"
#include "java/security/spec/AlgorithmParameterSpec.h"

@interface JavaxCryptoSpecDHParameterSpec : NSObject < JavaSecuritySpecAlgorithmParameterSpec > {
 @public
  JavaMathBigInteger *p_;
  JavaMathBigInteger *g_;
  jint l_;
}

- (instancetype)initWithJavaMathBigInteger:(JavaMathBigInteger *)p
                    withJavaMathBigInteger:(JavaMathBigInteger *)g;

- (instancetype)initWithJavaMathBigInteger:(JavaMathBigInteger *)p
                    withJavaMathBigInteger:(JavaMathBigInteger *)g
                                   withInt:(jint)l;

- (JavaMathBigInteger *)getP;

- (JavaMathBigInteger *)getG;

- (jint)getL;

- (void)copyAllFieldsTo:(JavaxCryptoSpecDHParameterSpec *)other;

@end

__attribute__((always_inline)) inline void JavaxCryptoSpecDHParameterSpec_init() {}

J2OBJC_FIELD_SETTER(JavaxCryptoSpecDHParameterSpec, p_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(JavaxCryptoSpecDHParameterSpec, g_, JavaMathBigInteger *)

#endif // _JavaxCryptoSpecDHParameterSpec_H_
