//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/crypto/spec/DHPublicKeySpec.java
//

#ifndef _JavaxCryptoSpecDHPublicKeySpec_H_
#define _JavaxCryptoSpecDHPublicKeySpec_H_

@class JavaMathBigInteger;

#import "JreEmulation.h"
#include "java/security/spec/KeySpec.h"

@interface JavaxCryptoSpecDHPublicKeySpec : NSObject < JavaSecuritySpecKeySpec > {
 @public
  JavaMathBigInteger *y_;
  JavaMathBigInteger *p_;
  JavaMathBigInteger *g_;
}

- (instancetype)initWithJavaMathBigInteger:(JavaMathBigInteger *)y
                    withJavaMathBigInteger:(JavaMathBigInteger *)p
                    withJavaMathBigInteger:(JavaMathBigInteger *)g;

- (JavaMathBigInteger *)getY;

- (JavaMathBigInteger *)getP;

- (JavaMathBigInteger *)getG;

- (void)copyAllFieldsTo:(JavaxCryptoSpecDHPublicKeySpec *)other;

@end

__attribute__((always_inline)) inline void JavaxCryptoSpecDHPublicKeySpec_init() {}

J2OBJC_FIELD_SETTER(JavaxCryptoSpecDHPublicKeySpec, y_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(JavaxCryptoSpecDHPublicKeySpec, p_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(JavaxCryptoSpecDHPublicKeySpec, g_, JavaMathBigInteger *)

#endif // _JavaxCryptoSpecDHPublicKeySpec_H_
