//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/crypto/spec/OAEPParameterSpec.java
//

#ifndef _JavaxCryptoSpecOAEPParameterSpec_H_
#define _JavaxCryptoSpecOAEPParameterSpec_H_

@class JavaxCryptoSpecPSource;

#import "JreEmulation.h"
#include "java/security/spec/AlgorithmParameterSpec.h"

@interface JavaxCryptoSpecOAEPParameterSpec : NSObject < JavaSecuritySpecAlgorithmParameterSpec > {
 @public
  NSString *mdName_;
  NSString *mgfName_;
  id<JavaSecuritySpecAlgorithmParameterSpec> mgfSpec_;
  JavaxCryptoSpecPSource *pSrc_;
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)mdName
                    withNSString:(NSString *)mgfName
withJavaSecuritySpecAlgorithmParameterSpec:(id<JavaSecuritySpecAlgorithmParameterSpec>)mgfSpec
      withJavaxCryptoSpecPSource:(JavaxCryptoSpecPSource *)pSrc;

- (NSString *)getDigestAlgorithm;

- (NSString *)getMGFAlgorithm;

- (id<JavaSecuritySpecAlgorithmParameterSpec>)getMGFParameters;

- (JavaxCryptoSpecPSource *)getPSource;

- (void)copyAllFieldsTo:(JavaxCryptoSpecOAEPParameterSpec *)other;

@end

FOUNDATION_EXPORT BOOL JavaxCryptoSpecOAEPParameterSpec_initialized;
J2OBJC_STATIC_INIT(JavaxCryptoSpecOAEPParameterSpec)

J2OBJC_FIELD_SETTER(JavaxCryptoSpecOAEPParameterSpec, mdName_, NSString *)
J2OBJC_FIELD_SETTER(JavaxCryptoSpecOAEPParameterSpec, mgfName_, NSString *)
J2OBJC_FIELD_SETTER(JavaxCryptoSpecOAEPParameterSpec, mgfSpec_, id<JavaSecuritySpecAlgorithmParameterSpec>)
J2OBJC_FIELD_SETTER(JavaxCryptoSpecOAEPParameterSpec, pSrc_, JavaxCryptoSpecPSource *)

FOUNDATION_EXPORT JavaxCryptoSpecOAEPParameterSpec *JavaxCryptoSpecOAEPParameterSpec_DEFAULT_;
J2OBJC_STATIC_FIELD_GETTER(JavaxCryptoSpecOAEPParameterSpec, DEFAULT_, JavaxCryptoSpecOAEPParameterSpec *)

#endif // _JavaxCryptoSpecOAEPParameterSpec_H_
