//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/crypto/spec/PBEKeySpec.java
//

#ifndef _JavaxCryptoSpecPBEKeySpec_H_
#define _JavaxCryptoSpecPBEKeySpec_H_

#include "J2ObjC_header.h"
#include "java/security/spec/KeySpec.h"

@class IOSByteArray;
@class IOSCharArray;

@interface JavaxCryptoSpecPBEKeySpec : NSObject < JavaSecuritySpecKeySpec >

#pragma mark Public

- (instancetype)initWithCharArray:(IOSCharArray *)password;

- (instancetype)initWithCharArray:(IOSCharArray *)password
                    withByteArray:(IOSByteArray *)salt
                          withInt:(jint)iterationCount;

- (instancetype)initWithCharArray:(IOSCharArray *)password
                    withByteArray:(IOSByteArray *)salt
                          withInt:(jint)iterationCount
                          withInt:(jint)keyLength;

- (void)clearPassword;

- (jint)getIterationCount;

- (jint)getKeyLength;

- (IOSCharArray *)getPassword;

- (IOSByteArray *)getSalt;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxCryptoSpecPBEKeySpec)

FOUNDATION_EXPORT void JavaxCryptoSpecPBEKeySpec_initWithCharArray_(JavaxCryptoSpecPBEKeySpec *self, IOSCharArray *password);

FOUNDATION_EXPORT JavaxCryptoSpecPBEKeySpec *new_JavaxCryptoSpecPBEKeySpec_initWithCharArray_(IOSCharArray *password) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JavaxCryptoSpecPBEKeySpec_initWithCharArray_withByteArray_withInt_withInt_(JavaxCryptoSpecPBEKeySpec *self, IOSCharArray *password, IOSByteArray *salt, jint iterationCount, jint keyLength);

FOUNDATION_EXPORT JavaxCryptoSpecPBEKeySpec *new_JavaxCryptoSpecPBEKeySpec_initWithCharArray_withByteArray_withInt_withInt_(IOSCharArray *password, IOSByteArray *salt, jint iterationCount, jint keyLength) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JavaxCryptoSpecPBEKeySpec_initWithCharArray_withByteArray_withInt_(JavaxCryptoSpecPBEKeySpec *self, IOSCharArray *password, IOSByteArray *salt, jint iterationCount);

FOUNDATION_EXPORT JavaxCryptoSpecPBEKeySpec *new_JavaxCryptoSpecPBEKeySpec_initWithCharArray_withByteArray_withInt_(IOSCharArray *password, IOSByteArray *salt, jint iterationCount) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaxCryptoSpecPBEKeySpec)

#endif // _JavaxCryptoSpecPBEKeySpec_H_
