//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/crypto/spec/PBEParameterSpec.java
//

#ifndef _JavaxCryptoSpecPBEParameterSpec_H_
#define _JavaxCryptoSpecPBEParameterSpec_H_

#include "J2ObjC_header.h"
#include "java/security/spec/AlgorithmParameterSpec.h"

@class IOSByteArray;

@interface JavaxCryptoSpecPBEParameterSpec : NSObject < JavaSecuritySpecAlgorithmParameterSpec >

#pragma mark Public

- (instancetype)initWithByteArray:(IOSByteArray *)salt
                          withInt:(jint)iterationCount;

- (jint)getIterationCount;

- (IOSByteArray *)getSalt;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxCryptoSpecPBEParameterSpec)

FOUNDATION_EXPORT void JavaxCryptoSpecPBEParameterSpec_initWithByteArray_withInt_(JavaxCryptoSpecPBEParameterSpec *self, IOSByteArray *salt, jint iterationCount);

FOUNDATION_EXPORT JavaxCryptoSpecPBEParameterSpec *new_JavaxCryptoSpecPBEParameterSpec_initWithByteArray_withInt_(IOSByteArray *salt, jint iterationCount) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaxCryptoSpecPBEParameterSpec)

#endif // _JavaxCryptoSpecPBEParameterSpec_H_
