//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/crypto/spec/PBEParameterSpec.java
//

#ifndef _JavaxCryptoSpecPBEParameterSpec_H_
#define _JavaxCryptoSpecPBEParameterSpec_H_

@class IOSByteArray;

#import "JreEmulation.h"
#include "java/security/spec/AlgorithmParameterSpec.h"

@interface JavaxCryptoSpecPBEParameterSpec : NSObject < JavaSecuritySpecAlgorithmParameterSpec > {
 @public
  IOSByteArray *salt_;
  jint iterationCount_;
}

- (instancetype)initWithByteArray:(IOSByteArray *)salt
                          withInt:(jint)iterationCount;

- (IOSByteArray *)getSalt;

- (jint)getIterationCount;

- (void)copyAllFieldsTo:(JavaxCryptoSpecPBEParameterSpec *)other;

@end

__attribute__((always_inline)) inline void JavaxCryptoSpecPBEParameterSpec_init() {}

J2OBJC_FIELD_SETTER(JavaxCryptoSpecPBEParameterSpec, salt_, IOSByteArray *)

#endif // _JavaxCryptoSpecPBEParameterSpec_H_
