//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/crypto/spec/PSource.java
//

#ifndef _JavaxCryptoSpecPSource_H_
#define _JavaxCryptoSpecPSource_H_

@class IOSByteArray;

#import "JreEmulation.h"

@interface JavaxCryptoSpecPSource : NSObject {
 @public
  NSString *pSrcName_;
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)pSrcName;

- (NSString *)getAlgorithm;

- (void)copyAllFieldsTo:(JavaxCryptoSpecPSource *)other;

@end

__attribute__((always_inline)) inline void JavaxCryptoSpecPSource_init() {}

J2OBJC_FIELD_SETTER(JavaxCryptoSpecPSource, pSrcName_, NSString *)

@interface JavaxCryptoSpecPSource_PSpecified : JavaxCryptoSpecPSource {
 @public
  IOSByteArray *p_;
}

- (instancetype)init;

- (instancetype)initWithByteArray:(IOSByteArray *)p;

- (IOSByteArray *)getValue;

- (void)copyAllFieldsTo:(JavaxCryptoSpecPSource_PSpecified *)other;

@end

FOUNDATION_EXPORT BOOL JavaxCryptoSpecPSource_PSpecified_initialized;
J2OBJC_STATIC_INIT(JavaxCryptoSpecPSource_PSpecified)

J2OBJC_FIELD_SETTER(JavaxCryptoSpecPSource_PSpecified, p_, IOSByteArray *)

FOUNDATION_EXPORT JavaxCryptoSpecPSource_PSpecified *JavaxCryptoSpecPSource_PSpecified_DEFAULT_;
J2OBJC_STATIC_FIELD_GETTER(JavaxCryptoSpecPSource_PSpecified, DEFAULT_, JavaxCryptoSpecPSource_PSpecified *)

#endif // _JavaxCryptoSpecPSource_H_
