//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/crypto/spec/PSource.java
//

#ifndef _JavaxCryptoSpecPSource_H_
#define _JavaxCryptoSpecPSource_H_

#include "J2ObjC_header.h"

@class IOSByteArray;

@interface JavaxCryptoSpecPSource : NSObject

#pragma mark Public

- (NSString *)getAlgorithm;

#pragma mark Protected

- (instancetype)initWithNSString:(NSString *)pSrcName;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxCryptoSpecPSource)

FOUNDATION_EXPORT void JavaxCryptoSpecPSource_initWithNSString_(JavaxCryptoSpecPSource *self, NSString *pSrcName);

FOUNDATION_EXPORT JavaxCryptoSpecPSource *new_JavaxCryptoSpecPSource_initWithNSString_(NSString *pSrcName) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaxCryptoSpecPSource)

@interface JavaxCryptoSpecPSource_PSpecified : JavaxCryptoSpecPSource

#pragma mark Public

- (instancetype)initWithByteArray:(IOSByteArray *)p;

- (IOSByteArray *)getValue;

@end

J2OBJC_STATIC_INIT(JavaxCryptoSpecPSource_PSpecified)

FOUNDATION_EXPORT JavaxCryptoSpecPSource_PSpecified *JavaxCryptoSpecPSource_PSpecified_DEFAULT_;
J2OBJC_STATIC_FIELD_GETTER(JavaxCryptoSpecPSource_PSpecified, DEFAULT_, JavaxCryptoSpecPSource_PSpecified *)

FOUNDATION_EXPORT void JavaxCryptoSpecPSource_PSpecified_initWithByteArray_(JavaxCryptoSpecPSource_PSpecified *self, IOSByteArray *p);

FOUNDATION_EXPORT JavaxCryptoSpecPSource_PSpecified *new_JavaxCryptoSpecPSource_PSpecified_initWithByteArray_(IOSByteArray *p) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaxCryptoSpecPSource_PSpecified)

#endif // _JavaxCryptoSpecPSource_H_
