//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/crypto/spec/RC2ParameterSpec.java
//

#ifndef _JavaxCryptoSpecRC2ParameterSpec_H_
#define _JavaxCryptoSpecRC2ParameterSpec_H_

#include "J2ObjC_header.h"
#include "java/security/spec/AlgorithmParameterSpec.h"

@class IOSByteArray;

@interface JavaxCryptoSpecRC2ParameterSpec : NSObject < JavaSecuritySpecAlgorithmParameterSpec >

#pragma mark Public

- (instancetype)initWithInt:(jint)effectiveKeyBits;

- (instancetype)initWithInt:(jint)effectiveKeyBits
              withByteArray:(IOSByteArray *)iv;

- (instancetype)initWithInt:(jint)effectiveKeyBits
              withByteArray:(IOSByteArray *)iv
                    withInt:(jint)offset;

- (jboolean)isEqual:(id)obj;

- (jint)getEffectiveKeyBits;

- (IOSByteArray *)getIV;

- (NSUInteger)hash;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxCryptoSpecRC2ParameterSpec)

FOUNDATION_EXPORT void JavaxCryptoSpecRC2ParameterSpec_initWithInt_(JavaxCryptoSpecRC2ParameterSpec *self, jint effectiveKeyBits);

FOUNDATION_EXPORT JavaxCryptoSpecRC2ParameterSpec *new_JavaxCryptoSpecRC2ParameterSpec_initWithInt_(jint effectiveKeyBits) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JavaxCryptoSpecRC2ParameterSpec_initWithInt_withByteArray_(JavaxCryptoSpecRC2ParameterSpec *self, jint effectiveKeyBits, IOSByteArray *iv);

FOUNDATION_EXPORT JavaxCryptoSpecRC2ParameterSpec *new_JavaxCryptoSpecRC2ParameterSpec_initWithInt_withByteArray_(jint effectiveKeyBits, IOSByteArray *iv) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JavaxCryptoSpecRC2ParameterSpec_initWithInt_withByteArray_withInt_(JavaxCryptoSpecRC2ParameterSpec *self, jint effectiveKeyBits, IOSByteArray *iv, jint offset);

FOUNDATION_EXPORT JavaxCryptoSpecRC2ParameterSpec *new_JavaxCryptoSpecRC2ParameterSpec_initWithInt_withByteArray_withInt_(jint effectiveKeyBits, IOSByteArray *iv, jint offset) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaxCryptoSpecRC2ParameterSpec)

#endif // _JavaxCryptoSpecRC2ParameterSpec_H_
