//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/crypto/spec/RC2ParameterSpec.java
//

#ifndef _JavaxCryptoSpecRC2ParameterSpec_H_
#define _JavaxCryptoSpecRC2ParameterSpec_H_

@class IOSByteArray;

#import "JreEmulation.h"
#include "java/security/spec/AlgorithmParameterSpec.h"

@interface JavaxCryptoSpecRC2ParameterSpec : NSObject < JavaSecuritySpecAlgorithmParameterSpec > {
 @public
  jint effectiveKeyBits_;
  IOSByteArray *iv_;
}

- (instancetype)initWithInt:(jint)effectiveKeyBits;

- (instancetype)initWithInt:(jint)effectiveKeyBits
              withByteArray:(IOSByteArray *)iv;

- (instancetype)initWithInt:(jint)effectiveKeyBits
              withByteArray:(IOSByteArray *)iv
                    withInt:(jint)offset;

- (jint)getEffectiveKeyBits;

- (IOSByteArray *)getIV;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

- (void)copyAllFieldsTo:(JavaxCryptoSpecRC2ParameterSpec *)other;

@end

__attribute__((always_inline)) inline void JavaxCryptoSpecRC2ParameterSpec_init() {}

J2OBJC_FIELD_SETTER(JavaxCryptoSpecRC2ParameterSpec, iv_, IOSByteArray *)

#endif // _JavaxCryptoSpecRC2ParameterSpec_H_
