//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/crypto/spec/RC5ParameterSpec.java
//

#ifndef _JavaxCryptoSpecRC5ParameterSpec_H_
#define _JavaxCryptoSpecRC5ParameterSpec_H_

#include "J2ObjC_header.h"
#include "java/security/spec/AlgorithmParameterSpec.h"

@class IOSByteArray;

@interface JavaxCryptoSpecRC5ParameterSpec : NSObject < JavaSecuritySpecAlgorithmParameterSpec >

#pragma mark Public

- (instancetype)initWithInt:(jint)version_
                    withInt:(jint)rounds
                    withInt:(jint)wordSize;

- (instancetype)initWithInt:(jint)version_
                    withInt:(jint)rounds
                    withInt:(jint)wordSize
              withByteArray:(IOSByteArray *)iv;

- (instancetype)initWithInt:(jint)version_
                    withInt:(jint)rounds
                    withInt:(jint)wordSize
              withByteArray:(IOSByteArray *)iv
                    withInt:(jint)offset;

- (jboolean)isEqual:(id)obj;

- (IOSByteArray *)getIV;

- (jint)getRounds;

- (jint)getVersion;

- (jint)getWordSize;

- (NSUInteger)hash;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxCryptoSpecRC5ParameterSpec)

FOUNDATION_EXPORT void JavaxCryptoSpecRC5ParameterSpec_initWithInt_withInt_withInt_(JavaxCryptoSpecRC5ParameterSpec *self, jint version_, jint rounds, jint wordSize);

FOUNDATION_EXPORT JavaxCryptoSpecRC5ParameterSpec *new_JavaxCryptoSpecRC5ParameterSpec_initWithInt_withInt_withInt_(jint version_, jint rounds, jint wordSize) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JavaxCryptoSpecRC5ParameterSpec_initWithInt_withInt_withInt_withByteArray_(JavaxCryptoSpecRC5ParameterSpec *self, jint version_, jint rounds, jint wordSize, IOSByteArray *iv);

FOUNDATION_EXPORT JavaxCryptoSpecRC5ParameterSpec *new_JavaxCryptoSpecRC5ParameterSpec_initWithInt_withInt_withInt_withByteArray_(jint version_, jint rounds, jint wordSize, IOSByteArray *iv) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JavaxCryptoSpecRC5ParameterSpec_initWithInt_withInt_withInt_withByteArray_withInt_(JavaxCryptoSpecRC5ParameterSpec *self, jint version_, jint rounds, jint wordSize, IOSByteArray *iv, jint offset);

FOUNDATION_EXPORT JavaxCryptoSpecRC5ParameterSpec *new_JavaxCryptoSpecRC5ParameterSpec_initWithInt_withInt_withInt_withByteArray_withInt_(jint version_, jint rounds, jint wordSize, IOSByteArray *iv, jint offset) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaxCryptoSpecRC5ParameterSpec)

#endif // _JavaxCryptoSpecRC5ParameterSpec_H_
