//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/crypto/spec/RC5ParameterSpec.java
//

#ifndef _JavaxCryptoSpecRC5ParameterSpec_H_
#define _JavaxCryptoSpecRC5ParameterSpec_H_

@class IOSByteArray;

#import "JreEmulation.h"
#include "java/security/spec/AlgorithmParameterSpec.h"

@interface JavaxCryptoSpecRC5ParameterSpec : NSObject < JavaSecuritySpecAlgorithmParameterSpec > {
 @public
  jint version__;
  jint rounds_;
  jint wordSize_;
  IOSByteArray *iv_;
}

- (instancetype)initWithInt:(jint)version_
                    withInt:(jint)rounds
                    withInt:(jint)wordSize;

- (instancetype)initWithInt:(jint)version_
                    withInt:(jint)rounds
                    withInt:(jint)wordSize
              withByteArray:(IOSByteArray *)iv;

- (instancetype)initWithInt:(jint)version_
                    withInt:(jint)rounds
                    withInt:(jint)wordSize
              withByteArray:(IOSByteArray *)iv
                    withInt:(jint)offset;

- (jint)getVersion;

- (jint)getRounds;

- (jint)getWordSize;

- (IOSByteArray *)getIV;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

- (void)copyAllFieldsTo:(JavaxCryptoSpecRC5ParameterSpec *)other;

@end

__attribute__((always_inline)) inline void JavaxCryptoSpecRC5ParameterSpec_init() {}

J2OBJC_FIELD_SETTER(JavaxCryptoSpecRC5ParameterSpec, iv_, IOSByteArray *)

#endif // _JavaxCryptoSpecRC5ParameterSpec_H_
