//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/crypto/spec/SecretKeySpec.java
//

#ifndef _JavaxCryptoSpecSecretKeySpec_H_
#define _JavaxCryptoSpecSecretKeySpec_H_

@class IOSByteArray;

#import "JreEmulation.h"
#include "java/io/Serializable.h"
#include "java/security/spec/KeySpec.h"
#include "javax/crypto/SecretKey.h"

#define JavaxCryptoSpecSecretKeySpec_serialVersionUID 6577238317307289933LL

@interface JavaxCryptoSpecSecretKeySpec : NSObject < JavaxCryptoSecretKey, JavaSecuritySpecKeySpec, JavaIoSerializable > {
 @public
  IOSByteArray *key_;
  NSString *algorithm_;
}

- (instancetype)initWithByteArray:(IOSByteArray *)key
                     withNSString:(NSString *)algorithm;

- (instancetype)initWithByteArray:(IOSByteArray *)key
                          withInt:(jint)offset
                          withInt:(jint)len
                     withNSString:(NSString *)algorithm;

- (NSString *)getAlgorithm;

- (NSString *)getFormat;

- (IOSByteArray *)getEncoded;

- (NSUInteger)hash;

- (jboolean)isEqual:(id)obj;

- (void)copyAllFieldsTo:(JavaxCryptoSpecSecretKeySpec *)other;

@end

__attribute__((always_inline)) inline void JavaxCryptoSpecSecretKeySpec_init() {}

J2OBJC_FIELD_SETTER(JavaxCryptoSpecSecretKeySpec, key_, IOSByteArray *)
J2OBJC_FIELD_SETTER(JavaxCryptoSpecSecretKeySpec, algorithm_, NSString *)

J2OBJC_STATIC_FIELD_GETTER(JavaxCryptoSpecSecretKeySpec, serialVersionUID, jlong)

#endif // _JavaxCryptoSpecSecretKeySpec_H_
