//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/database/Cursor.java
//

#ifndef _AndroidDatabaseCursor_H_
#define _AndroidDatabaseCursor_H_

#import "JreEmulation.h"

#define AndroidDatabaseCursor_FIELD_TYPE_BLOB 4
#define AndroidDatabaseCursor_FIELD_TYPE_FLOAT 2
#define AndroidDatabaseCursor_FIELD_TYPE_INTEGER 1
#define AndroidDatabaseCursor_FIELD_TYPE_NULL 0
#define AndroidDatabaseCursor_FIELD_TYPE_STRING 3

@protocol AndroidDatabaseCursor < NSObject, JavaObject >

- (void)close;

- (jboolean)isNullWithInt:(jint)pIndex;

- (jint)getTypeWithInt:(jint)pIndex;

- (jint)getColumnCount;

- (NSString *)getColumnNameWithInt:(jint)pIndex;

- (NSString *)getStringWithInt:(jint)pIndex;

- (jint)getIntWithInt:(jint)pIndex;

- (jshort)getShortWithInt:(jint)pIndex;

- (jfloat)getFloatWithInt:(jint)pIndex;

- (jdouble)getDoubleWithInt:(jint)pIndex;

- (jboolean)moveWithInt:(jint)pStep;

@end

__attribute__((always_inline)) inline void AndroidDatabaseCursor_init() {}

J2OBJC_STATIC_FIELD_GETTER(AndroidDatabaseCursor, FIELD_TYPE_NULL, jint)

J2OBJC_STATIC_FIELD_GETTER(AndroidDatabaseCursor, FIELD_TYPE_INTEGER, jint)

J2OBJC_STATIC_FIELD_GETTER(AndroidDatabaseCursor, FIELD_TYPE_FLOAT, jint)

J2OBJC_STATIC_FIELD_GETTER(AndroidDatabaseCursor, FIELD_TYPE_STRING, jint)

J2OBJC_STATIC_FIELD_GETTER(AndroidDatabaseCursor, FIELD_TYPE_BLOB, jint)

#endif // _AndroidDatabaseCursor_H_
