//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/database/DatabaseErrorHandler.java
//

#ifndef _AndroidDatabaseDatabaseErrorHandler_H_
#define _AndroidDatabaseDatabaseErrorHandler_H_

#import "JreEmulation.h"

@protocol AndroidDatabaseDatabaseErrorHandler < NSObject, JavaObject >

@end

__attribute__((always_inline)) inline void AndroidDatabaseDatabaseErrorHandler_init() {}

#endif // _AndroidDatabaseDatabaseErrorHandler_H_
