//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/database/DatabaseErrorHandler.java
//

#ifndef _AndroidDatabaseDatabaseErrorHandler_H_
#define _AndroidDatabaseDatabaseErrorHandler_H_

#include "J2ObjC_header.h"

@protocol AndroidDatabaseDatabaseErrorHandler < NSObject, JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidDatabaseDatabaseErrorHandler)

J2OBJC_TYPE_LITERAL_HEADER(AndroidDatabaseDatabaseErrorHandler)

#endif // _AndroidDatabaseDatabaseErrorHandler_H_
