//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/text/TextPaint.java
//

#ifndef _AndroidTextTextPaint_H_
#define _AndroidTextTextPaint_H_

#import "JreEmulation.h"
#include "android/graphics/Paint.h"

@interface AndroidTextTextPaint : AndroidGraphicsPaint {
}

- (instancetype)init;

@end

__attribute__((always_inline)) inline void AndroidTextTextPaint_init() {}

#endif // _AndroidTextTextPaint_H_
