//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/text/TextPaint.java
//

#ifndef _AndroidTextTextPaint_H_
#define _AndroidTextTextPaint_H_

#include "J2ObjC_header.h"
#include "android/graphics/Paint.h"

@interface AndroidTextTextPaint : AndroidGraphicsPaint

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidTextTextPaint)

FOUNDATION_EXPORT void AndroidTextTextPaint_init(AndroidTextTextPaint *self);

FOUNDATION_EXPORT AndroidTextTextPaint *new_AndroidTextTextPaint_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(AndroidTextTextPaint)

#endif // _AndroidTextTextPaint_H_
