//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/interfaces/DSAKey.java
//

#ifndef _JavaSecurityInterfacesDSAKey_H_
#define _JavaSecurityInterfacesDSAKey_H_

#include "J2ObjC_header.h"

@protocol JavaSecurityInterfacesDSAParams;

@protocol JavaSecurityInterfacesDSAKey < NSObject, JavaObject >

- (id<JavaSecurityInterfacesDSAParams>)getParams;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaSecurityInterfacesDSAKey)

J2OBJC_TYPE_LITERAL_HEADER(JavaSecurityInterfacesDSAKey)

#endif // _JavaSecurityInterfacesDSAKey_H_
