//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/interfaces/DSAKeyPairGenerator.java
//

#ifndef _JavaSecurityInterfacesDSAKeyPairGenerator_H_
#define _JavaSecurityInterfacesDSAKeyPairGenerator_H_

@class JavaSecuritySecureRandom;
@protocol JavaSecurityInterfacesDSAParams;

#import "JreEmulation.h"

@protocol JavaSecurityInterfacesDSAKeyPairGenerator < NSObject, JavaObject >

- (void)initialize__WithJavaSecurityInterfacesDSAParams:(id<JavaSecurityInterfacesDSAParams>)params
                           withJavaSecuritySecureRandom:(JavaSecuritySecureRandom *)random OBJC_METHOD_FAMILY_NONE;

- (void)initialize__WithInt:(jint)modlen
                withBoolean:(jboolean)genParams
withJavaSecuritySecureRandom:(JavaSecuritySecureRandom *)random OBJC_METHOD_FAMILY_NONE;

@end

__attribute__((always_inline)) inline void JavaSecurityInterfacesDSAKeyPairGenerator_init() {}

#endif // _JavaSecurityInterfacesDSAKeyPairGenerator_H_
