//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/interfaces/DSAKey.java
//

#ifndef _JavaSecurityInterfacesDSAKey_H_
#define _JavaSecurityInterfacesDSAKey_H_

@protocol JavaSecurityInterfacesDSAParams;

#import "JreEmulation.h"

@protocol JavaSecurityInterfacesDSAKey < NSObject, JavaObject >

- (id<JavaSecurityInterfacesDSAParams>)getParams;

@end

__attribute__((always_inline)) inline void JavaSecurityInterfacesDSAKey_init() {}

#endif // _JavaSecurityInterfacesDSAKey_H_
