//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/interfaces/DSAKeyPairGenerator.java
//

#ifndef _JavaSecurityInterfacesDSAKeyPairGenerator_H_
#define _JavaSecurityInterfacesDSAKeyPairGenerator_H_

#include "J2ObjC_header.h"

@class JavaSecuritySecureRandom;
@protocol JavaSecurityInterfacesDSAParams;

@protocol JavaSecurityInterfacesDSAKeyPairGenerator < NSObject, JavaObject >

- (void)initialize__WithJavaSecurityInterfacesDSAParams:(id<JavaSecurityInterfacesDSAParams>)params
                           withJavaSecuritySecureRandom:(JavaSecuritySecureRandom *)random OBJC_METHOD_FAMILY_NONE;

- (void)initialize__WithInt:(jint)modlen
                withBoolean:(jboolean)genParams
withJavaSecuritySecureRandom:(JavaSecuritySecureRandom *)random OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaSecurityInterfacesDSAKeyPairGenerator)

J2OBJC_TYPE_LITERAL_HEADER(JavaSecurityInterfacesDSAKeyPairGenerator)

#endif // _JavaSecurityInterfacesDSAKeyPairGenerator_H_
