//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/interfaces/DSAPrivateKey.java
//

#ifndef _JavaSecurityInterfacesDSAPrivateKey_H_
#define _JavaSecurityInterfacesDSAPrivateKey_H_

@class JavaMathBigInteger;

#import "JreEmulation.h"
#include "java/security/PrivateKey.h"
#include "java/security/interfaces/DSAKey.h"

#define JavaSecurityInterfacesDSAPrivateKey_serialVersionUID 7776497482533790279LL

@protocol JavaSecurityInterfacesDSAPrivateKey < JavaSecurityInterfacesDSAKey, JavaSecurityPrivateKey, NSObject, JavaObject >
- (JavaMathBigInteger *)getX;

@end

__attribute__((always_inline)) inline void JavaSecurityInterfacesDSAPrivateKey_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaSecurityInterfacesDSAPrivateKey, serialVersionUID, jlong)

#endif // _JavaSecurityInterfacesDSAPrivateKey_H_
