//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/interfaces/DSAParams.java
//

#ifndef _JavaSecurityInterfacesDSAParams_H_
#define _JavaSecurityInterfacesDSAParams_H_

#include "J2ObjC_header.h"

@class JavaMathBigInteger;

@protocol JavaSecurityInterfacesDSAParams < NSObject, JavaObject >

- (JavaMathBigInteger *)getG;

- (JavaMathBigInteger *)getP;

- (JavaMathBigInteger *)getQ;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaSecurityInterfacesDSAParams)

J2OBJC_TYPE_LITERAL_HEADER(JavaSecurityInterfacesDSAParams)

#endif // _JavaSecurityInterfacesDSAParams_H_
