//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/interfaces/DSAParams.java
//

#ifndef _JavaSecurityInterfacesDSAParams_H_
#define _JavaSecurityInterfacesDSAParams_H_

@class JavaMathBigInteger;

#import "JreEmulation.h"

@protocol JavaSecurityInterfacesDSAParams < NSObject, JavaObject >

- (JavaMathBigInteger *)getG;

- (JavaMathBigInteger *)getP;

- (JavaMathBigInteger *)getQ;

@end

__attribute__((always_inline)) inline void JavaSecurityInterfacesDSAParams_init() {}

#endif // _JavaSecurityInterfacesDSAParams_H_
