//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/interfaces/ECKey.java
//

#ifndef _JavaSecurityInterfacesECKey_H_
#define _JavaSecurityInterfacesECKey_H_

@class JavaSecuritySpecECParameterSpec;

#import "JreEmulation.h"

@protocol JavaSecurityInterfacesECKey < NSObject, JavaObject >

- (JavaSecuritySpecECParameterSpec *)getParams;

@end

__attribute__((always_inline)) inline void JavaSecurityInterfacesECKey_init() {}

#endif // _JavaSecurityInterfacesECKey_H_
