//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/interfaces/ECPrivateKey.java
//

#ifndef _JavaSecurityInterfacesECPrivateKey_H_
#define _JavaSecurityInterfacesECPrivateKey_H_

@class JavaMathBigInteger;

#import "JreEmulation.h"
#include "java/security/PrivateKey.h"
#include "java/security/interfaces/ECKey.h"

#define JavaSecurityInterfacesECPrivateKey_serialVersionUID -7896394956925609184LL

@protocol JavaSecurityInterfacesECPrivateKey < JavaSecurityPrivateKey, JavaSecurityInterfacesECKey, NSObject, JavaObject >
- (JavaMathBigInteger *)getS;

@end

__attribute__((always_inline)) inline void JavaSecurityInterfacesECPrivateKey_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaSecurityInterfacesECPrivateKey, serialVersionUID, jlong)

#endif // _JavaSecurityInterfacesECPrivateKey_H_
