//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/interfaces/RSAKey.java
//

#ifndef _JavaSecurityInterfacesRSAKey_H_
#define _JavaSecurityInterfacesRSAKey_H_

@class JavaMathBigInteger;

#import "JreEmulation.h"

@protocol JavaSecurityInterfacesRSAKey < NSObject, JavaObject >

- (JavaMathBigInteger *)getModulus;

@end

__attribute__((always_inline)) inline void JavaSecurityInterfacesRSAKey_init() {}

#endif // _JavaSecurityInterfacesRSAKey_H_
