//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/interfaces/RSAMultiPrimePrivateCrtKey.java
//

#ifndef _JavaSecurityInterfacesRSAMultiPrimePrivateCrtKey_H_
#define _JavaSecurityInterfacesRSAMultiPrimePrivateCrtKey_H_

@class IOSObjectArray;
@class JavaMathBigInteger;

#import "JreEmulation.h"
#include "java/security/interfaces/RSAPrivateKey.h"

#define JavaSecurityInterfacesRSAMultiPrimePrivateCrtKey_serialVersionUID 618058533534628008LL

@protocol JavaSecurityInterfacesRSAMultiPrimePrivateCrtKey < JavaSecurityInterfacesRSAPrivateKey, NSObject, JavaObject >
- (JavaMathBigInteger *)getCrtCoefficient;

- (IOSObjectArray *)getOtherPrimeInfo;

- (JavaMathBigInteger *)getPrimeP;

- (JavaMathBigInteger *)getPrimeQ;

- (JavaMathBigInteger *)getPrimeExponentP;

- (JavaMathBigInteger *)getPrimeExponentQ;

- (JavaMathBigInteger *)getPublicExponent;

@end

__attribute__((always_inline)) inline void JavaSecurityInterfacesRSAMultiPrimePrivateCrtKey_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaSecurityInterfacesRSAMultiPrimePrivateCrtKey, serialVersionUID, jlong)

#endif // _JavaSecurityInterfacesRSAMultiPrimePrivateCrtKey_H_
