//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/interfaces/RSAPublicKey.java
//

#ifndef _JavaSecurityInterfacesRSAPublicKey_H_
#define _JavaSecurityInterfacesRSAPublicKey_H_

@class JavaMathBigInteger;

#import "JreEmulation.h"
#include "java/security/PublicKey.h"
#include "java/security/interfaces/RSAKey.h"

#define JavaSecurityInterfacesRSAPublicKey_serialVersionUID -8727434096241101194LL

@protocol JavaSecurityInterfacesRSAPublicKey < JavaSecurityPublicKey, JavaSecurityInterfacesRSAKey, NSObject, JavaObject >
- (JavaMathBigInteger *)getPublicExponent;

@end

__attribute__((always_inline)) inline void JavaSecurityInterfacesRSAPublicKey_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaSecurityInterfacesRSAPublicKey, serialVersionUID, jlong)

#endif // _JavaSecurityInterfacesRSAPublicKey_H_
