//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/interfaces/RSAPrivateCrtKey.java
//

#ifndef _JavaSecurityInterfacesRSAPrivateCrtKey_H_
#define _JavaSecurityInterfacesRSAPrivateCrtKey_H_

@class JavaMathBigInteger;

#import "JreEmulation.h"
#include "java/security/interfaces/RSAPrivateKey.h"

#define JavaSecurityInterfacesRSAPrivateCrtKey_serialVersionUID -5682214253527700368LL

@protocol JavaSecurityInterfacesRSAPrivateCrtKey < JavaSecurityInterfacesRSAPrivateKey, NSObject, JavaObject >
- (JavaMathBigInteger *)getCrtCoefficient;

- (JavaMathBigInteger *)getPrimeP;

- (JavaMathBigInteger *)getPrimeQ;

- (JavaMathBigInteger *)getPrimeExponentP;

- (JavaMathBigInteger *)getPrimeExponentQ;

- (JavaMathBigInteger *)getPublicExponent;

@end

__attribute__((always_inline)) inline void JavaSecurityInterfacesRSAPrivateCrtKey_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaSecurityInterfacesRSAPrivateCrtKey, serialVersionUID, jlong)

#endif // _JavaSecurityInterfacesRSAPrivateCrtKey_H_
