//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/java/security/interfaces/RSAPrivateKey.java
//

#ifndef _JavaSecurityInterfacesRSAPrivateKey_H_
#define _JavaSecurityInterfacesRSAPrivateKey_H_

@class JavaMathBigInteger;

#import "JreEmulation.h"
#include "java/security/PrivateKey.h"
#include "java/security/interfaces/RSAKey.h"

#define JavaSecurityInterfacesRSAPrivateKey_serialVersionUID 5187144804936595022LL

@protocol JavaSecurityInterfacesRSAPrivateKey < JavaSecurityPrivateKey, JavaSecurityInterfacesRSAKey, NSObject, JavaObject >
- (JavaMathBigInteger *)getPrivateExponent;

@end

__attribute__((always_inline)) inline void JavaSecurityInterfacesRSAPrivateKey_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaSecurityInterfacesRSAPrivateKey, serialVersionUID, jlong)

#endif // _JavaSecurityInterfacesRSAPrivateKey_H_
