//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/graphics/drawable/Drawable.java
//

#ifndef _AndroidGraphicsDrawableDrawable_H_
#define _AndroidGraphicsDrawableDrawable_H_

#include "J2ObjC_header.h"

@protocol AndroidGraphicsCanvas;

@protocol AndroidGraphicsDrawableDrawable < NSObject, JavaObject >

- (jint)getIntrinsicWidth;

- (void)setBoundsWithInt:(jint)pLeft
                 withInt:(jint)pTop
                 withInt:(jint)pRight
                 withInt:(jint)pBottom;

- (void)drawWithAndroidGraphicsCanvas:(id<AndroidGraphicsCanvas>)pC;

- (jint)getOpacity;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidGraphicsDrawableDrawable)

J2OBJC_TYPE_LITERAL_HEADER(AndroidGraphicsDrawableDrawable)

#endif // _AndroidGraphicsDrawableDrawable_H_
