//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/graphics/drawable/Drawable.java
//

#ifndef _AndroidGraphicsDrawableDrawable_H_
#define _AndroidGraphicsDrawableDrawable_H_

@protocol AndroidGraphicsCanvas;

#import "JreEmulation.h"

@protocol AndroidGraphicsDrawableDrawable < NSObject, JavaObject >

- (jint)getIntrinsicWidth;

- (void)setBoundsWithInt:(jint)pLeft
                 withInt:(jint)pTop
                 withInt:(jint)pRight
                 withInt:(jint)pBottom;

- (void)drawWithAndroidGraphicsCanvas:(id<AndroidGraphicsCanvas>)pC;

- (jint)getOpacity;

@end

__attribute__((always_inline)) inline void AndroidGraphicsDrawableDrawable_init() {}

#endif // _AndroidGraphicsDrawableDrawable_H_
