//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/util/AttributeSet.java
//

#ifndef _AndroidUtilAttributeSet_H_
#define _AndroidUtilAttributeSet_H_

#import "JreEmulation.h"

@protocol AndroidUtilAttributeSet < NSObject, JavaObject >

@end

__attribute__((always_inline)) inline void AndroidUtilAttributeSet_init() {}

#endif // _AndroidUtilAttributeSet_H_
