//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/util/AttributeSet.java
//

#ifndef _AndroidUtilAttributeSet_H_
#define _AndroidUtilAttributeSet_H_

#include "J2ObjC_header.h"

@protocol AndroidUtilAttributeSet < NSObject, JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidUtilAttributeSet)

J2OBJC_TYPE_LITERAL_HEADER(AndroidUtilAttributeSet)

#endif // _AndroidUtilAttributeSet_H_
