//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/util/TypedValue.java
//

#ifndef _AndroidUtilTypedValue_H_
#define _AndroidUtilTypedValue_H_

#include "J2ObjC_header.h"
#include "java/lang/Enum.h"

@interface AndroidUtilTypedValue : NSObject

#pragma mark Public

- (instancetype)init;

- (jboolean)getBoolean;

- (jfloat)getFloat;

- (jint)getInt;

- (NSString *)getString;

- (void)setBooleanWithBoolean:(jboolean)pValue;

- (void)setFloatWithFloat:(jfloat)pValue;

- (void)setIntWithInt:(jint)pValue;

- (void)setStringWithNSString:(NSString *)pValue;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidUtilTypedValue)

FOUNDATION_EXPORT void AndroidUtilTypedValue_init(AndroidUtilTypedValue *self);

FOUNDATION_EXPORT AndroidUtilTypedValue *new_AndroidUtilTypedValue_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(AndroidUtilTypedValue)

typedef NS_ENUM(NSUInteger, AndroidUtilTypedValue_Type) {
  AndroidUtilTypedValue_Type_FLOAT = 0,
  AndroidUtilTypedValue_Type_INTEGER = 1,
  AndroidUtilTypedValue_Type_BOOLEAN = 2,
  AndroidUtilTypedValue_Type_STRING = 3,
};

@interface AndroidUtilTypedValue_TypeEnum : JavaLangEnum < NSCopying >

#pragma mark Package-Private

+ (IOSObjectArray *)values;
FOUNDATION_EXPORT IOSObjectArray *AndroidUtilTypedValue_TypeEnum_values();

+ (AndroidUtilTypedValue_TypeEnum *)valueOfWithNSString:(NSString *)name;
FOUNDATION_EXPORT AndroidUtilTypedValue_TypeEnum *AndroidUtilTypedValue_TypeEnum_valueOfWithNSString_(NSString *name);

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(AndroidUtilTypedValue_TypeEnum)

FOUNDATION_EXPORT AndroidUtilTypedValue_TypeEnum *AndroidUtilTypedValue_TypeEnum_values_[];

#define AndroidUtilTypedValue_TypeEnum_FLOAT AndroidUtilTypedValue_TypeEnum_values_[AndroidUtilTypedValue_Type_FLOAT]
J2OBJC_ENUM_CONSTANT_GETTER(AndroidUtilTypedValue_TypeEnum, FLOAT)

#define AndroidUtilTypedValue_TypeEnum_INTEGER AndroidUtilTypedValue_TypeEnum_values_[AndroidUtilTypedValue_Type_INTEGER]
J2OBJC_ENUM_CONSTANT_GETTER(AndroidUtilTypedValue_TypeEnum, INTEGER)

#define AndroidUtilTypedValue_TypeEnum_BOOLEAN AndroidUtilTypedValue_TypeEnum_values_[AndroidUtilTypedValue_Type_BOOLEAN]
J2OBJC_ENUM_CONSTANT_GETTER(AndroidUtilTypedValue_TypeEnum, BOOLEAN)

#define AndroidUtilTypedValue_TypeEnum_STRING AndroidUtilTypedValue_TypeEnum_values_[AndroidUtilTypedValue_Type_STRING]
J2OBJC_ENUM_CONSTANT_GETTER(AndroidUtilTypedValue_TypeEnum, STRING)

J2OBJC_TYPE_LITERAL_HEADER(AndroidUtilTypedValue_TypeEnum)

#endif // _AndroidUtilTypedValue_H_
