//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/util/TypedValue.java
//

#ifndef _AndroidUtilTypedValue_H_
#define _AndroidUtilTypedValue_H_

@class AndroidUtilTypedValue_TypeEnum;

#import "JreEmulation.h"
#include "java/lang/Enum.h"

@interface AndroidUtilTypedValue : NSObject {
 @public
  id mValue_;
  AndroidUtilTypedValue_TypeEnum *mType_;
}

- (void)setBooleanWithBoolean:(jboolean)pValue;

- (jboolean)getBoolean;

- (void)setFloatWithFloat:(jfloat)pValue;

- (jfloat)getFloat;

- (void)setIntWithInt:(jint)pValue;

- (jint)getInt;

- (void)setStringWithNSString:(NSString *)pValue;

- (NSString *)getString;

- (instancetype)init;

- (void)copyAllFieldsTo:(AndroidUtilTypedValue *)other;

@end

__attribute__((always_inline)) inline void AndroidUtilTypedValue_init() {}

J2OBJC_FIELD_SETTER(AndroidUtilTypedValue, mValue_, id)
J2OBJC_FIELD_SETTER(AndroidUtilTypedValue, mType_, AndroidUtilTypedValue_TypeEnum *)

typedef enum {
  AndroidUtilTypedValue_Type_FLOAT = 0,
  AndroidUtilTypedValue_Type_INTEGER = 1,
  AndroidUtilTypedValue_Type_BOOLEAN = 2,
  AndroidUtilTypedValue_Type_STRING = 3,
} AndroidUtilTypedValue_Type;

@interface AndroidUtilTypedValue_TypeEnum : JavaLangEnum < NSCopying > {
}

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal;

+ (IOSObjectArray *)values;
FOUNDATION_EXPORT IOSObjectArray *AndroidUtilTypedValue_TypeEnum_values();

+ (AndroidUtilTypedValue_TypeEnum *)valueOfWithNSString:(NSString *)name;

FOUNDATION_EXPORT AndroidUtilTypedValue_TypeEnum *AndroidUtilTypedValue_TypeEnum_valueOfWithNSString_(NSString *name);- (id)copyWithZone:(NSZone *)zone;

@end

FOUNDATION_EXPORT BOOL AndroidUtilTypedValue_TypeEnum_initialized;
J2OBJC_STATIC_INIT(AndroidUtilTypedValue_TypeEnum)

FOUNDATION_EXPORT AndroidUtilTypedValue_TypeEnum *AndroidUtilTypedValue_TypeEnum_values_[];

#define AndroidUtilTypedValue_TypeEnum_FLOAT AndroidUtilTypedValue_TypeEnum_values_[AndroidUtilTypedValue_Type_FLOAT]
J2OBJC_STATIC_FIELD_GETTER(AndroidUtilTypedValue_TypeEnum, FLOAT, AndroidUtilTypedValue_TypeEnum *)

#define AndroidUtilTypedValue_TypeEnum_INTEGER AndroidUtilTypedValue_TypeEnum_values_[AndroidUtilTypedValue_Type_INTEGER]
J2OBJC_STATIC_FIELD_GETTER(AndroidUtilTypedValue_TypeEnum, INTEGER, AndroidUtilTypedValue_TypeEnum *)

#define AndroidUtilTypedValue_TypeEnum_BOOLEAN AndroidUtilTypedValue_TypeEnum_values_[AndroidUtilTypedValue_Type_BOOLEAN]
J2OBJC_STATIC_FIELD_GETTER(AndroidUtilTypedValue_TypeEnum, BOOLEAN, AndroidUtilTypedValue_TypeEnum *)

#define AndroidUtilTypedValue_TypeEnum_STRING AndroidUtilTypedValue_TypeEnum_values_[AndroidUtilTypedValue_Type_STRING]
J2OBJC_STATIC_FIELD_GETTER(AndroidUtilTypedValue_TypeEnum, STRING, AndroidUtilTypedValue_TypeEnum *)

#endif // _AndroidUtilTypedValue_H_
