//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/crypto/SecretKey.java
//

#ifndef _JavaxCryptoSecretKey_H_
#define _JavaxCryptoSecretKey_H_

#import "JreEmulation.h"
#include "java/security/Key.h"

#define JavaxCryptoSecretKey_serialVersionUID -4795878709595146952LL

@protocol JavaxCryptoSecretKey < JavaSecurityKey, NSObject, JavaObject >
@end

__attribute__((always_inline)) inline void JavaxCryptoSecretKey_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaxCryptoSecretKey, serialVersionUID, jlong)

#endif // _JavaxCryptoSecretKey_H_
