//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/xml/parsers/DocumentBuilderFactory.java
//

#ifndef _JavaxXmlParsersDocumentBuilderFactory_H_
#define _JavaxXmlParsersDocumentBuilderFactory_H_

@class JavaLangClassLoader;
@class JavaxXmlParsersDocumentBuilder;
@class JavaxXmlValidationSchema;

#import "JreEmulation.h"

@interface JavaxXmlParsersDocumentBuilderFactory : NSObject {
 @public
  jboolean validating_;
  jboolean namespaceAware_;
  jboolean whitespace_;
  jboolean expandEntityRef_;
  jboolean ignoreComments_;
  jboolean coalescing_;
}

- (instancetype)init;

+ (JavaxXmlParsersDocumentBuilderFactory *)newInstance OBJC_METHOD_FAMILY_NONE;

+ (JavaxXmlParsersDocumentBuilderFactory *)newInstanceWithNSString:(NSString *)factoryClassName
                                           withJavaLangClassLoader:(JavaLangClassLoader *)classLoader OBJC_METHOD_FAMILY_NONE;

- (JavaxXmlParsersDocumentBuilder *)newDocumentBuilder OBJC_METHOD_FAMILY_NONE;

- (void)setNamespaceAwareWithBoolean:(jboolean)awareness;

- (void)setValidatingWithBoolean:(jboolean)validating;

- (void)setIgnoringElementContentWhitespaceWithBoolean:(jboolean)whitespace;

- (void)setExpandEntityReferencesWithBoolean:(jboolean)expandEntityRef;

- (void)setIgnoringCommentsWithBoolean:(jboolean)ignoreComments;

- (void)setCoalescingWithBoolean:(jboolean)coalescing;

- (jboolean)isNamespaceAware;

- (jboolean)isValidating;

- (jboolean)isIgnoringElementContentWhitespace;

- (jboolean)isExpandEntityReferences;

- (jboolean)isIgnoringComments;

- (jboolean)isCoalescing;

- (void)setAttributeWithNSString:(NSString *)name
                          withId:(id)value;

- (id)getAttributeWithNSString:(NSString *)name;

- (void)setFeatureWithNSString:(NSString *)name
                   withBoolean:(jboolean)value;

- (jboolean)getFeatureWithNSString:(NSString *)name;

- (JavaxXmlValidationSchema *)getSchema;

- (void)setSchemaWithJavaxXmlValidationSchema:(JavaxXmlValidationSchema *)schema;

- (void)setXIncludeAwareWithBoolean:(jboolean)state;

- (jboolean)isXIncludeAware;

- (void)copyAllFieldsTo:(JavaxXmlParsersDocumentBuilderFactory *)other;

@end

__attribute__((always_inline)) inline void JavaxXmlParsersDocumentBuilderFactory_init() {}

#endif // _JavaxXmlParsersDocumentBuilderFactory_H_
