//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/xml/transform/dom/DOMLocator.java
//

#ifndef _JavaxXmlTransformDomDOMLocator_H_
#define _JavaxXmlTransformDomDOMLocator_H_

@protocol OrgW3cDomNode;

#import "JreEmulation.h"
#include "javax/xml/transform/SourceLocator.h"

@protocol JavaxXmlTransformDomDOMLocator < JavaxXmlTransformSourceLocator, NSObject, JavaObject >
- (id<OrgW3cDomNode>)getOriginatingNode;

@end

__attribute__((always_inline)) inline void JavaxXmlTransformDomDOMLocator_init() {}

#endif // _JavaxXmlTransformDomDOMLocator_H_
