//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/xml/transform/dom/DOMResult.java
//

#ifndef _JavaxXmlTransformDomDOMResult_H_
#define _JavaxXmlTransformDomDOMResult_H_

@protocol OrgW3cDomNode;

#import "JreEmulation.h"
#include "javax/xml/transform/Result.h"

@interface JavaxXmlTransformDomDOMResult : NSObject < JavaxXmlTransformResult > {
 @public
  id<OrgW3cDomNode> node_;
  id<OrgW3cDomNode> nextSibling_;
  NSString *systemId_;
}

- (instancetype)init;

- (instancetype)initWithOrgW3cDomNode:(id<OrgW3cDomNode>)node;

- (instancetype)initWithOrgW3cDomNode:(id<OrgW3cDomNode>)node
                         withNSString:(NSString *)systemId;

- (instancetype)initWithOrgW3cDomNode:(id<OrgW3cDomNode>)node
                    withOrgW3cDomNode:(id<OrgW3cDomNode>)nextSibling;

- (instancetype)initWithOrgW3cDomNode:(id<OrgW3cDomNode>)node
                    withOrgW3cDomNode:(id<OrgW3cDomNode>)nextSibling
                         withNSString:(NSString *)systemId;

- (void)setNodeWithOrgW3cDomNode:(id<OrgW3cDomNode>)node;

- (id<OrgW3cDomNode>)getNode;

- (void)setNextSiblingWithOrgW3cDomNode:(id<OrgW3cDomNode>)nextSibling;

- (id<OrgW3cDomNode>)getNextSibling;

- (void)setSystemIdWithNSString:(NSString *)systemId;

- (NSString *)getSystemId;

- (void)copyAllFieldsTo:(JavaxXmlTransformDomDOMResult *)other;

@end

__attribute__((always_inline)) inline void JavaxXmlTransformDomDOMResult_init() {}

J2OBJC_FIELD_SETTER(JavaxXmlTransformDomDOMResult, node_, id<OrgW3cDomNode>)
J2OBJC_FIELD_SETTER(JavaxXmlTransformDomDOMResult, nextSibling_, id<OrgW3cDomNode>)
J2OBJC_FIELD_SETTER(JavaxXmlTransformDomDOMResult, systemId_, NSString *)

FOUNDATION_EXPORT NSString *JavaxXmlTransformDomDOMResult_FEATURE_;
J2OBJC_STATIC_FIELD_GETTER(JavaxXmlTransformDomDOMResult, FEATURE_, NSString *)

#endif // _JavaxXmlTransformDomDOMResult_H_
