//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/xml/transform/dom/DOMSource.java
//

#ifndef _JavaxXmlTransformDomDOMSource_H_
#define _JavaxXmlTransformDomDOMSource_H_

@protocol OrgW3cDomNode;

#import "JreEmulation.h"
#include "javax/xml/transform/Source.h"

@interface JavaxXmlTransformDomDOMSource : NSObject < JavaxXmlTransformSource > {
 @public
  id<OrgW3cDomNode> node_;
  NSString *systemID_;
}

- (instancetype)init;

- (instancetype)initWithOrgW3cDomNode:(id<OrgW3cDomNode>)n;

- (instancetype)initWithOrgW3cDomNode:(id<OrgW3cDomNode>)node
                         withNSString:(NSString *)systemID;

- (void)setNodeWithOrgW3cDomNode:(id<OrgW3cDomNode>)node;

- (id<OrgW3cDomNode>)getNode;

- (void)setSystemIdWithNSString:(NSString *)systemID;

- (NSString *)getSystemId;

- (void)copyAllFieldsTo:(JavaxXmlTransformDomDOMSource *)other;

@end

__attribute__((always_inline)) inline void JavaxXmlTransformDomDOMSource_init() {}

J2OBJC_FIELD_SETTER(JavaxXmlTransformDomDOMSource, node_, id<OrgW3cDomNode>)
J2OBJC_FIELD_SETTER(JavaxXmlTransformDomDOMSource, systemID_, NSString *)

FOUNDATION_EXPORT NSString *JavaxXmlTransformDomDOMSource_FEATURE_;
J2OBJC_STATIC_FIELD_GETTER(JavaxXmlTransformDomDOMSource, FEATURE_, NSString *)

#endif // _JavaxXmlTransformDomDOMSource_H_
