//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/security/auth/login/LoginException.java
//

#ifndef _JavaxSecurityAuthLoginLoginException_H_
#define _JavaxSecurityAuthLoginLoginException_H_

#import "JreEmulation.h"
#include "java/security/GeneralSecurityException.h"

#define JavaxSecurityAuthLoginLoginException_serialVersionUID -4679091624035232488LL

@interface JavaxSecurityAuthLoginLoginException : JavaSecurityGeneralSecurityException {
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)message;

@end

__attribute__((always_inline)) inline void JavaxSecurityAuthLoginLoginException_init() {}

J2OBJC_STATIC_FIELD_GETTER(JavaxSecurityAuthLoginLoginException, serialVersionUID, jlong)

#endif // _JavaxSecurityAuthLoginLoginException_H_
