//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/security/auth/login/LoginException.java
//

#ifndef _JavaxSecurityAuthLoginLoginException_H_
#define _JavaxSecurityAuthLoginLoginException_H_

#include "J2ObjC_header.h"
#include "java/security/GeneralSecurityException.h"

@interface JavaxSecurityAuthLoginLoginException : JavaSecurityGeneralSecurityException

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)message;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxSecurityAuthLoginLoginException)

FOUNDATION_EXPORT void JavaxSecurityAuthLoginLoginException_init(JavaxSecurityAuthLoginLoginException *self);

FOUNDATION_EXPORT JavaxSecurityAuthLoginLoginException *new_JavaxSecurityAuthLoginLoginException_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JavaxSecurityAuthLoginLoginException_initWithNSString_(JavaxSecurityAuthLoginLoginException *self, NSString *message);

FOUNDATION_EXPORT JavaxSecurityAuthLoginLoginException *new_JavaxSecurityAuthLoginLoginException_initWithNSString_(NSString *message) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaxSecurityAuthLoginLoginException)

#endif // _JavaxSecurityAuthLoginLoginException_H_
