//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/xml/transform/ErrorListener.java
//

#ifndef _JavaxXmlTransformErrorListener_H_
#define _JavaxXmlTransformErrorListener_H_

@class JavaxXmlTransformTransformerException;

#import "JreEmulation.h"

@protocol JavaxXmlTransformErrorListener < NSObject, JavaObject >

- (void)warningWithJavaxXmlTransformTransformerException:(JavaxXmlTransformTransformerException *)exception;

- (void)errorWithJavaxXmlTransformTransformerException:(JavaxXmlTransformTransformerException *)exception;

- (void)fatalErrorWithJavaxXmlTransformTransformerException:(JavaxXmlTransformTransformerException *)exception;

@end

__attribute__((always_inline)) inline void JavaxXmlTransformErrorListener_init() {}

#endif // _JavaxXmlTransformErrorListener_H_
