//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/xml/transform/SourceLocator.java
//

#ifndef _JavaxXmlTransformSourceLocator_H_
#define _JavaxXmlTransformSourceLocator_H_

#import "JreEmulation.h"

@protocol JavaxXmlTransformSourceLocator < NSObject, JavaObject >

- (NSString *)getPublicId;

- (NSString *)getSystemId;

- (jint)getLineNumber;

- (jint)getColumnNumber;

@end

__attribute__((always_inline)) inline void JavaxXmlTransformSourceLocator_init() {}

#endif // _JavaxXmlTransformSourceLocator_H_
