//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/xml/transform/Source.java
//

#ifndef _JavaxXmlTransformSource_H_
#define _JavaxXmlTransformSource_H_

#import "JreEmulation.h"

@protocol JavaxXmlTransformSource < NSObject, JavaObject >

- (void)setSystemIdWithNSString:(NSString *)systemId;

- (NSString *)getSystemId;

@end

__attribute__((always_inline)) inline void JavaxXmlTransformSource_init() {}

#endif // _JavaxXmlTransformSource_H_
