//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/xml/transform/Templates.java
//

#ifndef _JavaxXmlTransformTemplates_H_
#define _JavaxXmlTransformTemplates_H_

@class JavaUtilProperties;
@class JavaxXmlTransformTransformer;

#import "JreEmulation.h"

@protocol JavaxXmlTransformTemplates < NSObject, JavaObject >

- (JavaxXmlTransformTransformer *)newTransformer OBJC_METHOD_FAMILY_NONE;

- (JavaUtilProperties *)getOutputProperties;

@end

__attribute__((always_inline)) inline void JavaxXmlTransformTemplates_init() {}

#endif // _JavaxXmlTransformTemplates_H_
