//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/xml/transform/TransformerFactory.java
//

#ifndef _JavaxXmlTransformTransformerFactory_H_
#define _JavaxXmlTransformTransformerFactory_H_

@class JavaLangClassLoader;
@class JavaxXmlTransformTransformer;
@protocol JavaxXmlTransformErrorListener;
@protocol JavaxXmlTransformSource;
@protocol JavaxXmlTransformTemplates;
@protocol JavaxXmlTransformURIResolver;

#import "JreEmulation.h"

@interface JavaxXmlTransformTransformerFactory : NSObject {
}

- (instancetype)init;

+ (JavaxXmlTransformTransformerFactory *)newInstance OBJC_METHOD_FAMILY_NONE;

+ (JavaxXmlTransformTransformerFactory *)newInstanceWithNSString:(NSString *)factoryClassName
                                         withJavaLangClassLoader:(JavaLangClassLoader *)classLoader OBJC_METHOD_FAMILY_NONE;

- (JavaxXmlTransformTransformer *)newTransformerWithJavaxXmlTransformSource:(id<JavaxXmlTransformSource>)source OBJC_METHOD_FAMILY_NONE;

- (JavaxXmlTransformTransformer *)newTransformer OBJC_METHOD_FAMILY_NONE;

- (id<JavaxXmlTransformTemplates>)newTemplatesWithJavaxXmlTransformSource:(id<JavaxXmlTransformSource>)source OBJC_METHOD_FAMILY_NONE;

- (id<JavaxXmlTransformSource>)getAssociatedStylesheetWithJavaxXmlTransformSource:(id<JavaxXmlTransformSource>)source
                                                                     withNSString:(NSString *)media
                                                                     withNSString:(NSString *)title
                                                                     withNSString:(NSString *)charset;

- (void)setURIResolverWithJavaxXmlTransformURIResolver:(id<JavaxXmlTransformURIResolver>)resolver;

- (id<JavaxXmlTransformURIResolver>)getURIResolver;

- (void)setFeatureWithNSString:(NSString *)name
                   withBoolean:(jboolean)value;

- (jboolean)getFeatureWithNSString:(NSString *)name;

- (void)setAttributeWithNSString:(NSString *)name
                          withId:(id)value;

- (id)getAttributeWithNSString:(NSString *)name;

- (void)setErrorListenerWithJavaxXmlTransformErrorListener:(id<JavaxXmlTransformErrorListener>)listener;

- (id<JavaxXmlTransformErrorListener>)getErrorListener;

@end

__attribute__((always_inline)) inline void JavaxXmlTransformTransformerFactory_init() {}

#endif // _JavaxXmlTransformTransformerFactory_H_
