//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/xml/transform/TransformerException.java
//

#ifndef _JavaxXmlTransformTransformerException_H_
#define _JavaxXmlTransformTransformerException_H_

@class JavaIoPrintStream;
@class JavaIoPrintWriter;
@class JavaLangThrowable;
@protocol JavaxXmlTransformSourceLocator;

#import "JreEmulation.h"
#include "java/lang/Exception.h"

#define JavaxXmlTransformTransformerException_serialVersionUID 975798773772956428LL

@interface JavaxXmlTransformTransformerException : JavaLangException {
 @public
  id<JavaxXmlTransformSourceLocator> locator_;
  JavaLangThrowable *containedException_;
}

- (id<JavaxXmlTransformSourceLocator>)getLocator;

- (void)setLocatorWithJavaxXmlTransformSourceLocator:(id<JavaxXmlTransformSourceLocator>)location;

- (JavaLangThrowable *)getException;

- (JavaLangThrowable *)getCause;

- (JavaLangThrowable *)initCauseWithJavaLangThrowable:(JavaLangThrowable *)cause OBJC_METHOD_FAMILY_NONE;

- (instancetype)initWithNSString:(NSString *)message;

- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)e;

- (instancetype)initWithNSString:(NSString *)message
           withJavaLangThrowable:(JavaLangThrowable *)e;

- (instancetype)initWithNSString:(NSString *)message
withJavaxXmlTransformSourceLocator:(id<JavaxXmlTransformSourceLocator>)locator;

- (instancetype)initWithNSString:(NSString *)message
withJavaxXmlTransformSourceLocator:(id<JavaxXmlTransformSourceLocator>)locator
           withJavaLangThrowable:(JavaLangThrowable *)e;

- (NSString *)getMessageAndLocation;

- (NSString *)getLocationAsString;

- (void)printStackTrace;

- (void)printStackTraceWithJavaIoPrintStream:(JavaIoPrintStream *)s;

- (void)printStackTraceWithJavaIoPrintWriter:(JavaIoPrintWriter *)s;

- (void)copyAllFieldsTo:(JavaxXmlTransformTransformerException *)other;

@end

__attribute__((always_inline)) inline void JavaxXmlTransformTransformerException_init() {}

J2OBJC_FIELD_SETTER(JavaxXmlTransformTransformerException, locator_, id<JavaxXmlTransformSourceLocator>)
J2OBJC_FIELD_SETTER(JavaxXmlTransformTransformerException, containedException_, JavaLangThrowable *)

J2OBJC_STATIC_FIELD_GETTER(JavaxXmlTransformTransformerException, serialVersionUID, jlong)

#endif // _JavaxXmlTransformTransformerException_H_
