//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/xml/transform/TransformerConfigurationException.java
//

#ifndef _JavaxXmlTransformTransformerConfigurationException_H_
#define _JavaxXmlTransformTransformerConfigurationException_H_

@class JavaLangThrowable;
@protocol JavaxXmlTransformSourceLocator;

#import "JreEmulation.h"
#include "javax/xml/transform/TransformerException.h"

@interface JavaxXmlTransformTransformerConfigurationException : JavaxXmlTransformTransformerException {
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)msg;

- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)e;

- (instancetype)initWithNSString:(NSString *)msg
           withJavaLangThrowable:(JavaLangThrowable *)e;

- (instancetype)initWithNSString:(NSString *)message
withJavaxXmlTransformSourceLocator:(id<JavaxXmlTransformSourceLocator>)locator;

- (instancetype)initWithNSString:(NSString *)message
withJavaxXmlTransformSourceLocator:(id<JavaxXmlTransformSourceLocator>)locator
           withJavaLangThrowable:(JavaLangThrowable *)e;

@end

__attribute__((always_inline)) inline void JavaxXmlTransformTransformerConfigurationException_init() {}

#endif // _JavaxXmlTransformTransformerConfigurationException_H_
