//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/xml/transform/Transformer.java
//

#ifndef _JavaxXmlTransformTransformer_H_
#define _JavaxXmlTransformTransformer_H_

@class JavaUtilProperties;
@protocol JavaxXmlTransformErrorListener;
@protocol JavaxXmlTransformResult;
@protocol JavaxXmlTransformSource;
@protocol JavaxXmlTransformURIResolver;

#import "JreEmulation.h"

@interface JavaxXmlTransformTransformer : NSObject {
}

- (instancetype)init;

- (void)reset;

- (void)transformWithJavaxXmlTransformSource:(id<JavaxXmlTransformSource>)xmlSource
                 withJavaxXmlTransformResult:(id<JavaxXmlTransformResult>)outputTarget;

- (void)setParameterWithNSString:(NSString *)name
                          withId:(id)value;

- (id)getParameterWithNSString:(NSString *)name;

- (void)clearParameters;

- (void)setURIResolverWithJavaxXmlTransformURIResolver:(id<JavaxXmlTransformURIResolver>)resolver;

- (id<JavaxXmlTransformURIResolver>)getURIResolver;

- (void)setOutputPropertiesWithJavaUtilProperties:(JavaUtilProperties *)oformat;

- (JavaUtilProperties *)getOutputProperties;

- (void)setOutputPropertyWithNSString:(NSString *)name
                         withNSString:(NSString *)value;

- (NSString *)getOutputPropertyWithNSString:(NSString *)name;

- (void)setErrorListenerWithJavaxXmlTransformErrorListener:(id<JavaxXmlTransformErrorListener>)listener;

- (id<JavaxXmlTransformErrorListener>)getErrorListener;

@end

__attribute__((always_inline)) inline void JavaxXmlTransformTransformer_init() {}

#endif // _JavaxXmlTransformTransformer_H_
