//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/xml/transform/TransformerFactoryConfigurationError.java
//

#ifndef _JavaxXmlTransformTransformerFactoryConfigurationError_H_
#define _JavaxXmlTransformTransformerFactoryConfigurationError_H_

@class JavaLangException;

#import "JreEmulation.h"
#include "java/lang/Error.h"

@interface JavaxXmlTransformTransformerFactoryConfigurationError : JavaLangError {
 @public
  JavaLangException *exception_;
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)msg;

- (instancetype)initWithJavaLangException:(JavaLangException *)e;

- (instancetype)initWithJavaLangException:(JavaLangException *)e
                             withNSString:(NSString *)msg;

- (NSString *)getMessage;

- (JavaLangException *)getException;

- (void)copyAllFieldsTo:(JavaxXmlTransformTransformerFactoryConfigurationError *)other;

@end

__attribute__((always_inline)) inline void JavaxXmlTransformTransformerFactoryConfigurationError_init() {}

J2OBJC_FIELD_SETTER(JavaxXmlTransformTransformerFactoryConfigurationError, exception_, JavaLangException *)

#endif // _JavaxXmlTransformTransformerFactoryConfigurationError_H_
