//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/javax/xml/transform/URIResolver.java
//

#ifndef _JavaxXmlTransformURIResolver_H_
#define _JavaxXmlTransformURIResolver_H_

@protocol JavaxXmlTransformSource;

#import "JreEmulation.h"

@protocol JavaxXmlTransformURIResolver < NSObject, JavaObject >

- (id<JavaxXmlTransformSource>)resolveWithNSString:(NSString *)href
                                      withNSString:(NSString *)base;

@end

__attribute__((always_inline)) inline void JavaxXmlTransformURIResolver_init() {}

#endif // _JavaxXmlTransformURIResolver_H_
