//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/content/res/AssetManager.java
//

#ifndef _AndroidContentResAssetManager_H_
#define _AndroidContentResAssetManager_H_

@class JavaIoInputStream;

#import "JreEmulation.h"

@protocol AndroidContentResAssetManager < NSObject, JavaObject >

- (JavaIoInputStream *)openWithNSString:(NSString *)pStrName;

@end

__attribute__((always_inline)) inline void AndroidContentResAssetManager_init() {}

#endif // _AndroidContentResAssetManager_H_
