//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/content/res/AssetManager.java
//

#ifndef _AndroidContentResAssetManager_H_
#define _AndroidContentResAssetManager_H_

#include "J2ObjC_header.h"

@class JavaIoInputStream;

@protocol AndroidContentResAssetManager < NSObject, JavaObject >

- (JavaIoInputStream *)openWithNSString:(NSString *)pStrName;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidContentResAssetManager)

J2OBJC_TYPE_LITERAL_HEADER(AndroidContentResAssetManager)

#endif // _AndroidContentResAssetManager_H_
