//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/content/res/DisplayMetrics.java
//

#ifndef _AndroidContentResDisplayMetrics_H_
#define _AndroidContentResDisplayMetrics_H_

#import "JreEmulation.h"

#define AndroidContentResDisplayMetrics_density 0.0f
#define AndroidContentResDisplayMetrics_widthPixels 0.0f

@protocol AndroidContentResDisplayMetrics < NSObject, JavaObject >

@end

__attribute__((always_inline)) inline void AndroidContentResDisplayMetrics_init() {}

J2OBJC_STATIC_FIELD_GETTER(AndroidContentResDisplayMetrics, density, jfloat)

J2OBJC_STATIC_FIELD_GETTER(AndroidContentResDisplayMetrics, widthPixels, jfloat)

#endif // _AndroidContentResDisplayMetrics_H_
