//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/content/res/DisplayMetrics.java
//

#ifndef _AndroidContentResDisplayMetrics_H_
#define _AndroidContentResDisplayMetrics_H_

#include "J2ObjC_header.h"

#define AndroidContentResDisplayMetrics_density 0.0f
#define AndroidContentResDisplayMetrics_widthPixels 0.0f

@protocol AndroidContentResDisplayMetrics < NSObject, JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidContentResDisplayMetrics)

J2OBJC_STATIC_FIELD_GETTER(AndroidContentResDisplayMetrics, density, jfloat)

J2OBJC_STATIC_FIELD_GETTER(AndroidContentResDisplayMetrics, widthPixels, jfloat)

J2OBJC_TYPE_LITERAL_HEADER(AndroidContentResDisplayMetrics)

#endif // _AndroidContentResDisplayMetrics_H_
