//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/content/res/Resources.java
//

#ifndef _AndroidContentResResources_H_
#define _AndroidContentResResources_H_

#include "J2ObjC_header.h"

@class AndroidUtilTypedValue;
@class IOSIntArray;
@protocol AndroidContentResDisplayMetrics;
@protocol AndroidContentResTypedArray;
@protocol AndroidGraphicsDrawableDrawable;
@protocol AndroidUtilAttributeSet;
@protocol JavaLangCharSequence;

@protocol AndroidContentResResources < NSObject, JavaObject >

- (NSString *)getStringWithInt:(jint)pKey;

- (jint)getColorWithInt:(jint)pKey;

- (jint)getDimensionPixelSizeWithInt:(jint)pKey;

- (id<AndroidContentResDisplayMetrics>)getDisplayMetrics;

- (id<AndroidGraphicsDrawableDrawable>)getDrawableWithInt:(jint)pKey;

- (jboolean)getBooleanWithInt:(jint)pKey;

- (id<JavaLangCharSequence>)getTextWithInt:(jint)pKey;

- (jint)getIntegerWithInt:(jint)pKey;

- (NSString *)getStringWithInt:(jint)pKey
                  withNSString:(NSString *)pDefault;

- (void)getValueWithInt:(jint)pKey
withAndroidUtilTypedValue:(AndroidUtilTypedValue *)pOut
            withBoolean:(jboolean)pResolveRefs;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidContentResResources)

J2OBJC_TYPE_LITERAL_HEADER(AndroidContentResResources)

@protocol AndroidContentResResources_Theme < NSObject, JavaObject >

- (id<AndroidContentResTypedArray>)obtainStyledAttributesWithAndroidUtilAttributeSet:(id<AndroidUtilAttributeSet>)pAttribs
                                                                        withIntArray:(IOSIntArray *)pView
                                                                             withInt:(jint)pI
                                                                             withInt:(jint)pI2;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidContentResResources_Theme)

J2OBJC_TYPE_LITERAL_HEADER(AndroidContentResResources_Theme)

#endif // _AndroidContentResResources_H_
