//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/content/res/TypedArray.java
//

#ifndef _AndroidContentResTypedArray_H_
#define _AndroidContentResTypedArray_H_

#import "JreEmulation.h"

@protocol AndroidContentResTypedArray < NSObject, JavaObject >

- (jboolean)getBooleanWithInt:(jint)pDiagramviewTripping
                  withBoolean:(jboolean)pB;

- (jint)getColorWithInt:(jint)pDiagramviewTextColor
                withInt:(jint)pTextColor;

- (jint)getDimensionPixelSizeWithInt:(jint)pExtslidingpanelayoutOverhangsize
                             withInt:(jint)pDefaultOverhangSize;

- (jfloat)getFloatWithInt:(jint)pExtslidingpanelayoutRelativeoverhangsize
                withFloat:(jfloat)pF;

- (jint)getIntWithInt:(jint)pManipulatortouchdispatcherOrientation
              withInt:(jint)pI;

- (void)recycle;

@end

__attribute__((always_inline)) inline void AndroidContentResTypedArray_init() {}

#endif // _AndroidContentResTypedArray_H_
