//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/apache/harmony/xml/parsers/DocumentBuilderFactoryImpl.java
//

#ifndef _OrgApacheHarmonyXmlParsersDocumentBuilderFactoryImpl_H_
#define _OrgApacheHarmonyXmlParsersDocumentBuilderFactoryImpl_H_

@class JavaxXmlParsersDocumentBuilder;

#import "JreEmulation.h"
#include "javax/xml/parsers/DocumentBuilderFactory.h"

@interface OrgApacheHarmonyXmlParsersDocumentBuilderFactoryImpl : JavaxXmlParsersDocumentBuilderFactory {
}

- (id)getAttributeWithNSString:(NSString *)name;

- (jboolean)getFeatureWithNSString:(NSString *)name;

- (JavaxXmlParsersDocumentBuilder *)newDocumentBuilder OBJC_METHOD_FAMILY_NONE;

- (void)setAttributeWithNSString:(NSString *)name
                          withId:(id)value;

- (void)setFeatureWithNSString:(NSString *)name
                   withBoolean:(jboolean)value;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgApacheHarmonyXmlParsersDocumentBuilderFactoryImpl_init() {}

FOUNDATION_EXPORT NSString *OrgApacheHarmonyXmlParsersDocumentBuilderFactoryImpl_NAMESPACES_;
J2OBJC_STATIC_FIELD_GETTER(OrgApacheHarmonyXmlParsersDocumentBuilderFactoryImpl, NAMESPACES_, NSString *)

FOUNDATION_EXPORT NSString *OrgApacheHarmonyXmlParsersDocumentBuilderFactoryImpl_VALIDATION_;
J2OBJC_STATIC_FIELD_GETTER(OrgApacheHarmonyXmlParsersDocumentBuilderFactoryImpl, VALIDATION_, NSString *)

#endif // _OrgApacheHarmonyXmlParsersDocumentBuilderFactoryImpl_H_
