//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/content/Context.java
//

#ifndef _AndroidContentContext_H_
#define _AndroidContentContext_H_

#include "J2ObjC_header.h"

@class IOSIntArray;
@class JavaIoFile;
@protocol AndroidContentResAssetManager;
@protocol AndroidContentResResources;
@protocol AndroidContentResResources_Theme;
@protocol AndroidContentResTypedArray;
@protocol AndroidUtilAttributeSet;

#define AndroidContentContext_MODE_PRIVATE 0

@protocol AndroidContentContext < NSObject, JavaObject >

- (id<AndroidContentResResources>)getResources;

- (id<AndroidContentResResources_Theme>)getTheme;

- (id<AndroidContentResTypedArray>)obtainStyledAttributesWithAndroidUtilAttributeSet:(id<AndroidUtilAttributeSet>)pAttrs
                                                                        withIntArray:(IOSIntArray *)pAttrs2;

- (id<AndroidContentResAssetManager>)getAssets;

- (JavaIoFile *)getCacheDir;

- (JavaIoFile *)getDatabasePathWithNSString:(NSString *)pDbName;

- (JavaIoFile *)getFilesDir;

- (NSString *)getStringWithInt:(jint)pKey;

- (id)getSystemServiceWithNSString:(NSString *)pKey;

- (void)deleteDatabaseWithNSString:(NSString *)pName;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidContentContext)

FOUNDATION_EXPORT NSString *AndroidContentContext_INPUT_METHOD_SERVICE_;
J2OBJC_STATIC_FIELD_GETTER(AndroidContentContext, INPUT_METHOD_SERVICE_, NSString *)

J2OBJC_STATIC_FIELD_GETTER(AndroidContentContext, MODE_PRIVATE, jint)

FOUNDATION_EXPORT NSString *AndroidContentContext_TELEPHONY_SERVICE_;
J2OBJC_STATIC_FIELD_GETTER(AndroidContentContext, TELEPHONY_SERVICE_, NSString *)

J2OBJC_TYPE_LITERAL_HEADER(AndroidContentContext)

#endif // _AndroidContentContext_H_
