//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/w3c/dom/Attr.java
//

#ifndef _OrgW3cDomAttr_H_
#define _OrgW3cDomAttr_H_

@protocol OrgW3cDomElement;
@protocol OrgW3cDomTypeInfo;

#import "JreEmulation.h"
#include "org/w3c/dom/Node.h"

@protocol OrgW3cDomAttr < OrgW3cDomNode, NSObject, JavaObject >
- (NSString *)getName;

- (jboolean)getSpecified;

- (NSString *)getValue;

- (void)setValueWithNSString:(NSString *)value;

- (id<OrgW3cDomElement>)getOwnerElement;

- (id<OrgW3cDomTypeInfo>)getSchemaTypeInfo;

- (jboolean)isId;

@end

__attribute__((always_inline)) inline void OrgW3cDomAttr_init() {}

#endif // _OrgW3cDomAttr_H_
