//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/w3c/dom/CDATASection.java
//

#ifndef _OrgW3cDomCDATASection_H_
#define _OrgW3cDomCDATASection_H_

#import "JreEmulation.h"
#include "org/w3c/dom/Text.h"

@protocol OrgW3cDomCDATASection < OrgW3cDomText, NSObject, JavaObject >
@end

__attribute__((always_inline)) inline void OrgW3cDomCDATASection_init() {}

#endif // _OrgW3cDomCDATASection_H_
