//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/w3c/dom/CDATASection.java
//

#ifndef _OrgW3cDomCDATASection_H_
#define _OrgW3cDomCDATASection_H_

#include "J2ObjC_header.h"
#include "org/w3c/dom/Text.h"

@protocol OrgW3cDomCDATASection < OrgW3cDomText, NSObject, JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(OrgW3cDomCDATASection)

J2OBJC_TYPE_LITERAL_HEADER(OrgW3cDomCDATASection)

#endif // _OrgW3cDomCDATASection_H_
