//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/w3c/dom/Comment.java
//

#ifndef _OrgW3cDomComment_H_
#define _OrgW3cDomComment_H_

#import "JreEmulation.h"
#include "org/w3c/dom/CharacterData.h"

@protocol OrgW3cDomComment < OrgW3cDomCharacterData, NSObject, JavaObject >
@end

__attribute__((always_inline)) inline void OrgW3cDomComment_init() {}

#endif // _OrgW3cDomComment_H_
