//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/w3c/dom/DocumentFragment.java
//

#ifndef _OrgW3cDomDocumentFragment_H_
#define _OrgW3cDomDocumentFragment_H_

#import "JreEmulation.h"
#include "org/w3c/dom/Node.h"

@protocol OrgW3cDomDocumentFragment < OrgW3cDomNode, NSObject, JavaObject >
@end

__attribute__((always_inline)) inline void OrgW3cDomDocumentFragment_init() {}

#endif // _OrgW3cDomDocumentFragment_H_
