//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/w3c/dom/DOMConfiguration.java
//

#ifndef _OrgW3cDomDOMConfiguration_H_
#define _OrgW3cDomDOMConfiguration_H_

@protocol OrgW3cDomDOMStringList;

#import "JreEmulation.h"

@protocol OrgW3cDomDOMConfiguration < NSObject, JavaObject >

- (void)setParameterWithNSString:(NSString *)name
                          withId:(id)value;

- (id)getParameterWithNSString:(NSString *)name;

- (jboolean)canSetParameterWithNSString:(NSString *)name
                                 withId:(id)value;

- (id<OrgW3cDomDOMStringList>)getParameterNames;

@end

__attribute__((always_inline)) inline void OrgW3cDomDOMConfiguration_init() {}

#endif // _OrgW3cDomDOMConfiguration_H_
