//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/w3c/dom/DOMConfiguration.java
//

#ifndef _OrgW3cDomDOMConfiguration_H_
#define _OrgW3cDomDOMConfiguration_H_

#include "J2ObjC_header.h"

@protocol OrgW3cDomDOMStringList;

@protocol OrgW3cDomDOMConfiguration < NSObject, JavaObject >

- (void)setParameterWithNSString:(NSString *)name
                          withId:(id)value;

- (id)getParameterWithNSString:(NSString *)name;

- (jboolean)canSetParameterWithNSString:(NSString *)name
                                 withId:(id)value;

- (id<OrgW3cDomDOMStringList>)getParameterNames;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgW3cDomDOMConfiguration)

J2OBJC_TYPE_LITERAL_HEADER(OrgW3cDomDOMConfiguration)

#endif // _OrgW3cDomDOMConfiguration_H_
