//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/w3c/dom/DOMErrorHandler.java
//

#ifndef _OrgW3cDomDOMErrorHandler_H_
#define _OrgW3cDomDOMErrorHandler_H_

@protocol OrgW3cDomDOMError;

#import "JreEmulation.h"

@protocol OrgW3cDomDOMErrorHandler < NSObject, JavaObject >

- (jboolean)handleErrorWithOrgW3cDomDOMError:(id<OrgW3cDomDOMError>)error;

@end

__attribute__((always_inline)) inline void OrgW3cDomDOMErrorHandler_init() {}

#endif // _OrgW3cDomDOMErrorHandler_H_
