//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/w3c/dom/DOMImplementationSource.java
//

#ifndef _OrgW3cDomDOMImplementationSource_H_
#define _OrgW3cDomDOMImplementationSource_H_

@protocol OrgW3cDomDOMImplementation;
@protocol OrgW3cDomDOMImplementationList;

#import "JreEmulation.h"

@protocol OrgW3cDomDOMImplementationSource < NSObject, JavaObject >

- (id<OrgW3cDomDOMImplementation>)getDOMImplementationWithNSString:(NSString *)features;

- (id<OrgW3cDomDOMImplementationList>)getDOMImplementationListWithNSString:(NSString *)features;

@end

__attribute__((always_inline)) inline void OrgW3cDomDOMImplementationSource_init() {}

#endif // _OrgW3cDomDOMImplementationSource_H_
