//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/w3c/dom/DOMImplementationList.java
//

#ifndef _OrgW3cDomDOMImplementationList_H_
#define _OrgW3cDomDOMImplementationList_H_

@protocol OrgW3cDomDOMImplementation;

#import "JreEmulation.h"

@protocol OrgW3cDomDOMImplementationList < NSObject, JavaObject >

- (id<OrgW3cDomDOMImplementation>)itemWithInt:(jint)index;

- (jint)getLength;

@end

__attribute__((always_inline)) inline void OrgW3cDomDOMImplementationList_init() {}

#endif // _OrgW3cDomDOMImplementationList_H_
