//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/w3c/dom/DOMImplementation.java
//

#ifndef _OrgW3cDomDOMImplementation_H_
#define _OrgW3cDomDOMImplementation_H_

@protocol OrgW3cDomDocument;
@protocol OrgW3cDomDocumentType;

#import "JreEmulation.h"

@protocol OrgW3cDomDOMImplementation < NSObject, JavaObject >

- (jboolean)hasFeatureWithNSString:(NSString *)feature
                      withNSString:(NSString *)version_;

- (id<OrgW3cDomDocumentType>)createDocumentTypeWithNSString:(NSString *)qualifiedName
                                               withNSString:(NSString *)publicId
                                               withNSString:(NSString *)systemId;

- (id<OrgW3cDomDocument>)createDocumentWithNSString:(NSString *)namespaceURI
                                       withNSString:(NSString *)qualifiedName
                          withOrgW3cDomDocumentType:(id<OrgW3cDomDocumentType>)doctype;

- (id)getFeatureWithNSString:(NSString *)feature
                withNSString:(NSString *)version_;

@end

__attribute__((always_inline)) inline void OrgW3cDomDOMImplementation_init() {}

#endif // _OrgW3cDomDOMImplementation_H_
