//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/w3c/dom/DOMLocator.java
//

#ifndef _OrgW3cDomDOMLocator_H_
#define _OrgW3cDomDOMLocator_H_

@protocol OrgW3cDomNode;

#import "JreEmulation.h"

@protocol OrgW3cDomDOMLocator < NSObject, JavaObject >

- (jint)getLineNumber;

- (jint)getColumnNumber;

- (jint)getByteOffset;

- (jint)getUtf16Offset;

- (id<OrgW3cDomNode>)getRelatedNode;

- (NSString *)getUri;

@end

__attribute__((always_inline)) inline void OrgW3cDomDOMLocator_init() {}

#endif // _OrgW3cDomDOMLocator_H_
