//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/w3c/dom/DOMStringList.java
//

#ifndef _OrgW3cDomDOMStringList_H_
#define _OrgW3cDomDOMStringList_H_

#import "JreEmulation.h"

@protocol OrgW3cDomDOMStringList < NSObject, JavaObject >

- (NSString *)itemWithInt:(jint)index;

- (jint)getLength;

- (jboolean)containsWithNSString:(NSString *)str;

@end

__attribute__((always_inline)) inline void OrgW3cDomDOMStringList_init() {}

#endif // _OrgW3cDomDOMStringList_H_
