//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/w3c/dom/Entity.java
//

#ifndef _OrgW3cDomEntity_H_
#define _OrgW3cDomEntity_H_

#import "JreEmulation.h"
#include "org/w3c/dom/Node.h"

@protocol OrgW3cDomEntity < OrgW3cDomNode, NSObject, JavaObject >
- (NSString *)getPublicId;

- (NSString *)getSystemId;

- (NSString *)getNotationName;

- (NSString *)getInputEncoding;

- (NSString *)getXmlEncoding;

- (NSString *)getXmlVersion;

@end

__attribute__((always_inline)) inline void OrgW3cDomEntity_init() {}

#endif // _OrgW3cDomEntity_H_
