//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/w3c/dom/EntityReference.java
//

#ifndef _OrgW3cDomEntityReference_H_
#define _OrgW3cDomEntityReference_H_

#import "JreEmulation.h"
#include "org/w3c/dom/Node.h"

@protocol OrgW3cDomEntityReference < OrgW3cDomNode, NSObject, JavaObject >
@end

__attribute__((always_inline)) inline void OrgW3cDomEntityReference_init() {}

#endif // _OrgW3cDomEntityReference_H_
