//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/w3c/dom/NamedNodeMap.java
//

#ifndef _OrgW3cDomNamedNodeMap_H_
#define _OrgW3cDomNamedNodeMap_H_

@protocol OrgW3cDomNode;

#import "JreEmulation.h"

@protocol OrgW3cDomNamedNodeMap < NSObject, JavaObject >

- (id<OrgW3cDomNode>)getNamedItemWithNSString:(NSString *)name;

- (id<OrgW3cDomNode>)setNamedItemWithOrgW3cDomNode:(id<OrgW3cDomNode>)arg;

- (id<OrgW3cDomNode>)removeNamedItemWithNSString:(NSString *)name;

- (id<OrgW3cDomNode>)itemWithInt:(jint)index;

- (jint)getLength;

- (id<OrgW3cDomNode>)getNamedItemNSWithNSString:(NSString *)namespaceURI
                                   withNSString:(NSString *)localName;

- (id<OrgW3cDomNode>)setNamedItemNSWithOrgW3cDomNode:(id<OrgW3cDomNode>)arg;

- (id<OrgW3cDomNode>)removeNamedItemNSWithNSString:(NSString *)namespaceURI
                                      withNSString:(NSString *)localName;

@end

__attribute__((always_inline)) inline void OrgW3cDomNamedNodeMap_init() {}

#endif // _OrgW3cDomNamedNodeMap_H_
