//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/w3c/dom/NodeList.java
//

#ifndef _OrgW3cDomNodeList_H_
#define _OrgW3cDomNodeList_H_

@protocol OrgW3cDomNode;

#import "JreEmulation.h"

@protocol OrgW3cDomNodeList < NSObject, JavaObject >

- (id<OrgW3cDomNode>)itemWithInt:(jint)index;

- (jint)getLength;

@end

__attribute__((always_inline)) inline void OrgW3cDomNodeList_init() {}

#endif // _OrgW3cDomNodeList_H_
