//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/w3c/dom/ProcessingInstruction.java
//

#ifndef _OrgW3cDomProcessingInstruction_H_
#define _OrgW3cDomProcessingInstruction_H_

#import "JreEmulation.h"
#include "org/w3c/dom/Node.h"

@protocol OrgW3cDomProcessingInstruction < OrgW3cDomNode, NSObject, JavaObject >
- (NSString *)getTarget;

- (NSString *)getData;

- (void)setDataWithNSString:(NSString *)data;

@end

__attribute__((always_inline)) inline void OrgW3cDomProcessingInstruction_init() {}

#endif // _OrgW3cDomProcessingInstruction_H_
