//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/org/w3c/dom/UserDataHandler.java
//

#ifndef _OrgW3cDomUserDataHandler_H_
#define _OrgW3cDomUserDataHandler_H_

@protocol OrgW3cDomNode;

#import "JreEmulation.h"

#define OrgW3cDomUserDataHandler_NODE_ADOPTED 5
#define OrgW3cDomUserDataHandler_NODE_CLONED 1
#define OrgW3cDomUserDataHandler_NODE_DELETED 3
#define OrgW3cDomUserDataHandler_NODE_IMPORTED 2
#define OrgW3cDomUserDataHandler_NODE_RENAMED 4

@protocol OrgW3cDomUserDataHandler < NSObject, JavaObject >

- (void)handleWithShort:(jshort)operation
           withNSString:(NSString *)key
                 withId:(id)data
      withOrgW3cDomNode:(id<OrgW3cDomNode>)src
      withOrgW3cDomNode:(id<OrgW3cDomNode>)dst;

@end

__attribute__((always_inline)) inline void OrgW3cDomUserDataHandler_init() {}

J2OBJC_STATIC_FIELD_GETTER(OrgW3cDomUserDataHandler, NODE_CLONED, jshort)

J2OBJC_STATIC_FIELD_GETTER(OrgW3cDomUserDataHandler, NODE_IMPORTED, jshort)

J2OBJC_STATIC_FIELD_GETTER(OrgW3cDomUserDataHandler, NODE_DELETED, jshort)

J2OBJC_STATIC_FIELD_GETTER(OrgW3cDomUserDataHandler, NODE_RENAMED, jshort)

J2OBJC_STATIC_FIELD_GETTER(OrgW3cDomUserDataHandler, NODE_ADOPTED, jshort)

#endif // _OrgW3cDomUserDataHandler_H_
