//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/os/Bundle.java
//

#ifndef _AndroidOsBundle_H_
#define _AndroidOsBundle_H_

@class JavaUtilArrayList;
@protocol AndroidOsParcelable;

#import "JreEmulation.h"

@interface AndroidOsBundle : NSObject {
}

- (instancetype)init;

- (jint)getIntWithNSString:(NSString *)pKey;

- (jboolean)getBooleanWithNSString:(NSString *)pKey
                       withBoolean:(jboolean)pValue;

- (void)putIntWithNSString:(NSString *)pKey
                   withInt:(jint)pValue;

- (void)putBooleanWithNSString:(NSString *)pKey
                   withBoolean:(jboolean)pValue;

- (void)putParcelableWithNSString:(NSString *)pKey
          withAndroidOsParcelable:(id<AndroidOsParcelable>)pValue;

- (void)putStringWithNSString:(NSString *)pKey
                 withNSString:(NSString *)pValue;

- (void)putDoubleWithNSString:(NSString *)pKey
                   withDouble:(jdouble)pValue;

- (id)getParcelableWithNSString:(NSString *)pKey;

- (NSString *)getStringWithNSString:(NSString *)pKey;

- (jdouble)getDoubleWithNSString:(NSString *)pKey;

- (jint)getIntWithNSString:(NSString *)pKey
                   withInt:(jint)pDefault;

- (NSString *)getStringWithNSString:(NSString *)pKey
                       withNSString:(NSString *)pDefault;

- (JavaUtilArrayList *)getParcelableArrayListWithNSString:(NSString *)pKey;

- (void)putParcelableArrayListWithNSString:(NSString *)pKey
                     withJavaUtilArrayList:(JavaUtilArrayList *)pValue;

@end

__attribute__((always_inline)) inline void AndroidOsBundle_init() {}

#endif // _AndroidOsBundle_H_
