//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/os/Parcel.java
//

#ifndef _AndroidOsParcel_H_
#define _AndroidOsParcel_H_

#include "J2ObjC_header.h"

@class IOSBooleanArray;
@class IOSCharArray;
@class IOSDoubleArray;
@class IOSFloatArray;
@class IOSIntArray;
@class IOSObjectArray;
@class JavaLangBoolean;
@class JavaLangClassLoader;
@protocol AndroidOsParcelable;
@protocol JavaUtilMap;

@protocol AndroidOsParcel < NSObject, JavaObject >

- (void)readBooleanArrayWithBooleanArray:(IOSBooleanArray *)pNewArray;

- (void)readCharArrayWithCharArray:(IOSCharArray *)pNewArray;

- (jdouble)readDouble;

- (jfloat)readFloat;

- (void)writeFloatWithFloat:(jfloat)pValue;

- (void)writeFloatArrayWithFloatArray:(IOSFloatArray *)pValue;

- (void)readFloatArrayWithFloatArray:(IOSFloatArray *)pValue;

- (void)readMapWithJavaUtilMap:(id<JavaUtilMap>)pMap
       withJavaLangClassLoader:(JavaLangClassLoader *)pClassloader;

- (void)writeMapWithJavaUtilMap:(id<JavaUtilMap>)pMap;

- (void)readDoubleArrayWithDoubleArray:(IOSDoubleArray *)pNewArray;

- (jshort)readInt;

- (void)readIntArrayWithIntArray:(IOSIntArray *)pValues;

- (id)readParcelableWithJavaLangClassLoader:(JavaLangClassLoader *)pClassLoader;

- (IOSObjectArray *)readParcelableArrayWithJavaLangClassLoader:(JavaLangClassLoader *)pClassLoader;

- (void)writeCharArrayWithCharArray:(IOSCharArray *)pCharArray;

- (void)writeDoubleWithDouble:(jdouble)pValue;

- (void)writeDoubleArrayWithDoubleArray:(IOSDoubleArray *)pValues;

- (void)writeIntWithInt:(jint)pValue;

- (void)writeStringWithNSString:(NSString *)pValue;

- (void)writeStringArrayWithNSStringArray:(IOSObjectArray *)pValues;

- (void)writeValueWithBoolean:(jboolean)pValue;

- (NSString *)readString;

- (void)readStringArrayWithNSStringArray:(IOSObjectArray *)pNewArray;

- (JavaLangBoolean *)readValueWithId:(id)pObject;

- (void)writeBooleanArrayWithBooleanArray:(IOSBooleanArray *)pValues;

- (void)writeIntArrayWithIntArray:(IOSIntArray *)pValues;

- (void)writeParcelableWithAndroidOsParcelable:(id<AndroidOsParcelable>)pParcelable
                                       withInt:(jint)pFlags;

- (void)writeParcelableArrayWithAndroidOsParcelableArray:(IOSObjectArray *)pArray
                                                 withInt:(jint)pFlags;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidOsParcel)

J2OBJC_TYPE_LITERAL_HEADER(AndroidOsParcel)

#endif // _AndroidOsParcel_H_
