//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/os/Parcelable.java
//

#ifndef _AndroidOsParcelable_H_
#define _AndroidOsParcelable_H_

@class IOSObjectArray;
@protocol AndroidOsParcel;

#import "JreEmulation.h"

@protocol AndroidOsParcelable < NSObject, JavaObject >

- (jint)describeContents;

- (void)writeToParcelWithAndroidOsParcel:(id<AndroidOsParcel>)pParcel
                                 withInt:(jint)pFlags;

@end

__attribute__((always_inline)) inline void AndroidOsParcelable_init() {}

@protocol AndroidOsParcelable_Creator < NSObject, JavaObject >

- (id)createFromParcelWithAndroidOsParcel:(id<AndroidOsParcel>)pSource;

- (IOSObjectArray *)newArrayWithInt:(jint)pSize OBJC_METHOD_FAMILY_NONE;

@end

__attribute__((always_inline)) inline void AndroidOsParcelable_Creator_init() {}

#endif // _AndroidOsParcelable_H_
