//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/os/Parcel.java
//

#ifndef _AndroidOsParcel_H_
#define _AndroidOsParcel_H_

@class IOSBooleanArray;
@class IOSCharArray;
@class IOSDoubleArray;
@class IOSIntArray;
@class IOSObjectArray;
@class JavaLangBoolean;
@class JavaLangClassLoader;
@protocol AndroidOsParcelable;

#import "JreEmulation.h"

@protocol AndroidOsParcel < NSObject, JavaObject >

- (void)readBooleanArrayWithBooleanArray:(IOSBooleanArray *)pNewArray;

- (void)readCharArrayWithCharArray:(IOSCharArray *)pNewArray;

- (jdouble)readDouble;

- (void)readDoubleArrayWithDoubleArray:(IOSDoubleArray *)pNewArray;

- (jshort)readInt;

- (void)readIntArrayWithIntArray:(IOSIntArray *)pValues;

- (id)readParcelableWithJavaLangClassLoader:(JavaLangClassLoader *)pClassLoader;

- (IOSObjectArray *)readParcelableArrayWithJavaLangClassLoader:(JavaLangClassLoader *)pClassLoader;

- (void)writeCharArrayWithCharArray:(IOSCharArray *)pCharArray;

- (void)writeDoubleWithDouble:(jdouble)pValue;

- (void)writeDoubleArrayWithDoubleArray:(IOSDoubleArray *)pValues;

- (void)writeIntWithInt:(jint)pValue;

- (void)writeStringWithNSString:(NSString *)pValue;

- (void)writeStringArrayWithNSStringArray:(IOSObjectArray *)pValues;

- (void)writeValueWithBoolean:(jboolean)pValue;

- (NSString *)readString;

- (void)readStringArrayWithNSStringArray:(IOSObjectArray *)pNewArray;

- (JavaLangBoolean *)readValueWithId:(id)pObject;

- (void)writeBooleanArrayWithBooleanArray:(IOSBooleanArray *)pValues;

- (void)writeIntArrayWithIntArray:(IOSIntArray *)pValues;

- (void)writeParcelableWithAndroidOsParcelable:(id<AndroidOsParcelable>)pParcelable
                                       withInt:(jint)pFlags;

- (void)writeParcelableArrayWithAndroidOsParcelableArray:(IOSObjectArray *)pArray
                                                 withInt:(jint)pFlags;

@end

__attribute__((always_inline)) inline void AndroidOsParcel_init() {}

#endif // _AndroidOsParcel_H_
