//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.siemens.android.wrapper/src/android/os/Parcelable.java
//

#ifndef _AndroidOsParcelable_H_
#define _AndroidOsParcelable_H_

#include "J2ObjC_header.h"

@class IOSObjectArray;
@protocol AndroidOsParcel;

@protocol AndroidOsParcelable < NSObject, JavaObject >

- (jint)describeContents;

- (void)writeToParcelWithAndroidOsParcel:(id<AndroidOsParcel>)pParcel
                                 withInt:(jint)pFlags;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidOsParcelable)

J2OBJC_TYPE_LITERAL_HEADER(AndroidOsParcelable)

@protocol AndroidOsParcelable_Creator < NSObject, JavaObject >

- (id)createFromParcelWithAndroidOsParcel:(id<AndroidOsParcel>)pSource;

- (IOSObjectArray *)newArrayWithInt:(jint)pSize OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidOsParcelable_Creator)

J2OBJC_TYPE_LITERAL_HEADER(AndroidOsParcelable_Creator)

#endif // _AndroidOsParcelable_H_
